### ISSUE TITLE
PDF2 plug-in fails when processing bookmap with DITA composite

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1077]
Converted from [SourceForge issue 1803111](http://sourceforge.net/support/tracker.php?aid=1803111), submitted by chris-sf

Bookmap processing by PDF2 plug-in 1.4 fails or only renders first child of DITA composite file topicref.

For a bookmap with following structure:

```
bookmap
  chapter
    topicref A (DITA composite)
    topicref B (DITA topic)
```

Topicref A points to a DITA composite file with this structure:

```
dita
  topic (A1)
  concept (A2)
  reference (A3)
  task (A4)
```

When the bookmap is rendered using the PDF2 plug-in, the process fails or you get the following PDF:

```
book
 chapter 1
  topic A1
  topic B
```

A2, A3, and A4 are missing.

**Comment by robander** [comment]
Taking another look at this one. Still not quite sure where to make the modification.
* Update topicmerge? If here, we end up with a merged map that has out of date info in the `<map>` portion, unless topicmerge re-implements title / link text pulling, which seems like poor design.
* In preprocess, after chunking? This seems the best spot. The map can be updated to refer to each topic. But this might result in unexpected output for some formats - not sure about it. Other formats could probably use the update, but like PDF, could still need an update to some sort of merged format.
* Before chunking, update references to these topics to add `chunk="by-topic"`? This would work for formats like PDF or EPUB, but could be undesirable for formats like HTML that have always produced a single output document.

Sample map attached below.
[1077.zip](https://github.com/dita-ot/dita-ot/files/232587/1077.zip)

**Comment by robander** [comment]
Had one other thought over the weekend. The `job.xml` file could be updated to note which files are composite files (root element `<dita>`) ... but I'm not sure if that would really improve efficiency of processing on those documents.

**Comment by robander** [comment]
Further work on this, playing in topicmerge today, a few notes:

- The Java portion of topicmerge drops `<dita>` wrappers with a comment calling them "redundant": https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/reader/MergeTopicParser.java#L204
- When I remove that (and the dropped end tag), `<dita>` is preserved in the merged file, the contents all appear in the PDF and in the bookmarks. This seems ... like a suspiciously easy fix. I don't understand exactly how it's working from the XSL, since (for example) bookmarks are created with a for-each over `/*/*[contains(@class,' topic/topic ')]`, but these topics are now nested within `/*/dita`.

Testing with and without this change:
- If I reference a composite doc with `composite.dita` before the fix, only the first topic appears; after the fix, everything appears. Yay!
- If I reference `composite.dita` and then add a second reference to `composite.dita`, before the fix, I get the first topic each time; after the fix, I get the whole document the first time, but the second reference to `composite.dita#last` is entirely ignored. An improvement for the first reference, second is broken in a different way.
- If I reference `composite.dita` and then add a reference to `composite.dita#last` (for the last topic), before the fix, I get the first and last topic; after the fix, I get the whole document first, but the reference to `composite.dita#last` is entirely ignored. An improvement for the first reference, second is broken in a different way.
- If I reference just `composite.dita#last`, then both _with and without this fix_, the PDF ends up with only the _first_ topic. I assume because the code that updates `@href` in the `<topicref>` elements explicitly pulls `firstTopicId`. Broken in both cases, unafffected by this change.

So with just this change:

- The original issue is fixed
- Repeat references to the document work differently than before
- References to a topic other than the first, without a reference to the full document, are still broken
