### ISSUE TITLE
Support for references in SVG graphics

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1123]
Converted from [SourceForge issue 1747147](http://sourceforge.net/support/tracker.php?aid=1747147), submitted by davidjbh

SVG Graphics can include links to other graphics using one of two methods:
- image xlink:href="location"
- use xlink:href="location"

DOST collects up the SVG file, and copies it to the output, but doesn't collect up any referenced graphics.

**Comment by geekgrrl** [comment]
This is still not fixed in DITA OT 2.3. Is a fix still coming?

**Comment by shaneataylor** [comment]
I've started work on this.

**Comment by shaneataylor** [comment]
Here are the assumptions I am making.

1. Special processing of embedded or referenced SVGs is reserved only for `<svgref>` and `<svg:svg>` descendants of `<svg-container>` (and of course, elements specialized from these). SVG files referenced by `<image>` are unchanged.
2. SVG dependency files include CSS, other SVGs, raster image formats, and Javascript.
3. SVG in HTML outputs (except for CHM) can be manipulated dynamically (this is part of the value). For that reason, local dependencies (inferred by a relative path in `xlink:href`) should be copied to the output directory for resolution by the rendering browser. Non-local dependencies are assumed to be available on rendering.
4. SVG in other outputs is assumed to be static. For that reason, both local and non-local dependencies should be resolved at build time. The most flexible way to do this for all deliverables is to embed these resources (with the exception of Javascript) in the referencing SVG so they are available to later processing steps (for example, FOP). For static SVG, Javascript resources are ignored.
5. SVGs referenced by `<svgref>` are embedded in the topic as inline SVGs before other processing is done. This ensures that all SVGs are parsed in the same way, and allows different instances of the same SVG target to be rendered contextually (see the enhancements below).

I think the following enhancements would also be useful, but they might be implemented later rather than as part of basic SVG support:

1. `<svg:use>` elements that point to DITA resources should resolve to the appropriate textual content of those resources: references to topics or titled elements resolve to the textual content of the title, while references to other elements resolve to the textual content of the targeted element. This extension allows an SVG illustration to be relabeled by the build in a way that is intuitive to DITA users.
2. Empty `<svg:a>` elements that point to DITA resources should resolve in a similar manner, while also adding a link to the targeted resource.
