### ISSUE TITLE
Xref to topic fails when copy-to used on topicref

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1227]
Converted from [SourceForge issue 3496422](http://sourceforge.net/support/tracker.php?aid=3496422), submitted by robertnthomas

Consider the following xref contained in topic snafoo.dita:

```
See <xref href=”foo.dita#foo”> for more information.
```

And the following target (foo.dita):

```
<topic id=”foo”><title>Foo</title></topic>
```

When foo.dita is brought into the bookmap as follows, the xref link resolves correctly:

```
<topicref href=”foo.dita”/>
```

However, when foo.dita is brought into the bookmap as follows, the xref link does not resolve:

```
<topicref href=”foo.dita” copy-to=”bar.dita”/>
```

**Comment by eerohele** [comment]
Using my sample files, at the end of the merge process, the [`idMap` HashTable](https://github.com/dita-ot/dita-ot/blob/c682aef06f7d58c5ad2a159a0c2a98298dff4b4c/src/main/java/org/dita/dost/util/MergeUtils.java#L31) looks like this:

```
{
topic3.dita#topic3=unique_3,
bar.dita=unique_4,
topic1.dita#topic1=unique_1,
bar.dita#topic2=unique_4,
topic3.dita=unique_3,
topic1.dita=unique_1,
topic2.dita#topic2=unique_2
}
```

`root_MERGED.xml` has an entry like this:

```xml
<topic … oid="topic2" id="unique_4">
```

Whereas the `<xref>` to `topic2.dita#topic2` looks like this:

```xml
<xref href="#unique_2" … ohref="topic2.dita#topic2"> … </xref>
```

In other words, the link points to `#unique2`, but that doesn't exist, since `#topic2` gets `#unique_4` as its ID instead. `#unique4` is the ID assigned to the non-existent `bar.dita`.

It also follows that having `<xref href="bar.dita"/>` in `topic1.dita` works but `<xref href="topic2.dita#topic2"/>` doesn't. I don't think an `<xref>` element that points to the value of a `@copy-to` attribute is meant to work...?

The culprit is [L196–199 in `MergeMapParser.java`](https://github.com/dita-ot/dita-ot/blob/c682aef06f7d58c5ad2a159a0c2a98298dff4b4c/src/main/java/org/dita/dost/reader/MergeMapParser.java#L196-L199), and removing those lines fixes the issue. I'm not sure why they've been added in the first place since I'm don't think the copy-to feature should figure into the topicmerge process at all. Should it?

**Comment by drmacro** [comment]
Before DITA 1.2 the only way to reliably address a specific use of a topic was to put a copy-to attribute on the topicref and use the copy-to URI as the URI on an xref. But that is of course problematic because now the URI on the xref points to a thing that doesn't literally exist in the source, even though the author intent is clear. But of course if the topic is reused in a different map that map must also provide a topic with the same effective URI as the one defined by the @copy-to in the first map (which is almost the same requirement as key references, but a bit harder to manage).

With DITA 1.2 you can put a unique key on each use of a topic and then author the xrefs to the key, which removes the need for @copy-to in order to simply enable the link to a specific use (but @copy-to may be required simply to control the anchor value of the rendered version of the topic. [And in fact the latest DITA Community adjust-copy-to preprocessing extension provides the option to use the @keys value to construct the @copy-to value.])

**Comment by jelovirt** [comment]
Copy-to processing will need to be revised for DITA 1.3 processing and the way we currently do it (early) don't work in all cases.

**Comment by naguila** [comment]
I can reproduce in PDF and XHTML using OT 1.8.5 with @eerohele fixtures. The error may not get noticed in XHTML because the transtype writes both `@href` and `@copy-to` files to the output, but the xref link in XHTML points to `@href` when it should be to `@copy-to`.

I found a possible workaround specifying both `@copy-to` and `chunk="to-content"` in the topicref element as result of investigating the following code:

[GenListModuleReader.java#L1373](https://github.com/dita-ot/dita-ot/blob/hotfix/1.8.5/src/main/java/org/dita/dost/reader/GenListModuleReader.java#L1373)

**Comment by jelovirt** [comment]
Closing as inactive. Since the link points to a file that doesn't exist, a broken link is basically correct too.
