### ISSUE TITLE
topicsetref generates duplicate ID

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1233]
Converted from [SourceForge issue 3512608](http://sourceforge.net/support/tracker.php?aid=3512608), submitted by tmakita

If I use topicset & topisetref in the bookmap, DITA-OT generates duplicate id in the result bookmap. This causes error in the formatting phase.
The test data is quite simple.

``` xml
 <topicset id="a1" navtitle="Topicset">
   <topicref>
     <topicref href="taskbook/task_preface.dita"></topicref>
   </topicref>
 </topicset>
 <topicsetref href="#a1" navtitle="Topicsetref"></topicsetref>
```

In this case the id value "a1" remains both topicset defined side topicref and referenced side of topicref.
Please fix this bug. I attached test data and result bookmap file generated in the temp directory.

**Comment by robander** [comment]
Using the sample file linked by @eerohele in the 2014 comment, I'm no longer able to reproduce any error using PDF2 output.

**Comment by eerohele** [comment]
I just tried this with 1.5.4 and I don't actually see any errors in the formatting phase, so I'm not sure what the original report refers to. It looks like the duplicate ID is still there even with the latest code, though, but I'm not sure whether that actually causes any errors. As you said, it doesn't prevent PDF2 output generation, at least.

**Comment by robander** [comment]
Ah, OK - so "error in the result phase" might just mean that a strict tool reports bad FO, even if it's able to recover (and if that warning doesn't end up in the DITA-OT log). Thanks for double checking.

**Comment by robander** [comment]
For default processing - this still takes place in the upcoming 2.5. It's really not a `topicset` specific issue; the same thing happens if I have:
```
<topicref id="a1">
  <topicref href="inner.dita" id="inner"/>
</topicref>
<topicref href="#a1" format="ditamap"/>
```

In that case, both the `a1` and `inner` IDs are duplicated in the result after mapref. That said - the topicmerge process already handles this, and generates IDs for any duplicates, so we don't end up with issues.

I'm not sure of the best resolution for this. Given the ways that maps can be chained together, it's not clear whether the 1st, 2nd, or Nth instance of an ID is the one to keep; you could also end up pulling in many instances of `id="ouch"` from many different maps. Basically, any change we make here seems as likely to break something as it is to fix something.

The one thing I can think of is that, potentially, the `clean-map` step that ends preprocessing could be updated to check for and strip duplicate IDs. You'd end up saving only the first copy of an ID within the map; I'm not sure if this would be better, worse, or equivalent to the current behavior, but it would technically make the map follow the original DITA rules a bit more closely.

The topicmerge

**Comment by robander** [comment]
On second thought - `clean-map` is not intended to do validation or fixup of the map so this shouldn't go there.

`mappull` seems more appropriate, as it already does a lot to massage the map. I'm still not sure if this should go in overall but the following bit of code in mappull will clean out any duplicate IDs:
```
<xsl:key name="ids" match="*[@id]" use="@id"/>
  <xsl:template match="@id">
    <xsl:attribute name="id" 
      select="if (generate-id(parent::*)=generate-id(key('ids',.)[1])) then (.) else (concat('dupid',generate-id(..)))"/>
  </xsl:template>
```
