### ISSUE TITLE
Doesn't work with SAXON 9 HE (9.4.0.3)

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1238]
Converted from [SourceForge issue 3519820](http://sourceforge.net/support/tracker.php?aid=3519820), submitted by @mkarg

I tried to run DITA-OT with saxon9he.jar contained in SAXON 9 HE (9.4.0.3) original zip archive, but DITA-OT does not work. Using the sxaon9.jar + saxon9-dom.jar contained in the "DITA-OT Full Bundle", DITA-OT is working correctly. It seems DITA-OT is dependend of exactly this revision of saxon 9!

Here is the error message:

>  [maplink] ...\maplinkImpl.xsl:130: Fatal Error! Cannot find a matching 1-argument function named {http://exslt.org/common}node-set(). There is no Saxon extension function with the local name node-set

In fact SAXON is right, as SAXON is a XSLT 2.0 processor, so node-set() is not needed. This is not pure XSLT, so it is incorrect to say that SAXON can drive DITA-OT. In fact, only the SAXON contained in DITA-OT can drive DITA-OT.

A simple solution would be to upgrade your XSLT level to 2.0, so this non-standard function can be removed.

**Comment by eerohele** [comment]
I think the only places that still use Java extensions are `generalize.xsl`, which is addressed by #2158, and [`dita2rtf-img.xsl`](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.wordrtf/xsl/xslrtf/dita2rtf-img.xsl), which has a single Java extension function call.

Not sure what to do with `dita2rtf-img.xsl`... could we just add Saxon-J as a dependency for that particular plugin (maybe during #2121?) and update to Saxon-HE otherwise? It'd be nice to be able to use XPath 3.0 (which recent Saxon-HE versions support).

**Comment by jelovirt** [comment]
Closed by #2668
