### ISSUE TITLE
Properly support <imagemap> for PDF output

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1458]
Right now the XSL `org.dita.pdf2/xsl/fo/commons.xsl` ignores the coordinates specified for an image map:

```xml
<xsl:template match="*[contains(@class,' ut-d/shape ')]"/>
<xsl:template match="*[contains(@class,' ut-d/coords ')]"/>
```

Looking at various posts it seems feasible to add hotspots on the image based on the coordinates:
http://groups.yahoo.com/group/XSL-FO/message/2317

So maybe for the future we could consider fully implementing image map support in PDF.

**Comment by robander** [comment]
This came up for some of our users today. On a related note - did you know that in at least some search engines, if you look for "xsl:fo image map", this issue is the top result? Probably worse now that I've added that comment.

The second hit was this stack overflow response last year indicating that FO doesn't natively support image maps, and that you should use SVG:
http://stackoverflow.com/questions/37564802/area-attribute-in-xsl-fo-external-graphic-with-coordinates

From the @drmacro post you linked to (a mere 15 years old) suggests we could actually make use of the coordinates ... but I wonder if the more reliable solution at this point might be "use SVG". SVG should also be more portable across other formats, where images could be sized differently and a hard-coded 1in by 1in box wouldn't be possible. From a quick test by my co-worker, links in the SVG are supported by both AH and FOP.

**Comment by raducoravu** [comment]
Ideally for producing the PDF we should have a parameter deciding if end user wants PDF for print or PDF for web. Because with PDF for print you want those links to appear under the image, ideally the image would also present the hotspot borders and show some figures on each of them.
With PDF for web you do not want the links under the image + you do not want the page number on each link.

**Comment by jelovirt** [comment]
@raducoravu an property to control whether print or online PDF is generated should be a separate feature request.

**Comment by raducoravu** [comment]
I added it separately:
https://github.com/dita-ot/dita-ot/issues/2671

**Comment by Nico-Amplexor** [comment]
Hi,
A plugin is available here to manage imagemap element in PDF with SVG : [com.amplexor.imagemap-pdf](https://www.dita-ot.org/plugins#!com.amplexor.imagemap-pdf)

**Comment by raducoravu** [comment]
@Nico-Amplexor Great, I worked a little bit with the plugin, it's an interesting idea to add that SVG layer. Maybe you can also write about it on the DITA Users List, there may be others interested in your work. 
Would it have been possible to add the imagemap processing without declaring the extra transtype so that it would have been applied maybe with a parameter to disable or enable it for the default DITA OT PDF transtype? 
Also the links from the hotspots shown on the image to the targets did not work for me, I produced the PDF using Apache FOP and using the Mac OSX Preview to visualize the PDF. 
I'm working with a sample DITA Map bundled with Oxygen XML Editor located in "OXYGEN_INSTALL_DIR/samples/dita/image-map/gear-pump.ditamap".

**Comment by Nico-Amplexor** [comment]
Hi @raducoravu ,

Thanks for your remark about the parameter to disable or enable it for the default DITA OT PDF transtype. I will implement that in the next release.

Concerning FOP, it seems that link doesn't work inside a local file (opened from the system) but it works if you copy the PDF on an Apache server for example, see https://www.oxygenxml.com/forum/post57688.html#p57688. I also forgot to add <fox:destination internal-destination="xxx"/> to make it work (in next release).

**Comment by raducoravu** [comment]
@Nico-Amplexor thanks for taking my suggestions into account, we'll probably do something similar for our DITA to PDF using CSS processing approach.
