### ISSUE TITLE
@chunk="to-content" in map causes file not found error

### ISSUE THREAD

**Issue by btp** [dita-ot/dita-ot#1470]
When using @chunk="to-content" in a ditamap file,
the topicpull process throws ``Error! java.io.FileNotFoundException:''
for each topic in the ditamap. These errors do not seem to affect the
success of the output.

Method to reproduce:
- Add @chunk="to-content" to samples/hierarchy.ditamap.
- Build the xhtml: ant -f samples/ant_sample/sample_xhtml.xml

**Comment by AJOwens** [comment]
Hi. I've just started working with DITA 2.0 and I am seeing this issue.

I have modified hierarchy.ditamap and sequence.ditamap to add @chunk="to-content" in the <map> element, and renamed them hierarchy_to_content.ditamap and sequence_to_content.ditamap. When I try to build html5 help using the command "dita -f html5 -i samples/hierarchy_to_content.ditamap -o test/html5", I get many errors of the form "The file. . . is not available to resolve link information."  

It's worth noting that the errors specify files such as /concept/sequence_to_content.dita or /task/sequence_to_content.dita, where the "task" or "concept" folder is appended. The file sequence_to_content.dita does exist in the temporary directory, but it doesn't exist in these subfolders.

**Comment by robander** [comment]
I'm not able to reproduce this with 3.1. I followed the last steps above (rename `hierarchy.ditamap` to `hierarchy_to_content.ditamap`, set the chunk value to `to-content` on the map, and build), but got a single HTML5 output file without any build errors. Generated file content is correct with working links. I think this issue is obsolete.
