### ISSUE TITLE
Map Titles Do Not Appear in Output

### ISSUE THREAD

**Issue by dautry** [dita-ot/dita-ot#1656]
Map title elements do not appear in generated output (PDF2) using DITA OT 1.84.

```
<bookmap>
    <mapref href="map1234.ditamap"/>
</bookmap>

<map> [map1234.ditamap]
    <title>Will not appear in output</title>
    <topicref href="12345.xml" type="concept"/>
</map>
```

It appears it's being dropped in the topic merge.  The title does not appear in the merged XML file.

**Comment by hajarghaem** [comment]
Dear,
I need to extract the title of all my submaps. I read your comments and know that it is not possible in the standard Dita-OT. I was wondering if/how I can customize Dita-OT in order to reuse the title of my submap (that are referenced via a mapref).
Thanks in advance,
Hajar

**Comment by xephon2** [comment]
Hi Hajar,

I do not know what you want to achieve, but maybe it would help you to extract the title to a `<keyword>` element and reuse it. I attached you an example. It is hopefully self-explaining.

[1656.zip](https://github.com/dita-ot/dita-ot/files/434591/1656.zip)

Greetings,
Stefan

**Comment by hajarghaem** [comment]
Hi Stefan,

Thanks for your fast response :). I just tested you code. I added a text inside the title element of submap.ditamap file. Then when I transformed map.ditamap into pdf (using Dita-OT 2.x in Oxygen ) I cannot see that tile.
I have a lot of content that I do not want to change them, and am looking for a way to automatically extract this type of title.
I attached my edited code.
Please let me know your feedback.
Thanks in advance,
Hajar 
[1656Edited.zip](https://github.com/dita-ot/dita-ot/files/434616/1656Edited.zip)

**Comment by hajarghaem** [comment]
I actually, need to show this title in the bookmark, TOC, and also in the pdf as part of content. I have been working on customization approach but still cannot find out a workaround.
Kind regards,
Hajar

**Comment by xephon2** [comment]
Hi Hajar,

why don't you just use a topic as a container. This is the common DITA way to achieve what you want to do (at least what I think you want to do).

[1656.zip](https://github.com/dita-ot/dita-ot/files/434733/1656.zip)

Is this helpful?

Greetings,
Stefan

**Comment by hajarghaem** [comment]
Hi Stefan,

Thanks for your time.
I have a lot of input dita map files that have other submaps. Each submap file has its own title. I do not want to change or add anything to my inputs. Thus I cannot use your solution.
As <mapref> has <title> element, I suppose that I can access somewho (in theory) to the value of this element.
If I want to use another way I may use <topichead>as a parent of <mapref>. 

Could you please let me know if there is any way in [customization]((http://www.dita-ot.org/1.8/readme/dita2pdf-customization.html) approach? 

Thanks in advance,
Hajar

**Comment by xephon2** [comment]
Hi Hajar,

sorry, but I cannot help you. I assume, this is not doable with a small customization. Maybe someone else can help you.

Good luck :four_leaf_clover: ,
Stefan

**Comment by drmacro** [comment]
You would need to modify the map merge process to generate topichead elements corresponding to the submaps and their titles.

By definition of the DITA standard submap titles are ignored when constructing the effective map from a tree of maps and submaps.

I understand that this is something many authors misunderstand about DITA but nevertheless it is how DITA is defined (and if you think about it it's the only way things can work otherwise you wouldn't be able to have maps that serve as both root maps and submaps when you *do not* want the submap titles to contribute to the navigation hierarchy.

So ultimately you should upgrade your source documents.

You basically have two choices:

1. Wrap each submap reference in a topichead or reference to a topic that has the title you want.
2. Add a top-level topichead or reference to a topic that has the title you want in each submap.

If you want to impose this pattern everywhere then it's a fairly easy one-time transform to apply to your content.

**Comment by hajarghaem** [comment]
Dear,
Thanks you all.
-Hajar
