### ISSUE TITLE
Re-check and rephrase messages.xml

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1709]
The messages XML document:

     DITA-OT/plugins/org.dita.pdf2/resource/messages.xml

contains messages shown by the DITA OT when running. Some of them seem to have been written by a non-English speaker. 
Example:

       There are multiple index entry found which is opening range for ID="%1" but there is only one which close it or ranges are overlapping.

      There are multiple index entry found which closing range for ID="%1".

Maybe they should be reviewed.

**Comment by robander** [comment]
Saw this when scanning through older issues - I can take it now unless @infotexture wants to grab it, or has perhaps already done some work on it?

**Comment by infotexture** [comment]
@robander — Please do. 

You probably know more about the context in which each of these messages is likely to appear. 

Let me know _(or send a docs PR)_ if there are any for which you'd like to add **Additional details** in docs via [DITA-messages-details.xml](https://github.com/dita-ot/docs/blob/develop/user-guide/DITA-messages-details.xml) .

**Comment by robander** [comment]
I'll work on updating them. Some today have content in the `<response>` section that is really more appropriate for Additional detail, as in the following, where the `<response>` is not actually a response:

```xml
  <message id="DOTA067W" type="WARN">
    <reason>Ignoring index-see '%1' inside parent index entry '%2' because the parent indexterm contains indexterm children.</reason>
    <response>According to the DITA Specification, the index-see element should be ignored if the parent indexterm contains other indexterm children.</response>
  </message>
```

**Comment by robander** [comment]
While working on this I noticed this in the PDF messages file:
```xml
  <!-- DOTA067W and DOTA068W actually come from Java code inside the PDF plug-in.
       DOTA prefix is innacurate. No reason to change at this point. -->
  <message id="DOTA067W" type="WARN">
    <reason>Ignoring index-see '%1' inside parent index entry '%2' because the parent indexterm contains indexterm children.</reason>
    <response>According to the DITA Specification, the index-see element should be ignored if the parent indexterm contains other indexterm children.</response>
  </message>
...
```

That makes me a bit nervous, to knowingly reuse the message prefix, even if this does jump 60 digits ahead of existing numbers. I won't worry about that now, but may open an issue for 2.3 or 3.0 to try and change message numbers so that they're unique to a plugin, leaving no chance for overlap.

**Comment by robander** [comment]
It is no longer possible to reach this message, as preprocessing removes the empty href attribute:
```xml
  <message id="PDFX004F" type="FATAL">
    <reason>Empty href was specified for some topic reference.</reason>
    <response>Please correct your ditamap or bookmap file.</response>
  </message>
```
Another item for cleanup, perhaps with #2326

**Comment by robander** [comment]
I'm also uncertain how to trigger PDFX005F, but will clean up the text to something that reads better; this message should be cleaned up with #2326 as well.

Same with PDFX006E; this message is designed to appear when a table does not set `@cols`, but a topic with such a table will not parse, so that message cannot be reached. I will comment that out of the guide for now.

The following two messages no longer exist in the code, so I will remove them from the message list: 
```xml
  <message id="PDFX010W" type="WARN">
    <reason>Index generation is not supported in FOP.</reason>
    <response/>
  </message>
  <message id="PDFX012F" type="FATAL">
    <reason>Unrecognized PDF formatter '%1'.</reason>
    <response>Use "fop" for FOP, "xep" for RenderX XEP, or "ah" for AH Formatter.</response>
  </message>
```
