### ISSUE TITLE
1.3: Support additional style values for flagging

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#1781]
Proposal 13090

**Comment by robander** [comment]
@drmacro we discussed this a bit last week when you thought "line-through" had been added to flag values. I think I tracked down why it was not - instead of adding new values, the proposal ended up being a more general change to list style values as space-delimited NMTOKENS instead of providing an enumerated list. The 1.3 text says that processors SHOULD support values that existed in 1.2 but the attribute is now open for other values. (Took me a bit to track down the details, I found the final title for 13090 listed as part of our first big spec review log https://wiki.oasis-open.org/dita/DITA1.3SpecReview1 )

Given that this was a change to free-form style values, I'm not sure exactly that is needed by this feature request. I'm not sure if the existing code can handle space-delimited values, or if it still expects single values. If we want to support additional values beyond what 1.3 lists, we probably need to explicitly list them.

**Comment by drmacro** [comment]
I think it would make sense to build in support for line-through since it's now a value in the highlight domain (and I need it for the @status flagging) and then provide an extension point to make it easy to add support for additional values via plugin.
