### ISSUE TITLE
Link to ID defined on topicref does not work (but should it?)

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1817]
Let's say in my DITA Map I define an ID on a topicref like:

``` xml
<topicref href="tasks/gardenPreparation.dita" id="tid"/>
```

and then in one of my DITA topics I have a link like:

``` xml
<xref href="../flowers.ditamap#tid" format="ditamap">LINK TEXT</xref>
```

But the link is broken in both the XHTML and PDF outputs.
According to [Eliot Kimber](https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/36579) this should work.

**Comment by ColinMaudry** [comment]
Reading this thread, I conclude that an xref that points to the mappath#id of a `topichead` is supposed to result in a working cross reference, at least in paginated outputs such as PDF? Because my tests seem to show it doesn't work, with href (dead link) or keyref (no link whatsoever).

DITA topic:
```xml
<xref outputclass
= "fm:" keyref = "../Installation-guide.ditamap#id1617A0Z04M8">Standalone
Deployment</xref>
```
Installation-guide.ditamap:
```xml
<topichead navtitle="Standalone Deployment" keys="standalone" id="id1617A0Z04M8">
...



stage1a.xml:

```xml
<topic class="+ topic/topic pdf2-d/placeholder " id="d4e39">
      <title class="- topic/title ">Standalone Deployment</title>
      ...
```

```xml
<xref class="- topic/xref " href="#unique_4" ohref="Installation-guide.ditamap#id1617A0Z04M8" outputclass="fm:" xtrc="xref:1;17:71" xtrf="file:/.../c_deployments-modes_overview.dita"><?ditaot usertext?>Standalone Deployment</xref>
```

**Comment by drmacro** [comment]
Your xref is not good--the @keyref value is clearly a URI and therefore should be in an @href attribute, so that xref is not going to work regardless of its target.

The DITA spec is not 100% clear on what it means to address a topicref by ID--at least at one point there was some language suggesting that it took you to the navigation represented by the topicref, not the resource referenced, meaning you went to the ToC entry in the ToC, not the topic.

I can't find any language in the 1.3 spec that directly covers this case and don't have time at the moment for deeper research.

I would say that treating a direct URI link to a topicref as either a link to the navigation (where that's sensible for the deliverable being generated) or as a link to the resource referenced by the topicref are both reasonable behaviors and processors are free to use one or the other.

Robert can correct me but I think there was at least a time when IBM had delivery systems that used the "link to the navigation" behavior.

The @format attribute could also be used as a determiner of the intent: if you address a topicref by ID with a @format of "ditamap" it could be taken to mean "I'm linking to the topicref, not its resource" but if you use a @format of anything other than "ditamap" then it means "I'm linking to the resource addressed by the topicref". There are some examples of that in the 1.3 spec in the direct addressing section. http://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/archSpec/base/uri-based-addressing.html#uri-based-addressing

In the case where @format is not specified (meaning the default is "dita"), I would expect a direct reference to a topicref to be interpreted the same as a key reference, that is, you are addressing the resource addressed by the topicref, not the topicref itself.

**Comment by ColinMaudry** [comment]
Thanks @drmacro for the answer. The attribute was a typo, I had forgotten to reverse keyref to href in my example.

I'll see what happens with @format = "ditamap" with the DITA OT. If it doesn't work, I'll find a workaround. Probably creating a topic for each title-only modules, but that would be quite a burden for the writers.

**Comment by drmacro** [comment]
If the issue is that you have topicheads and want to link to them, then if you specify @chunk="to-content" it should produce a result as though there was a title-only topic. Put a key on the topichead and link to that.

See this section of the spec: http://docs.oasis-open.org/dita/dita/v1.3/os/part1-base/archSpec/base/chunkingdetails.html

Under "to-content:"

When specified on a <topicref> that contains a title but no target, this indicates that processors MUST generate a title-only topic in the rendered result, along with any topics referenced by child <topicref> elements of this <topicref>. The rendition address of the generated topic is determined as defined for the @copy-to attribute. If the @copy-to attribute is not specified and the <topicref> has no @id attribute, the address of the generated topic is not required to be predictable or consistent across rendition instances.

**Comment by ColinMaudry** [comment]
Thanks Elliot, but according to my tests, using @chunk="to-content" doesn't help.

No change actually, the results are the same as without the chunk attribute, whether I use a keyref or an href.

Is it a bug or it simply was never implemented? Shall I file an issue?

**Comment by ColinMaudry** [comment]
And when I add `format="ditamap"`, the resulting link, in the PDF, points to the .ditamap file, to the title within the PDF.

**Comment by drmacro** [comment]
If specifying @chunk="to-content" on a topichead and using a keyref to the topichead doesn't produce a working link in the PDF then I think that must be a bug since that's what the spec requires.

**Comment by drmacro** [comment]
I created a test case (https://github.com/dita-community/dita-test-cases/tree/master/topichead-linking) and the results I get with the 2.2.2 OT are that the HTML works mostly but the PDF is pretty broken.

In the HTML the ToC and generated child links are correct but the xrefs are not. That is, the required title-only topic behavior is used and is correctly reflected in the ToC but the xrefs to those topics do not reflect the navigation titles and do not point to the resulting HTML files.

In the PDF none of the links to topicheads work at all.

The 1.8.5 OT fails utterly to generate PDF and the HTML runs but reports errors trying to resolve the references to the topicheads.

So for PDF there is definitely a bug or bugs related to the handling of links to topicheads. The HTML seems to be (minimally) correct. The processor is free to treat references to topicheads that *don't* specify @chunk in the same way it treats topicheads without @chunk but it should produce *something* useful in that case, which it currently does not.

**Comment by ColinMaudry** [comment]
Thanks a lot for summarizing the issue. I will check with my client how they want to move forward from here.

**Comment by raducoravu** [comment]
Another one of our user's requested links to topicheads:

         I’d like to insert in a .dita file a cross reference to either a ‘navtitle’ or a ‘topic head’.

**Comment by drmacro** [comment]
IDs on topics are not guaranteed unique within context except the XML document containing the topic so they are not a general candidate for map-level navigation.

IDs on topicrefs are unique within the *map document* but not within the effective map so they are also not general candidates for map-level navigation. However, they are a more reasonable fallback in the absence of a key than the topic ID, which is absolutely unreliable (remember that I go out of my way to make the ID on every top-level topic "topicid" just to emphasize this point).

The only candidate for preservation as an ID in generated deliverables is the (scope-qualified) key names defined on topicrefs. But a topicref ID is a reasonable fallback if the topicref IDs are managed so that they are globally unique within the scope of the map tree.
