### ISSUE TITLE
Report reference to topic not included in map

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1852]
Whenever we have links to topics not included in the DITA Map, the result PDF output has broken links. Ideally the DITA OT would give a more specific warning when such situations are encountered. Right now only Apache FOP complains about this:

```
 [fop] 1232 WARN [ main ] org.apache.fop.apps.FOUserAgent - Page 3: Unresolved ID reference "unique_2" found.
```

but the error does not help much in determining the problem.

Based on this forum thread:

http://www.oxygenxml.com/forum/viewtopic.php?f=1&t=11262

**Comment by jelovirt** [comment]
Dead links should be reported during preprocessing already. In PDF conversions, we could just create `fo:inline` instead of `fo:basic-link` for dead links, this way the renderer doesn't need handle these error cases.

**Comment by mstanleyjones** [comment]
```Dead links should be reported during preprocessing already.```
I'm not sure what you mean by this. What does the report look like? I have not yet spotted anything. If you enable `onlytopic.in.map`, the topic that isn't in the map simply doesn't get built, but the link to it is still there (and dead) and I have not been able to detect any output message. I devised an extremely hacky solution of enabling `onlytopic.in.map` and then comparing the topicpull messages to the Writing messages, and seeing what's missing! Those are the orphans. This is awful, I know.

I had high hopes for DOT063W, but it seems to only be implemented for PDF2, and I am not sure how to hook it into a HTML5 transformation. I am not an XSL guru by any means.

(I'm replying because I asked Radu a question that triggered this bug report.)
