### ISSUE TITLE
Change site plugin name

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#1880]
The `net.sourceforge.dita-ot.html` plugin used to generate HTML output for the project website at http://www.dita-ot.org should be renamed to `org.dita-ot.html` _(or similar)_ to reflect the project website URL.

**Comment by jelovirt** [comment]
Wondering whether we should move the plugin into a separate repository, since it's not really part of core code and it's difficult to move it to docs or dita-ot.github.io repositories because plugin integration becomes hacky. If it were it's own plugin repo, it might serve as an easy start point for custom plugin for Jekyll site publishing.

**Comment by infotexture** [comment]
:+1: Good point. Could be re-included as submodule or installed & integrated via build script. 

Would be very useful to have it available separately so others can easily fork & customize.

**Comment by jelovirt** [comment]
I'll make it a separate repo. I don't think we should import the history to the new repo, because there's the old HTML site generation that we don't need and the plugin is never released for general use. Votes?

**Comment by infotexture** [comment]
:+1: Sounds good.

**Comment by robander** [comment]
:+1: Same, sounds good.

**Comment by jelovirt** [comment]
https://github.com/dita-ot/org.dita-ot.html is up, but it hasn't been integrated with dita-ot/dita-ot and dita-ot/docs yet. Will get to that later.
