### ISSUE TITLE
Key definitions do not resolve in a topic referenced by the copy-to attribute

### ISSUE THREAD

**Issue by grnygbns** [dita-ot/dita-ot#1901]
Topics inserted into a map for subsequent occurrences using the 
<topicref copy-to="c_topic_subsequent.xml" href="c_topic.xml"> 
attribute do not resolve key definitions contained in the copy-to 
topic c_topic_subsequent.html although the key space for the key definitions is properly specified.  
The key definitions in the copy-to topic output do not appear in either PDF or webhelp.
Please advise.

**Comment by raducoravu** [comment]
This is for DITA OT 1.8, right? Have you tested with DITA OT 2.0?

**Comment by drmacro** [comment]
I thought I reported this issue recently. The problem is that copy-to processing is applied before the key definitions are handled, so the copy-to processor doesn't know that the topicref indirects through a key (or rather, it couldn't resolve the key reference even if it wanted to).

The workaround is to define a separate key definition that specifies the copy-to and then refer to that key from the navigation topicref.

I don't think this is something that can or should be fixed until the preprocessing is completely re-thought to handle DITA 1.3 requirements.

**Comment by eerohele** [comment]
Sounds like a duplicate of #1861.
