### ISSUE TITLE
extension point dita.xsl.htmltoc useless or deprecated

### ISSUE THREAD

**Issue by gsejourne** [dita-ot/dita-ot#1934]
On version 2.0, trying to use the extension point `dita.xsl.htmltoc` is useless. For example:

``` xml
<plugin id="com.example.brandheader">
  <feature extension="dita.xsl.xhtml" file="xsl/header.xsl"/>
  <feature extension="dita.xsl.htmltoc" file="xsl/toc.xsl"/>
  <feature extension="dita.conductor.target.relative" file="conductor.xml"/>
</plugin>
```

will not work, for either "html5" or "xhtml" transtypes. However, using "dita.xsl.html.cover" instead works as expected. It would be good to mention in the docs that the `dita.xsl.htmltoc` seems deprecated.

**Comment by jelovirt** [comment]
The `dita.xsl.htmltoc` extension point as such isn't deprecated, but rather a separate TOC file is no longer generated. Instead, since DITA-OT 2.0 a cover page with a nested TOC is generated.

Not sure how to treat this, since the separate TOC stylesheet is still there and should work correctly with `dita.xsl.htmltoc`.

**Comment by 88ning** [comment]
I had a similar experience as gsjourne when trying this today on an XHTML plugin. 

<feature extension="dita.xsl.html.cover" file="xsl/toc.xsl"/>  replaces the index.html with the output of xsl/toc.xsl.

<feature extension="dita.xsl.htmltoc" file="xsl/toc.xsl"/> does not do anything to index.html, and I don't see any indication in the log or in the output that indicates that the extension point was triggered.
