### ISSUE TITLE
img/data-about element should not be rendered in XHTML output page

### ISSUE THREAD

**Issue by sorin-ristache** [dita-ot/dita-ot#1939]
For an image element like:

~~~~~
            <fig>
                <title>IMAGE TITLE</title>
                <image href="image.jpg"/>
                <data-about type="image" scope="local">
                    <data name="xoffset" value="1.000pt"/>
                    <data name="yoffset" value="1.000pt"/>
                </data-about>
            </fig>
~~~~~

the following text representation of data-about is added to the the HTML output page:

~~~~~
[/topic/body/p/fig/data-about {"- topic/data-about "}) (data-about]
~~~~~

To skip the data-about element the following XSLT template should be added to the file (both DITA-OT 1.8 and 2.0): 

DITA-OT-DIR/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl

~~~~~
<xsl:template match="*[contains(@class,' topic/data-about ')]"/>
~~~~~

**Comment by drmacro** [comment]
I agree that data-about should not be rendered, but note that the example is not a correct use of data-about. The data-about element is supposed to point to the element to which it applies. So to be completely correct it needs to address the image element, e.g.:

````
<image id="image-01" href="image.jpg"/>
                <data-about type="image" scope="local" href="#./image-01">
                    <data name="xoffset" value="1.000pt"/>
                    <data name="yoffset" value="1.000pt"/>
                </data-about>
````
Here using the DITA 1.3 "this topic" fragment identifier (otherwise you need to specify the ID of the topic that contains the image element.
