### ISSUE TITLE
Move same topic fragment processing before conref

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1968]
Move same topic fragment processing before conref processing to enable
```xml
<p conref="#./foo"/>
```
As reported in #1649

**Comment by drmacro** [comment]
But note that for xrefs, this-topic resolution is performed *after* conref resolution, meaning that "this topic" is the topic that contains the conref reference so that this-topic references within conreffed elements resolve in the context of the using topic, not the topic that contains the referenced elements. Not sure if this change affects that logic.
