### ISSUE TITLE
Defer reading images list to end of preprocessing

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#1988]
In the current preprocessing design, list of images is generated during gen-list target. However, this relies on listing image formats in a configuration file and not relying on `<image>` element references, since key defined images are not processes at that point. An alternative design would be to create a list of images during image-metadata target where image dimensions are read. This would allow getting an accurate list of images that doesn't rely on `@format` or file extensions.

**Comment by jelovirt** [comment]
No image list is generated, the images are copied based on job configuration list directly. Copying still doesn't happen at the end of preprocessing. A better approach could be that each transtype handles the copying.

**Comment by drmacro** [comment]
The DITA Community map-driven processing use a final-phase process for generating an Ant script that then does the copying. This process operates on the images in the content and also provides an extension point so that you can add anything else you want to the copying process. This approach might be a useful model. 

I took the approach of generating an Ant script because that seemed like the simplest solution that didn't require custom Java code to do the copying.

**Comment by shaneataylor** [comment]
I'm seeing that images that are the target of a key definition (`<keydef keys="mykey" href="image"/>`) are not copied to the output, even if they are referenced elsewhere by an `<image href="image">`. Is this an expected result of the current behavior?

**Comment by jelovirt** [comment]
@shaneataylor you have to use `format="image"` on the key. This will be partially fixed when this feature is implemented.

In any case you should not claim `mykey` in your example is a DITA topic (omitting `@format` means target is a DITA topic), you should use e.g. `format="image"` or `format="png"`.

**Comment by shaneataylor** [comment]
These were actually external MathML, with `format="mml"` set in the key definition and customization to pull them into the generated HTML. I was able to work around the problem by removing the keydefs altogether as the reason I needed them no longer exists.
