### ISSUE TITLE
Branch filters and internal links [DOT 2.x develop branch]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#1999]
On the samples here:

http://www.oxygenxml.com/forum/files/branchFiltering2.zip

The "index.dita" has an xref like:

```
   <xref href="someOtherTopic.dita#topic_rl4_rc2_ys"/>
```

When the second branch is created, there is an "index-1.html" which has a reference to "someOtherTopic.html" instead of "someOtherTopic-1.html" so that the references would be self-contained on one branch.
Related links seems to work fine though.

**Comment by jelovirt** [comment]
Others may disagree, but this isn't a bug since DITA 1.3 doesn't mandate that links in branch filtering branches need to rewritten to point to duplicated targets in that same branch. To me, this is similar to a feature that links should point to the "closest" occurrence of a duplicated topic.

This could be left as an improvement feature for future.

**Comment by raducoravu** [comment]
Ok, I do not have a precise need for this right now. It's good to know the limitations though.
What I was trying to do was to take our user's manual's main DITA Map and refer it in a "main.ditamap" with two or more ditavalref's in order to create a table of contents which contains in it merged both the Oxygen XML Editor and Oxygen XML Author user's manuals. I'm not sure if end users will have similar cases in which they plan to use branch filtering.

**Comment by drmacro** [comment]
You should not be using direct URI references for any links. There is no way for a processor to know, for an arbitrary URI reference, what the appropriate rewriting would be. With keys the map owner has control, but direct URI references are uncontrollable. So Jarno is correct--not a bug.

Having said that, a processor could be smart enough to take a stab at rewriting direct URIs so they "make sense" in the face of the effective copy-tos produced by branch filtering. But anything it did would only be the correct answer for some, but not all, users.

**Comment by fjssbarney** [comment]
After talking with the oXygen folk at the LavaCon conference, it appears that I am being challenged by this issue.
We are trying to create a library of manuals, so that we can link between our manuals. For these links, I was planning to only allow the use of reltables.
WIthin this library of manuals, two use many of the same topics. These topics are using conditional processing to include or exclude content. So while they both use "topicA.dita", the two output versions of what would become "topicA.html" differ in content. At this point, I understand that I need two differentiated file names.
All the links that I provide (either within the topic, which I understand is not pure DITA, or via reltables) end up redirecting to the first instance of "topicA.html". For the second manual, this link ends up being wrong - it takes it to the topic where the conditional content is no longer valid.
I have tried using the "copy-to" but without successful results. The links then appear as broken, as the copy-to creates a valid HTML file name, but none of the links know to re-name themselves to point to this file.
You imply that the reltables can be a solution here? Can you instruct me - how can I specify that the reltable point to the name of a file that will eventually be created after the transform?

It is critical to me that I be able to link from one manual to another (from our GUI-interface manual to our deeply-technical specifications manual), and I thought that creating a library that comprised of my manuals would be the solution. But as we have topic re-use, I now have too many output files being created with number extensions, thus breaking any and all of my linking strategies.

**Comment by raducoravu** [comment]
Hi Scott,

From what I understood on this thread, once you start using ditavalref and you want links between topics to properly point either to a topic in the same publication or to a topic in another publication, you will also be bound to use key references and key scopes in order to properly differentiate targets.
I'm attaching a sample project I made to exemplify this:
[ditavalRefWithLinking.zip](https://github.com/dita-ot/dita-ot/files/2537621/ditavalRefWithLinking.zip)
In the "topic2.dita" there are two xrefs, one points to the "topic1.dita" from the first publication and it does this by using the "novice" keyscope which I defined on the first reference to the "publication.ditamap" followed by the "firstTopic" key name which I have set on the topic reference to the "topic1.dita". The second xref points to the "topic1.dita" from the current publication, as it does not use the keyscope in the keyref value.
I also used the "dvrResourceSuffix" in the ditavalref to take a little bit of control over how each topic will be named in the published output.

My sample project seems to work with DITA OT 3.1.3, the links text and targets seem to be properly computed.

Regards,
Radu

**Comment by fjssbarney** [comment]
Thanks for this example! 

It helped me to solve the issues I was having with the “copy-to” attribute; using the “dvrResourceSuffix” element provided the proper file re-naming without breaking my branch filtering.

It also helped  me to solve my linking issues when two manuals shared the same map in a branch filtering, through the use of keys and keyrefs.

 

For my last step, I need to figure out how to reference these files in my reltables.

 

For example, in the ZIP file included, I want to use reltables to:

*	LINK between Topic A and Topic C within a manual
*	LINK from Topic B (either PROD or JPROD manual) to RandoA

 

As you can see in the attached sample, the reltable entries I have are completely ignored, given that the DITA files mentioned do not exist.

I tried using keys: 

<topicref keyref="topicA"/>


But to no avail.

 

Scott

**Comment by raducoravu** [comment]
@fjssbarney I agree, reltables with keyscopes and branch filtering do not work at all, from what it seems the related links are added in the original topic file names and not in the topic files which have been generated by keyscoping and branch filtering.
I added at some point in the past a separate issue for this: https://github.com/dita-ot/dita-ot/issues/2147

**Comment by raducoravu** [comment]
I agree that when it comes to using branch filtering in order for links to properly resolve you need to use keyrefs and key scopes.
