### ISSUE TITLE
Key reference resolution should be done in key scope context [DOT 2.x develop branch]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2021]
I uploaded a sample DITA Map here:

http://www.oxygenxml.com/forum/files/testKeyScopeAndExternal.zip

It's contents are quite small:

    <map>
     <title>DITA Topic Map</title>
     <topicgroup keyscope="KS">
      <topicref href="inner.dita"/>
      <topicref href="inner2.dita" keys="TARGET"/>
     </topicgroup>
     <topicref href="outer.dita" keys="TARGET"/>
    </map>

The "inner.dita" has an xref keyref like:

      <xref keyref="TARGET"/>

Should the keyref be resolved:
1) To the inner2.dita
or
2) To the outer.dita
?

Right now (2) is done, I would consider (1) as the correct behavior but I'm not 100% sure.

**Comment by drmacro** [comment]
This is a subtle case, but  (2) is the correct result. Keys are resolved in the context of the *highest* ancestor key scope in which the key name is declared. Because the root scope declares the key "TARGET", that declaration overrides any declaration in descendant scopes. So the unqualified key reference in inner.dita must resolve to outer.dita.

Note that the order of declaration doesn't matter in this case.

This is analogous to key in a higher map overriding the same key defined in any descendant map, regardless of where in the higher map the key definition occurs relative to the map references.

It is this behavior that makes it clear that key scopes are not the same as variable scopes as in most programming languages.

The implication of this rule is that higher maps should avoid declaring any keys unless they absolutely have to in order to make the documents correct, otherwise they run the risk of creating just this situation.

It also makes it clear that coordination of key definitions among maps is essential.

**Comment by raducoravu** [comment]
I understand and I think I agree now that you twisted the entire thing around :)

**Comment by robander** [comment]
If it helps, there's a sample of this case here:
http://docs.oasis-open.org/dita/dita/v1.3/csprd01/part1-base/archSpec/base/example-nested-key-scopes.html

In the sample, `<keydef keys="a">` appears in the root scope, and in scope "B". The tables below the graphic show that from any scope in this map, a reference to "a" will resolve to the one in the root scope. [Note: based on a comment on this version of the topic in the public review, the updated topic will have unique `@href` values along with the key values to help clarify how each key resolves.]

**Comment by raducoravu** [comment]
That settles it, thanks Robert and Eliot, I will close this issue.
