### ISSUE TITLE
Missing reltable links with DITA 1.3 schemas

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#2102]
Docs output generated with recent builds of the OT `develop` branch no longer include related links from reltable entries. Links derived from `<related-links>` elements in topics are generated correctly.

A bit of sleuthing with `git bisect` suggests the regression may have been introduced with a71c54f, which adds the DITA 1.3 schemas.

**Comment by infotexture** [comment]
For example: 

* The link to the Apache license under [DITA Open Toolkit Overview](http://www.dita-ot.org/2.1/user-guide/overview-of-dita-ot.html) is created by [reltable.ditamap#L229](https://github.com/dita-ot/docs/blob/develop/reltable.ditamap#L229) and missing in recent builds.
* The `<related-links>` under [Reducing processing time](http://www.dita-ot.org/2.1/user-guide/reducing-processing-time.html) ([Line 50](https://github.com/dita-ot/docs/blob/develop/user-guide/reducing-processing-time.dita#L50)) are generated correctly.

**Comment by jelovirt** [comment]
Seems that DITA 1.3 changed the `processing-role` default value to be `resource-only` on `<reltable>`. That is the probable cause for this.

**Comment by raducoravu** [comment]
The relcell also has in the DITA 1.3 DTDs a default resource-only value for the processing-role. And this also influences the current issue.

**Comment by raducoravu** [comment]
It looks also like a problem with the DITA 1.3 specs not being 100% compatible with the DITA 1.2 specs.
In the DITA 1.2 specs the processing-role attribute used on reltable points to this:

http://docs.oasis-open.org/dita/v1.2/os/spec/common/topicref-atts.html

which describes its default value as being normal.

**Comment by jelovirt** [comment]
@robander @keberlein can you comment on the TC rational for changing the default value? Is the DITA 1.3 spec intent that links are generated even for resource-only relations in reltable?

**Comment by raducoravu** [comment]
The DITA 1.3 specs seems indeed to specify resource-only as being the default value for processing role for reltable:

https://www.oxygenxml.com/dita/1.3/specs/index.html#langRef/base/reltable.html

For relcell it would seem to indicate that it has a normal processing role:

https://www.oxygenxml.com/dita/1.3/specs/index.html#langRef/base/relcell.html

but the DTDs say otherwise.

**Comment by keberlein** [comment]
I think this is a bug. Can one of you send an e-mail to the
    dita-comment list? That is the official mechanism for non-DITA TC
    members to comment on the spec and the grammar files.
    
    Best,
      Kris
      
      Kristen James Eberlein
      Chair, OASIS DITA Technical Committee
      Principal consultant, Eberlein Consulting
      www.eberleinconsulting.com
      +1 919 682-2290; kriseberlein (skype)
      
    
    On 10/19/2015 2:56 AM, Radu Coravu
      wrote:
    
    
      The DITA 1.3 specs seems indeed to specify resource-only as
        being the default value for processing role for reltable:
      https://www.oxygenxml.com/dita/1.3/specs/index.html#langRef/base/reltable.html
      For relcell it would seem to indicate that it has a normal
        processing role:
      https://www.oxygenxml.com/dita/1.3/specs/index.html#langRef/base/relcell.html
      but the DTDs say otherwise.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by drmacro** [comment]
Looking at the 1.3 mapMod.rng, it looks like this might be a side effect of removing @keyscope from reltable, which was a relatively late change. The group topicref-atts-no-toc-no-keyscope sets the default for processing-role to "resource-only", which was a change made for 1.3 in the topicref-atts-no-toc group. It looks like that group was then copied to make the new topicref-atts-no-toc-no-keyscope group, which is of course new for 1.3. I'm sure I didn't consider the implications of the default value for processing-role when I did that.

I agree that this is probably not the appropriate default for reltable. 

We'll need to get some input from Robert on this to make sure we know the history.

**Comment by infotexture** [comment]
I can confirm that related links **are** generated when `@processing-role="normal"` is explicitly added to a `<relcell>` and its parent `<reltable>`, so that does indeed seem to be the problem.

**Comment by robander** [comment]
This was an intentional change, but I don't think the impact on linking was considered or expected. The idea was that the TOC / Print aspects of "resource-only" should apply to reltable, and that resource-only should be specified in order to keep items in the reltable from somehow showing up in the TOC, showing up as a jumble of printed topics in a PDF, or generating their own output topics if not otherwise rendered in the main section of the map. I couldn't find it searching the OASIS site, which may not be going into our meeting minutes, but I can find it on the (private to TC) trello board that tracked code fixes: https://trello.com/c/IossC3qR/10-10-set-processing-role-resource-only-as-default-for-reltable

**Comment by robander** [comment]
Ah, I found the record, going back to July 26 2011, but little of the discussion was recorded (I am sure the linking aspect didn't come up or there would have been more to this): https://lists.oasis-open.org/archives/dita/201107/msg00029.html

**Comment by robander** [comment]
To go back to @jelovirt 's question about intent -- in case it's not clear from what's above, I'm certain that the intent of this was to keep from having topics show up randomly at some point in a publication just because they were part of a reltable. They did so one point early on for PDF2 (or maybe it was legacypdf), and could do for other similar formats that don't explicitly set the conversion up to not print reltable topics at the location of the reltable. I'm also 100% certain that the intent was *not* to turn off linking for anything in the reltable.

**Comment by raducoravu** [comment]
A similar problem is with the relcolspec element, again it has processing-role="resource-only" on it so if the reltable is something like this:

    <reltable>
        <relheader>
            <relcolspec type="topic">
                <title>Data</title>
            </relcolspec>
            <relcolspec type="topic">
                <title>Format</title>
            </relcolspec>
        </relheader>
        <relrow>
            <relcell>
                <topicref href="test.dita"/>
            </relcell>
            <relcell>
                <topicref href="secondtest.dita"/>
            </relcell>
        </relrow>
        <relrow>
            <relcell/>
            <relcell/>
        </relrow>
    </reltable>

the related links will still not get displayed even if the DTD is modified to remove resource-only processing-role for table and cell.

**Comment by drmacro** [comment]
I think part of the challenge here is that processing-role isn't really meaningful in the context of relationship tables.

That is, relationship tables simply serve to associate topics to each other *for any purpose*. The presentation result of those associations, if any, is entirely processor dependent. There is no requirement in the DITA spec that topics linked by relationship tables be presented in any way or that reltable links produce any particular presentation result.

From that standpoint, the default of resource-only is more appropriate because it emphasizes that, as far at the DITA spec is concerned, the associated resources are simply associated together with no presentation implications.

In particular, including a topic in a relationship table does not inherently imply that that topic be presented anywhere. 

The effect of generating related links in rendered topics is simply one possible presentation result of related links, one provided by the OT. The value of the processing-role attribute is pretty much irrelevant--the OT is free to treat the links in any way, including generating HTML files for topics that are not otherwise included in the navigation tree for HTML output or reporting an error when generating PDF and there's a reltable link to a topic not included in the navigation tree. 

Processors could use the @processing-role setting as a clue as to how to handle the case where topics not included in the navigation tree are linked by relationship tables but I don't see that value implies any particular behavior one way or the other, because the semantics of relationship table links are entirely in the domain of processors and authors.

**Comment by drmacro** [comment]
The implications of my foregoing comment are that the OT is free do whatever it wants with relationship tables irrespective of the value of the @processing-role attribute. Therefore it can continue to behave as though normal were the default since the value doesn't actually matter.

**Comment by raducoravu** [comment]
I agree that the default value for the processing role set on reltable elements should have probably been resource-only from the initial DITA 1.0 standard.
I do not quite agree with the fact that DITA 1.3 breaks compatibility with 1.2 and older DITA standards in doing this. Because the DITA standard has been great in the way in which it keeps adding stuff and remains backward compatible with the older DITA standard versions.
So if you want to have reltables used in the output you cannot use the DITA 1.3 schemes both with the latest DITA OT 2.x and with older DITA OTs as well. And possibly other processors will have the same issue.

**Comment by robander** [comment]
Based on discussion at today's OASIS call, we'll be removing the default, so `@processing-role` will have the same defaults for all `reltable` elements as in DITA 1.2. So, we will need to update the grammar files we're shipping to match the changes @drmacro will be making in the official OASIS ones (guessing in the next couple days).

**Comment by drmacro** [comment]
My initial analysis is that simply removing the default value from the topicref-atts-no-toc-no-keyscope corrects the issue and does not affect any other element types defined in the DITA 1.3

**Comment by jelovirt** [comment]
While the DITA 1.3 grammar files will be modified to match the `processing-role` default from DITA 1.2, I think we still should take the discussion and ideas this raised and make relationship tables to collect links, regardless of the `processing-role` value. I have a feature branch for this and thus far it seems at least the integration tests still pass.

**Comment by drmacro** [comment]
I have updated the 1.3 grammars to remove the default on @processing-role for reltable, relcolspec, and relcell. I've committed those changes to the TC SVN repo. I tested the DTD, RNG, and XSD grammars.

**Comment by infotexture** [comment]
The missing reltable links are restored when docs are built with the updated DITA 1.3 DTDs from 4d2e858.

**Comment by raducoravu** [comment]
Great, the fix works for me. Just to double check, the XML Schema did not seem to specify a default for the attribute, right?

**Comment by jelovirt** [comment]
@raducoravu Yes, that's what it looked like. When TC updates the actual grammar ZIP, will verify our copies match theirs.

**Comment by keberlein** [comment]
Guys, if it would help, I can build a new package sooner rather than later.

Kris

**Comment by jelovirt** [comment]
@keberlein If you can build them in a week or so, that would be enough for 2.2 release.

**Comment by drmacro** [comment]
Yes, I noticed that the XSD did not specify a default. I'll check the XSDs to make sure that all defaults are being set in the XSDs--there aren't that many defaults in the DITA grammars so it's an easy thing to overlook when verifying the XSDs. I will do that immediately this morning.

**Comment by drmacro** [comment]
Fixes for the 1.3 XSDs have been committed to the TC SVN repo.
