### ISSUE TITLE
Using of 'dita.specialization.catalog.relative' extension point does not override native DITA-OT XML catalogs.

### ISSUE THREAD

**Issue by ibarinova** [dita-ot/dita-ot#2113]
Using of 'dita.specialization.catalog.relative' extension point does not override native DITA-OT catalogs.
It adds references to new catalogs below references to native DITA-OT catalogs. For example:

    <nextCatalog catalog="plugins/org.dita.specialization.dita11/catalog.xml"/>
    <nextCatalog catalog="plugins/org.oasis-open.dita.v1_2/catalog.xml"/>
    <nextCatalog catalog="plugins/com.custom.plugin/catalog.xml"/>
    <nextCatalog catalog="plugins/org.dita.specialization.eclipsemap/catalog.xml"/>

In this situation DITA-OT ignores customization in custom catalog (such as adding new attributes or custom elements). If references to the native DITA-OT catalogs are removed all work as expected and customized DITA files could be correctly resolved.

Was reproduced using DITA-OT 2.1; extending xhtml/html5 plugin; OS Windows 10.

Proposed solution: Add references to 'org.dita.specialization.dita11' and 'org.oasis-open.dita.v1_2' catalogs after custom catalogs.

**Comment by jelovirt** [comment]
Exactly what are you trying to override?

**Comment by ibarinova** [comment]
Hi,

I'm trying to add new attributes (for example @attr1 to <shortdesc> element).

I have a copy of native DITA-OT DTDs in my plugin (Yep, it is not a best idea, but I have such requirements). I've customized commonElements.mod and added new @attr1 to shortdesc definition.
Also I've added catalog.xml and 'dita.specialization.catalog.relative' extension point.
DITA-OT adds reference to my catalog into catalog-dita.xml. But resolver still uses native DITA-OT declarations and following error is displayed in log:
[gen-list] [DOTJ013E][ERROR] Failed to parse the referenced file 'file:/path/to/file.xml'.: file:/path/to/file.xml Line 3:Attribute "attr1" must be declared for element type "shortdesc".

**Comment by jelovirt** [comment]
DITA-OT deliberately gives the OASIS DTD's the highest priority in order to make sure people don't try to override the OASIS DTDs in a way that isn't intended by the DITA specialization system. You need to create a shell DTD that adds the custom attributes as a attribute specialization and then use the shell's public ID to use it.

If you want to override the OASIS provided shells and modules, you have to manually change the order in the catalog file.

@drmacro can probably give you a more verbose answer.

**Comment by drmacro** [comment]
If you need to add attributes to specific elements, my recommendation is to implement it as a constraint module using the normal constraint module coding rules.

Adding attributes to individual elements is not allowed but if you need to do, constraint modules are the closest thing DITA does provide. If you need to, you can rationalize it as "I defined a global attribute and then constrained it away from all but one element type".

In any case, by making it a constraint module you can most easily remove it if you need to restore things to a conforming state.

There should NEVER be a reason to directly modify the OASIS-supplied declarations, or the declarations of any other third party. DITA provides ample mechanisms for overriding anything.

If you are modifying the OASIS-supplied declarations because you can't use local document type shells then the tool you're using is broken and needs to be fixed. At a minimum, if you need to modify anything OASIS-provided, it should be the shells and not the base declaration modules.
