### ISSUE TITLE
db2dita plugin doesn't support segmentedlist

### ISSUE THREAD

**Issue by oreganmurphy** [dita-ot/dita-ot#2138]
`docbook2dita/dbdita/ditaWriter/topicOutput.xsl` have no writer code for `topic.segmentedlist.out`

A simple hack is below but it only dumps out the content (incl. child nodes) as a lump of text.
Any fix/upgrade should also iterate through all child nodes and process accordingly.

```xml
  <xsl:template match="*" mode="topic.segmentedlist.in">
    <!-- <p> -->
      <!-- drive the list by outputting each segtitle in turn -->
      <xsl:for-each select="segtitle">
        <p>
        <b>
          <xsl:value-of select="."/>
        </b>
        <xsl:text>: </xsl:text>
        <!-- record the current position in the list (1,2,3...) -->
        <xsl:variable name="thispos" select="position()"/>
        <!-- output the relevant item from the seglistitem child
             of the parent element (segmentedlist) -->
        <xsl:value-of select="../seglistitem/seg
                              [position()=$thispos]"/>
        <!-- add a linebreak to all except the last -->
	<!-- <xsl:if test="position()!=last()">-->
	  </p>
	<!--   <lines/> -->
       <!--  </xsl:if>-->
      </xsl:for-each>
   <!--  </p> -->
  </xsl:template>
```

**Comment by robander** [comment]
I don't think this issue is related to any code maintained by DITA-OT. It appears this is related to the following file in another github project that is not maintained by this team:
https://github.com/jmourelos/doconv/blob/master/doconv/plugin/docbooktodita/ditaWriter/topicOutput.xsl

If so, then the issue should be opened against that project: https://github.com/jmourelos/doconv/issues
