### ISSUE TITLE
Fix headers of 'org.oasis-open.dita.v1_3'

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2142]
Headers of the doctypes `org.oasis-open.dita.v1_3` mention the version `1.2`.

```
 MODULE:    DITA Abbreviated Form Domain                     
 VERSION:   1.2                                              
 DATE:      November 2009
```

**Comment by robander** [comment]
I'm guessing this may be because the module did not change between 1.2 and 1.3, so the file is the same. (Well, the file is now generated, but no change was made to the markup). Either way, I don't think we want to change this, as we are trying to use the exact copies delivered by OASIS -- it will be up to the OASIS TC to decide whether the header is worth updating in an errata edition.
