### ISSUE TITLE
Use URN in href to reference stylesheets and modules in 'org.oasis-open.dita.v1_3'

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2143]
The shells use URNs, but the URNs are not used in the `<include>` elements.

**moduleMetadata** in [concept.rng](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.oasis-open.dita.v1_3/rng/technicalContent/rng/concept.rng)
```xml
<moduleMetadata>
  <moduleType>topicshell</moduleType>
  <moduleShortName>concept</moduleShortName>
  <shellPublicIds>
	<dtdShell>-//OASIS//DTD DITA<var presep=" " name="ditaver"/> Concept//EN</dtdShell>
	<rncShell>urn:oasis:names:tc:dita:rnc:concept.rnc<var presep=":" name="ditaver"/></rncShell>
	<rngShell>urn:oasis:names:tc:dita:rng:concept.rng<var presep=":" name="ditaver"/></rngShell>
	<xsdShell>urn:oasis:names:tc:dita:xsd:concept.xsd<var presep=":" name="ditaver"/></xsdShell>
  </shellPublicIds>
</moduleMetadata>
```

**MODULE INCLUSIONS** in [concept.rng](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.oasis-open.dita.v1_3/rng/technicalContent/rng/concept.rng)
```xml
<div>
<a:documentation>MODULE INCLUSIONS</a:documentation>
<include href="../../base/rng/topicMod.rng"/>
<include href="conceptMod.rng">
  <define name="concept-info-types">
	<ref name="concept.element"/>
  </define>
</include>
<include href="abbreviateDomain.rng"/>
<include href="../../base/rng/deliveryTargetAttDomain.rng" dita:since="1.3"/>
<include href="equationDomain.rng" dita:since="1.3"/>
<include href="../../base/rng/hazardstatementDomain.rng"/>
<include href="../../base/rng/highlightDomain.rng"/>
<include href="../../base/rng/indexingDomain.rng"/>
<include href="markupDomain.rng" dita:since="1.3"/>
<include href="mathmlDomain.rng" dita:since="1.3"/>
<include href="programmingDomain.rng"/>
<include href="releaseManagementDomain.rng" dita:since="1.3"/>
<include href="softwareDomain.rng"/>
<include href="svgDomain.rng" dita:since="1.3"/>
<include href="uiDomain.rng"/>
<include href="../../base/rng/utilitiesDomain.rng"/>
<include href="xmlDomain.rng"/>
</div>
```

Eliot includes modules by URN, this is probably more reliable than including by a relative path.

**MODULE INCLUSIONS** in ** [chapter.rng](https://github.com/dita4publishers/org.dita4publishers.doctypes/blob/master/doctypes/chapter/rng/chapter.rng)
```xml
<include href="urn:dita-ng:dita:rng:topic.mod.rng"/>
<include href="chapter.mod.rng"/>
<include href="urn:dita-ng:dita:rng:highlightDomain.mod.rng"/>
<include href="urn:dita-ng:dita:rng:indexingDomain.mod.rng"/>
<include href="urn:dita-ng:dita:rng:utilitiesDomain.mod.rng"/>
<include href="urn:dita-ng:dita:rng:hazardstatementDomain.mod.rng"/>
```

**Comment by robander** [comment]
Eliot @drmacro  created the DITA 1.3 RNG files for OASIS -- he may be able to comment on the reason for using relative paths. Either way, as with #2142 I don't think we want to modify these ourselves. Changing the files delivered by OASIS is generally frowned upon, so I'd rather not do so unless something is really broken (and even then, only if we know that OASIS is planning to make the same change in an errata).

**Comment by drmacro** [comment]
Because this is the way the DTDs work and the RNG mirrors the DTDs as they were defined through DITA 1.2.

It would be possible to generate a set of RNG files that use URNs instead of system IDs but it was never suggested during the 1.3 process. Once 1.3 is official we can decide if doing so would be useful--but for now will leave things as they are for the reasons Robert gave.

**Comment by nakohdo** [comment]
JFTR
Using URNs at least for the \<include>s would at least make for cleaner customization because you only have to copy the files to your customization plugin you actually modify. The rest will be correctly resolved via the catalog files. That's why my colleague Marion Knebel and I recommended this procedure in our tutorial at this year's tcworld conference (http://conferences.tekom.de/conference/tcworld15/conference-program/conference-program/program/sv_1080_IN52/).
