### ISSUE TITLE
dita.xsl.strings Not Working

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2146]
I have a plugin that among other things, uses the dita.xsl.strings extension point to override generated text for some note types, next/previous labels, etc.

In 2.0, this worked fine. In 2.2, my strings are being ignored. I've made some other changes to the plugin (it's now based off of the new HTML5 transform rather than XHTML), but nothing that should affect the string overrides. I've already tried:
- varying the capitalization of the language code (en-us to en-US)
- specifying xml:lang on a DITA topic in addition to the map

I've searched the DITA-OT commit log somewhat, but I don't see a change that jumps out at me to explain why this is no longer working. Can anyone else repro this behavior to confirm it's an OT issue? Thanks!

**Comment by eerohele** [comment]
I can reproduce the issue with [this Gist](https://gist.github.com/eerohele/66da498432d248903022).

The issue was introduced in ffa63df38c7021adb752899d87ad91fa1102f5ff: after that commit, when DITA-OT generates `xsl/common/strings.xml`, it puts user strings *before* the strings defined in `org.dita.base`. Therefore any overrides you make don't work, but completely new strings should work.

A workaround is to add `<require plugin="org.dita.base"/>` into your `plugin.xml`. The real fix is probably to fiddle with the `plugin.order` property in `lib/configuration.properties`, but since I'm not sure how it works exactly, I can't propose an exact fix.

**Comment by eerohele** [comment]
Slightly OT, but the `otrelease` and `otversion` properties in `configuration.properties` are out of date.

**Comment by xephon2** [comment]
@eerohele , could you please add the `xhtml` label?
