### ISSUE TITLE
glossentry references are not rendered correctly

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2173]
I receive the following error with a simple test scenario:

```
[DOTJ047I] Unable to find key definition for key reference "G_Term" in root scope.
```

_test scenario_:
[Glossary-Test 002.zip](https://github.com/dita-ot/dita-ot/files/67624/Glossary-Test.002.zip)

The glossary entry does not appear in the PDF output. I have tested this using the DITA-OT 2.2.1.

![2015-12-19 23_58_24-glossary pdf - adobe acrobat reader dc](https://cloud.githubusercontent.com/assets/3266567/11915572/827440ca-a6ac-11e5-89c1-42e9968871a6.png)

## Possible Solution

Suggested by @drmacro in duplicating issue #2788:

> Remove the check in "topic.term" template that gets the matching acronym. That behavior should be applied to abbreviated-form.

**Comment by eerohele** [comment]
Hmm. Has this ever worked? I tried 1.5.4, 1.7.5, 1.8.5, 2.0.1, and 2.2.1 and it didn't work on any of them.

**Comment by jelovirt** [comment]
Ok, so not a bug, it's missing functionality.

**Comment by eerohele** [comment]
In fact, this is a duplicate of #1721.

**Comment by eerohele** [comment]
(The workaround is to add `@print="yes"` to the `<glossref>` element.)

**Comment by jelovirt** [comment]
Ah, that one. A feature of DITA that is by no means obvious.

**Comment by xephon2** [comment]
Well, `print="no"` is a strange default here. Could anyone who is working on the OASIS deliverables force that `print="yes"` is becoming the default value? Otherwise it would be interesting to read a motivation in the specs, why `print="no"` is the default.
So, I assume that nobody realized that the default also affects the rendering of [abbreviated-form](http://docs.oasis-open.org/dita/v1.2/os/spec/langref/abbreviated-form.html) and [term](http://docs.oasis-open.org/dita/v1.2/os/spec/langref/term.html#term). I think that the intention was, that a glossary should not be printed, which might make sense. But it does not make sense to have gaps in the text.
So please, if you do not want any text to appear here, please throw at least a message that informs the publisher, why that happens. This would not break anything but would reduce a little confusion here.

**Comment by xephon2** [comment]
But anyway, there is a bug here. This is the code of the `<concept>`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
<concept id="C_Concept">
 <title>Concept</title>
 <shortdesc>Concept with a term.</shortdesc>
 <conbody>
  <ul>
   <li><codeph>term</codeph> (empty) with <codeph>keyref</codeph> attribute: <term keyref="G_Term"/></li>
   <li><codeph>term</codeph> (filled) with <codeph>keyref</codeph> attribute: <term keyref="G_Term">term</term></li>
   <li><codeph>abbreviated-form</codeph>: <abbreviated-form keyref="G_Term"/></li>
  </ul>
 </conbody>
</concept>
```

This is the code of the `<glossentry>`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE glossentry PUBLIC "-//OASIS//DTD DITA Glossary//EN" "glossary.dtd">
<glossentry id="G_Term">
    <glossterm>term</glossterm>
    <glossdef>definiton</glossdef>
    <glossBody>
        <glossAlt>
            <glossAbbreviation>abbreviation</glossAbbreviation>
        </glossAlt>
        <glossAlt>
            <glossAcronym>acronym</glossAcronym>
        </glossAlt>
    </glossBody>
</glossentry>
```

And this is the rendered PDF result (`print="yes"` is set):

![bildschirmfoto_2015-12-21_16-43-52](https://cloud.githubusercontent.com/assets/3266567/11934366/0ad903d2-a802-11e5-9512-ac9eb1a11027.png)

`<abbreviated-form>` shows the text `term`, but it should display `acronym`. This intended behavior is also very strange. The [specs say](http://docs.oasis-open.org/dita/v1.2/os/spec/langref/abbreviated-form.html), that `<abbreviated-form>` displays the value of `<glossAcronym>` *not* of `<glossAbbreviation>` and BTW an `<acronym-form>` element would be nice.

Fortunately the XHTML processing is logically, but it does not comply to the specs. This is the rendered result:

![xhtml](https://cloud.githubusercontent.com/assets/3266567/11934547/43f88984-a803-11e5-8f66-3b648b04e09f.png)

The specs say, that `<abbreviated-form>` displays the value of `<glossAcronym>` *not* of `<glossAbbreviation>`, but in this case, `<glossAbbreviation>` is displayed.

**Comment by xephon2** [comment]
So please, reopen this. I change the title from `Processing glossentry elements throws [DOTJ047I]` to `glossentry references are not rendered correctly`, because the subject has changed.

**Comment by eerohele** [comment]
I haven't looked at the code yet so I'm not sure, but I would imagine that it doesn't handle the distinction between what the spec calls "introductory" and "non-introductory" contexts (which basically mean first use and subsequent uses, I guess), either, so that should probably also be implemented.

Also, if I remember correctly, there's quite a bit of code duplication between transtypes when it comes to the processing of `<abbreviated-form>` and `<term>` elements. Might be better to move some of the code into preprocessing or into common library code.

**Comment by xephon2** [comment]
This is probably quite easy to fix. How about adding a milestone tag?

**Comment by eerohele** [comment]
Having taken a proper look at the issue and the code, isn't the case actually that the PDF output is per spec?

The `<abbreviated-form>` element in your example is the first (introductory) use of the abbreviated form, therefore:

>1. In an introductory context, processors SHOULD render the surface form of the term by displaying the contents of the glossSurfaceForm element from the referenced glossentry topic.
>2. If the glossentry topic does not contain a glossSurfaceForm element or the glossSurfaceForm element is empty, processors SHOULD render the contents of the glossterm element in introductory contexts.

In other words, first use → `<glossterm>`, since `<glossSurfaceForm>` doesn't exist, which how DITA-OT currently behaves.

The second use displays the value of `<glossAcronym>`:

<img width="683" alt="screen shot 2016-02-19 at 23 37 53" src="https://cloud.githubusercontent.com/assets/31859/13189801/5a1fd9b8-d762-11e5-9c3f-bae12511c353.png">

I agree that it's kinda odd that it uses `<glossAcronym>` instead of `<glossAbbreviation>` (@robander might be able to comment on that), but it is, as you say, per spec.

So I guess the only actual bug (kinda sorta) here is that the XHTML output uses `<glossAbbreviation>` instead of `<glossAcronym>`, right? I agree that both transtypes should use the same element, at least.

**Comment by robander** [comment]
Not much to comment about except that the creation of `<abbreviated-form>` and most of the glossentry markup did not come about together, with the functions sort of combined at a later date. I believe the original use case for `<abbreviated-form>` was specifically to support acronyms, but it was renamed before final approval to make it more general. However, the original intent can still be seen in the rendering connection to `<glossAcronym>`. 

I had never noticed that disconnect, because I still remembered this as a feature to support acronyms, with the `<abbreviated-form>` name coming about as part of a compromise; I hadn't noticed `<glossAbbreviation>` while also considering the other domain. Regardless, the creation of all of those elements (and the combination of the modules for processing) went through a lot of churn, and I'm not too surprised that some quirks came out in the end.

**Comment by xephon2** [comment]
> So I guess the only actual bug (kinda sorta) here is that the XHTML output uses <glossAbbreviation> instead of <glossAcronym>, right? I agree that both transtypes should use the same element, at least.

@eerohele: Yes. 

I enhanced the test data and added `<glossSurfaceForm>`.

**Test data**: [Glossary-Test.zip](https://github.com/dita-ot/dita-ot/files/139646/Glossary-Test.zip)


**PDF**

As @eerohele said, the PDF complies to the specification and no change is needed here. This is the PDF output of the test data.

![glossarypdf](https://cloud.githubusercontent.com/assets/3266567/13203084/fb3af20e-d8ae-11e5-8299-97637cab8b19.png)
![glossarypdf2](https://cloud.githubusercontent.com/assets/3266567/13203086/fcbd5de2-d8ae-11e5-806f-f5c195527de8.png)

**XHTML**

The XHTML result does comply to the specification (needed changes are summarized at the end of this post). This is the XHTML output of the test data.

![glossaryxhtml](https://cloud.githubusercontent.com/assets/3266567/13203088/03bb6698-d8af-11e5-95b9-dca58b6a83ac.png)
![glossaryxhtml2](https://cloud.githubusercontent.com/assets/3266567/13203091/0ad85b0c-d8af-11e5-9419-433aa6903918.png)


**Needed Changes**

This list summarizes the differences between the processing of the `<term>` and the `<abbreviated-form>` element of the XHTML output.

- `<term>` shows the value of `<glossAbbreviation>` when it is not the first occurance of a `<term>` element referring to the same glossary entry in the same topic. This is wrong. `<term>` should always show the value of the `<glossterm>` element.
- `<abbreviated-form>` shows the value of `<glossAbbreviation>` when it is the first occurance of an `<abbreviated-form>` element referring to the same glossary entry in the same topic.  This is wrong. `<abbreviated-form>` should show the value of `<glossterm>` when it is being used the first time and no `<glossSurfaceForm>` does exist.
- `<abbreviated-form>` shows the value of `<glossAcronym>` when it is not the first occurance of an `<abbreviated-form>` element referring to the same glossary entry in the same topic.  This is wrong. `<abbreviated-form>`  should show the value of the `<glossAbbreviation>` element.
- `<term>` shows the value of `<glossSurfaceForm>` when a glossary entry has a `<glossSurfaceForm>` element and it is the first occurance of the `<term>` element referring to the same glossary entry in the topic.
- `<abbreviated-form>` shows the value of `<glossAbbreviation>` when it is the first occurance of an `<abbreviated-form>` element referring to the same glossary entry in the same topic. This is wrong. `<abbreviated-form>` should show the value of the `<glossSurfaceForm>` element of the glossary entry, if it has one and if not, it should show the value of the `<glossterm>` element.

**Comment by xephon2** [comment]
@eerohele , could you please replace the `pdf` label of this issue with the `html` label?

**Comment by xephon2** [comment]
@jelovirt , could you please add a `priority` label?

**Comment by xephon2** [comment]
#2243 is also related to `<term>` so it should be kept in mind when fixing this.

**Comment by lief-erickson** [comment]
I recently ran into this issue with a project using DITA-OT 3.3.3. Using `<term keyref="gloss-key">` produces output in PDF but `<abbreviated-form keyref="gloss-key">` does not and generates the error below. The `gloss-key` _is_ defined on a glossary entry and `@print="yes"`.

[DOTX060W]: Key 'gloss-key' was used in an abbreviated-form element, but the key is not associated with a glossary entry. Abbreviated-form should ONLY be used to reference to a glossary entry.
