### ISSUE TITLE
XHTML publication throws ${args.xsl} doesn't exist with DITA-OT 2.2.1

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2180]
The DITA-OT 2.2.1 fails with the following error when trying to publish a standard map with a standard concept to XHTML:

```
BUILD FAILED
C:\Users\eike\DITA-OT\dita-ot-2.2.1\build.xml:41: The following error occurred while executing this line:
C:\Users\eike\DITA-OT\dita-ot-2.2.1\plugins\org.dita.xhtml\build_general.xml:168: stylesheet C:\Users\eike\DITA-QA\Map-Test 001\${args.xsl} doesn't exist.
```

I did not use the `args.xsl` parameter.

**Output**
[args.xsl log.txt](https://github.com/dita-ot/dita-ot/files/79851/args.xsl.log.txt)

**Test files for reproduction**
[Map-Test 001.zip](https://github.com/dita-ot/dita-ot/files/79853/Map-Test.001.zip)

**Comment by jelovirt** [comment]
Can't see what could cause this. Could you rerun the conversion in Oxygen using verbose logging so that we can see where `args.xsl` is not set. Just add `-v` into Additional arguments in Advanced tab.

**Comment by xephon2** [comment]
[args.xsl log2.txt](https://github.com/dita-ot/dita-ot/files/80020/args.xsl.log2.txt)

**Comment by xephon2** [comment]
Hmm... I uninstalled the `com.oxygen.webhelp` plugin, it now fails with:

```
`C:\Users\eike\DITA-OT\dita-ot-2.2.1\plugins\org.dita.xhtml\build_general.xml:162: stylesheet C:\Users\eike\DITA-OT\dita-ot-2.2.1\plugins\org.dita.xhtml\xsl\dita2html5.xsl doesn't exist.
```

**Comment by xephon2** [comment]
I removed all plugins that override XHTML. Not the publication works again.

[args.xsl log3.txt](https://github.com/dita-ot/dita-ot/files/80032/args.xsl.log3.txt)

However, that should not happen. If I integrate and deploy my environment using the DITA-OT 2.1, the publication works with all XHTML-overriding plugins installed.

**Comment by xephon2** [comment]
I assume that the DITA-OT picks the first XHTML-related build file here.

**Comment by jelovirt** [comment]
Hmm... are you able to how the debug logs (`-d` argument), for both working and non-working plugin combinations?

**Comment by xephon2** [comment]
Hi Jarno,

sure. I published the same content with 6 different scenarios.

**Scenario 1**

* DITA-OT 2.2.1
* CLI arguments: `-v -d`
* Installed plugins: none
* Build status: `BUILD SUCCESSFUL`
* Logfile: [scenario1.txt](https://github.com/dita-ot/dita-ot/files/80832/scenario1.txt)


**Scenario 2**

* DITA-OT 2.2.1
* CLI arguments: `-v -d`
* Installed plugins: `com.oxygenxml.dita-ot.plugin.webhelp`
* Build status: `BUILD FAILED`
* Error message: `${args.xsl} doesn't exist.`
* Logfile: [scenario2.txt](https://github.com/dita-ot/dita-ot/files/80834/scenario2.txt)


**Scenario 3**

* DITA-OT 2.2.1
* CLI arguments: `-v -d`
* Installed plugins: `org.doctales.reveal`
* Build status: `BUILD FAILED`
* Error message: `dita2html5.xsl doesn't exist.`
* Logfile: [scenario3.txt](https://github.com/dita-ot/dita-ot/files/80836/scenario3.txt)


**Scenario 4**

* DITA-OT 2.1.2
* CLI arguments: `-v -d`
* Installed plugins: none
* Build status: `BUILD SUCCESSFUL`
* Logfile: [scenario4.txt](https://github.com/dita-ot/dita-ot/files/80839/scenario4.txt)


**Scenario 5**

* DITA-OT 2.1.2
* CLI arguments: `-v -d`
* Installed plugins: `com.oxygenxml.dita-ot.plugin.webhelp`
* Build status: `BUILD SUCCESSFUL`
* Logfile: [scenario5.txt](https://github.com/dita-ot/dita-ot/files/80848/scenario5.txt)


**Scenario 6**

* DITA-OT 2.1.2
* CLI arguments: `-v -d`
* Installed plugins: `org.doctales.reveal`
* Build status: `BUILD SUCCESSFUL`
* Logfile: [scenario6.txt](https://github.com/dita-ot/dita-ot/files/80853/scenario6.txt)

**Comment by raducoravu** [comment]
I had some time to look into this. The Oxygen WebHelp plugin tries to be compatible with both DITA OT 1.8 and 2.0.
In our plugin's main build file we have some code like:

{code}      	<target name="dita2webhelp-common" 
      		depends="build-init, 
      		check-license, 
      		check-webhelp-feedback-parameters,
      		dita.map.webhelp.init, 
      		preprocess,
      		xhtml.init,
      		xhtml.image-metadata,
      		dita.out.map.webhelp.toc,
      		dita.webhelp.sitemap.xml,
      		copy-webhelp-resources,
      		copy-css, 
      		dita.topics.html.common, 
      		dita.topics.xhtml, 
      		dita.inner.topics.webhelp,
      		dita.outer.topics.xhtml, 
      		webhelp-indexterms, 	                       
      		create-main-files,
      		webhelp-index"/>
      	
      	
      	<target name="xhtml.init"/>
      	<target name="xhtml.image-metadata"/>
      	<target name="dita.topics.html.common"/>
      
      	
      	<target name="dita.topics.xhtml"/>
      	<target name="dita.outer.topics.xhtml"/>{code}

so we define empty targets like "xhtml.init". We do this because we want the main "dita2webhelp-common" target to work even when the plugin is run with DITA OT 1.8.
Somehow when run with DITA OT 2.x versions smaller than 2.2.1, that empty target "xhtml.init" was not used at all because probably the build files were imported in such a manner that the target "xhtml.init" from the build_general.xml came first. Somehow this is not the case anymore.

**Comment by raducoravu** [comment]
Looking further in the main DITA OT build XML the order of imports in DITA OT 2.2.1 is:

      <import file="plugins/com.oxygenxml.webhelp/build_dita.xml"/>
      <import file="plugins/com.oxygenxml.pdf.css/build.xml"/>
      <import file="plugins/org.dita.base/build_init.xml"/>
      <import file="plugins/org.dita.base/build_preprocess.xml"/>
      <import file="plugins/org.dita.docbook/build_dita2docbook.xml"/>
      <import file="plugins/org.dita.eclipsecontent/build_dita2eclipsecontent.xml"/>

Probably this occurred because the order in which plugins are integrated in the DITA OT is now alphabetical?
Maybe the base DITA OT plugins should always come first. In this way no plugin could overwrite a base target (although maybe this could prove useful sometimes).

**Comment by raducoravu** [comment]
@xephon2 so to make this work right now you would need to edit the Oxygen WebHelp plugin's "build_dita.xml" and remove from it (or comment out) these lines:

        <target name="xhtml.init"/>
        <target name="xhtml.image-metadata"/>
        <target name="dita.topics.html.common"/>

Hopefully Jarno will agree with my proposal about the order of build file imports when the integrator is run.

**Comment by jelovirt** [comment]
@raducoravu Actually both orders are useful sometimes and it just depends on the case. Sometimes it would be convenient to override some things, and then on other cases you really do not want to allow subclasses to override base targets. I suppose we could rename targets that are intended to be private with e.g. underscore prefix like `_xhtml.init` in denote that this should never be overridden. However, due to the nature of Ant and the history of the project, going though every target to decide whether it's overrideable or not would probably be pretty hard.

**Comment by raducoravu** [comment]
I can find a workaround for this problem in our WebHelp plugin (we already have two plugin.xml's, one for 1.8 and one for 2.0).
Ideally and for consistency reasons, I think that the build files from the base plugins should always be imported first. Maybe this could be stated as some kind of flag in their "plugin.xml", somehow state an "priority". Also if this priority had a number as a value, then a plugin could state that it has high importance (comes before those base plugins) or a normal importance.
And they could get sorted based on priority + based on alphabetical sorting as well.

**Comment by xephon2** [comment]
I agree to @raducoravu. That is a good coding style. @jelovirt, do you have an example, why that is necessary? To me that seems to be complexity that nobody needs (KISS!).

**Comment by raducoravu** [comment]
Great, thanks Jarno.
