### ISSUE TITLE
xml:lang set on topic level shouldn't be ignored

### ISSUE THREAD

**Issue by MarkusAbt** [dita-ot/dita-ot#2201]
During PDF2 publication, the `xml:lang` attribute set on topic level is ignored when fetching localized strings. Instead, the `xml:lang` attribute of the map is used.
Verified for versions: DITA-OT 2.1.1, DITA-OT 2.2.1.
In older versions (1.8.5) it worked as expected.

Sample files: https://gist.github.com/MarkusAbt/0b904395aa8972242a61
Contained is a map with `xml:lang="it"`, and two topics with `xml:lang="de"` and `xml:lang="en"`, respectively.

Using the older DITA-OT 1.8.5, the result has *Sommario* (Italian) for the table of contents title, *Gefahr:* for the German hazard statement, and *Danger:* for the English hazard statement.

With current versions of DITA-OT (2.2.1), all string are Italian, i.e. *Pericolo:* for all hazard statements.
The `xml:lang` attributes are still correct in the intermediate files *map_MERGED.xml* and *stage1a.xml*.

**Comment by jelovirt** [comment]
This is by design, the PDF code does not support multi-language output. This issue can be used as a feature request for this functionality.

**Comment by jelovirt** [comment]
@robander does your recent work on PDF fix this?

**Comment by easirois** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  


Sent from Yahoo Mail for iPhone


On Sunday, May 22, 2016, 8:28 AM, Jarno Elovirta <notifications@github.com> wrote:


@robander does your recent work on PDF fix this?

**Comment by robander** [comment]
This is my preferred way of working but I did not explicitly set out to address this. I believe that it is fixed though, based on what I saw with the issue that was setting `en` on documents without a language. For those documents, string variables appeared in English, while elsewhere the correct language was used. 

I believe that this is fixed, because the current default is to use the closest specified language, falling back to the map language if none is found in the topic, falling back to the OT configured default if none is found in the map.
