### ISSUE TITLE
Indexterm ranges no longer work in PDF with Apache FOP [DOT 2.x]

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2214]
One of my topics has:

    <indexterm start="keyID">indexWord</indexterm>

and the other has:

    <indexterm end="keyID">indexWord</indexterm>

and the Index page in the resulting PDF should have something like:

indexWord 3-4

but it only shows the first page number.

**Comment by raducoravu** [comment]
Looking in the "index_fop.xsl", it has a variable called "currentStartRangeValueAttr" which should probably have a different @select value:

        <xsl:variable name="currentStartRangeValueAttr" select="$start-range/opentopic-index:refID/@value"/>

**Comment by eerohele** [comment]
@raducoravu: that fix works otherwise, but it will also generate page number citations for index ranges where both occurrences of the index term are on the same page.

c11b79f should fix the issue and hopefully make the code a bit more explicit.

I've also updated [the fixtures for #2086](https://github.com/eerohele/dita-ot-issues/tree/master/fixtures/2086) to include a case where the terms of the index range are on different pages so you can try out the fix for yourself.

**Comment by raducoravu** [comment]
Thanks @eerohele, tested with the TC samples and fix looks OK, better than before, it avoids that "3-3" page range.
