### ISSUE TITLE
PDF2: Is there a 'best practice' method to creating custom stylesheets?

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#2319]
There are a number of options to creating custom stylesheets.

One method would be to put all the customisations into one of the two custom.xsl files.

For a simple customisation, that is probably a good idea.

The alternative is to use the two custom.xsl files to import customised stylesheets and retain the original file names. For a more complex customisation, it can help to retain the original file name.

However, if you start with a full copy of the original stylesheet, then there will be a lot of templates, variables, etc., etc. that are left untouched.

So, the question is whether to leave these untouched templates, etc., in the customised stylesheet, or to delete them?

Apologies if this is an obvious question!

**Comment by drmacro** [comment]
You should delete all templates you are not overriding. Otherwise you will have big problems in the future when the templates you're not overriding change in the base code.

**Comment by robander** [comment]
There are different opinions on this, so there is not a universal "best practice". I pretty strongly agree with Eliot on this one though, and I think any of the regular contributors likely to speak up will answer the same.

**Comment by xephon2** [comment]
I recommend to firstly generate a plugin with the [dita-generator](http://dita-generator-hrd.appspot.com/). Then you have a good initial state to start working. Do not use `custom.xsl`, this only makes it harder for you to maintain your code over time. If you need to override a template, create a pendant XSL file identically named to its original. Only copy templates from the original XSL to its override pendant, if you need to modify them. That way you always know where a template comes from and, if the `org.dita.pdf2` alters, you will faster notice if a template has been replaced, because its pendant it missing. You will oftenly have to compare templates between `org.dita.pdf2` and your plugin, at least between DITA-OT major releases. So maintainability is probably the most important factor in the design decision. I assume, that most people that are still using DITA-OT 1.8.5, because they are stuck in the mud of `org.dita.pdf2`.

**Comment by DJBHollis** [comment]
Thanks for all the comments - I appreciate it. I have looked at Jarno's plug-in generator, however, it doesn't do headers and footers.

I am using the two `custom.xsl`, but only to import copies of the original stylesheets, not for actual code. Actually, they are both called from `catalog.xml`, so you can't ignore them!

I'm a great believer in [Murphy's law](https://en.wikipedia.org/wiki/Murphy%27s_law), so I don't think I'll delete the templates that I currently do not need, but rather I'll comment them out. Someone is bound to ask for tweaks later on!

One of the issues with 1.8.5 is that Leigh's book is based on it. She has plans to update it, I understand.

FWIW, I'm working with 2.1.2 as it happens to be bundled with a certain XML editor.

**Comment by xephon2** [comment]
To modify headers and footers, you have to fork `static-content.xsl` and `static-content-attr.xsl`.

- Create pendants of `static-content-attr.xsl` and `static-content.xsl` in your plugin.
- Add the import statements to `topic2fo_shell_fop.xsl`.
```xml
    <xsl:import href="plugin:org.dita.pdf2:cfg/fo/attrs/static-content-attr.xsl"/>
    <xsl:import href="plugin:com.your.company:cfg/fo/attrs/static-content-attr.xsl"/>
    <xsl:import href="plugin:org.dita.pdf2:xsl/fo/static-content.xsl"/>
    <xsl:import href="plugin:com.your.company:xsl/fo/static-content.xsl"/>
```
- Add your changes.

>**Hint**
>For static contents you probably need to copy all templates, because you need to change them all.
