### ISSUE TITLE
No list file generated for topic references marked as non-searchable

### ISSUE THREAD

**Issue by radu-pisoi** [dita-ot/dita-ot#2323]
Hi,

I have a DITA map containing some topic references that are marked as non-searchable (@search='no').

I want to know the topics which are not available for searching. I am expecting to find such a file in the temporary folder generated by the 'gen-list' task .

Is there any list file generated for topics that are marked as non-searchable?

I have tested with DITA-OT 2.2.3.

**Comment by robander** [comment]
DITA-OT has never performed any operations based on the `@search` attribute in the maps, so we have not done anything to track it. There are several attributes in maps that are not tracked with list files.

Also - using more recent versions of DITA-OT - that sort of tracking information is usually placed in the `.job.xml` file rather than in list files - but the same is true of that file regarding `@search`, `@query`, and other map attributes that we do not currently evaluate.

**Comment by robander** [comment]
Thinking more about whether this can or should be added to the `.job.xml` file, I think it might be tricky, as the DITA Specification defines `@search` as an attribute that cascades. This means we couldn't really have access to the information until after the `move-meta-entries` step, and it seems strange to add it then. I think the proper solution at that point is that any extension which needs this information would query the map to determine which files are searchable.

**Comment by robander** [comment]
Marking as closed, with the suggestion that the best way to find searchable files is to query the resolved map after `preprocess` runs (most importantly, after `move-meta-entries`).
