### ISSUE TITLE
PDF2: Page breaks have changed

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#2331]
There used to be a page break before every top level topic. That no longer is the case. What has changed? Is this deliberate? Bug?

BTW, now using 2.2.3 in Oxy 18!

**Comment by robander** [comment]
I'm guessing by "top level topic" - you mean the root of any map branch, like a `<chapter>` element in a bookmap. Can you tell me whether you're seeing a change in regular maps, or in bookmaps? Also - I think I recall that you've made quite a leap in versions - what version were you using when it worked differently?

**Comment by DJBHollis** [comment]
Yup! Top level on a ToC, as chapter. I'm using ditamap. I've used 1.8.5 and 2.1.2 with Oxy 17, and now 2.2.3 with Oxy 18.

1.8.5 is as I'd expect. 2.1.2 and later don't have page breaks.

I'm assuming it is something to do with force page break. I've had a quick look, but I can't see anything obvious.

**Comment by drmacro** [comment]
Through 1.8.5 each top-level topic (part, chapter, etc.) was produced as a new page sequence. New page sequences always start new pages.

If this was changed in 2.x so that there's not a one-to-one mapping from top-level topics to page sequences, that would explain the change in behavior.

The original design was always wrong, so changing it would be good, but it would also make sense to maintain the default behavior by setting break-before to "page" for top-level topics.

**Comment by DJBHollis** [comment]
> The original design was always wrong ...

By 'design' do you mean page design or XSLT/XSL:FO design?!

I would suggest that the page design was correct.

I happened to find this old blog post recently: [Handling XSL:FO’s memory issue with large page counts](http://www.scriptorium.com/2009/12/handling-xslfos-memory-issue-with-large-page-counts/)

I don't know if this is still relevant, or even related to this issue.

**Comment by drmacro** [comment]
I mean the design of how page sequences were generated. There was never a need for one page sequence per topic and it should be possible to have a more sophisticated mapping from content to page sequences.

For example, it should be possible to end a page sequence within a topic, start a new one for rotated tables or foldouts, and then start another one that has the same page masters as the first sequence.

**Comment by DJBHollis** [comment]
Is there any chance of someone figuring out where to put a page-break-before, please?

**Comment by drmacro** [comment]
Interesting, I find this in root-processing.xsl:

`
  <xsl:variable name="map-based-page-sequence-generation" select="true()" as="xs:boolean"/>
`

This variable is used later to choose between new map-based page sequence generation (a better design) or the old per-topic way

Looks like somebody intended to make this a runtime parameter but never go that far.

**Comment by drmacro** [comment]
Looks like you can override:

`
<xsl:template match="*" mode="commonTopicProcessing">
`

In commons.xsl and add logic to add break-before="page" for whatever topics you want.

You can see there's already a check to see if the topic has any ancestor topics, which I think is what you want.

Alternatively, if you have a custom top-level XSLT, you could override the map-base-page-sequence-generation variable to set it to false()

**Comment by DJBHollis** [comment]
Thanks v. much. I set map-based-page-sequence-generation to false, and it was 'back to normal'. Maybe not the best solution, but it will do for now.

**Comment by robander** [comment]
Marking this closed - the XSL-FO page sequence changes were intentional and there is still a mechanism to keep the old behavior.

**Comment by DJBHollis** [comment]
But the new sequences do not provide the same page breaks. The changes might be intentional, but they ought to maintain the established, and accepted page break behaviour.

**Comment by DJBHollis** [comment]
So the intention of this change is to have one page sequence flow per map. That is, ditamap rather than bookmap.

I can see that that makes sense for bookmap where each chapter or appendix, etc. has a child ditamap.

There is an issue for PDF from ditamap. The choice is to revert to the 1.x page sequencing method, or add some logic as Eliot, @drmacro, suggests. I believe it would be necessary to check `$mirror-page-margins` and add either `break-before="page"` or `break-before="even-page"`.

Is there an issue for a bookmap that doesn't use child ditamaps? Where all the content is attached directly to the bookmap. Does that automatically revert to the 1.x page sequencing?

**Comment by drmacro** [comment]
The use or non-use of submaps is not relevant: all map references are resolved during preprocessing, resulting in a single map that is then the input to the PDF2 map merge process.

The generation of page sequences should be driven primarily by the need to have different page numbering rules for a given page sequence, e.g., frontmatter (numbered with lowercase roman numerals), body (arabic numbers), and backmatter, or by folio-by-chapter numbering (in which case you need per-chapter page sequences). It can also be driven by the need to have different page geometry for different pages, e.g., foldouts, rotated tables, etc. However, a simple topic-boundary-based approach won't work for that because the page sequence boundaries don't necessarily align to topic boundaries in that case (or don't align to sibling topics).

For the short term I think the correct response would be to have break-before="page" or "even-page" be the default, restoring the default behavior, with a runtime option to turn that behavior off and a specific XSLT extension point to make it easy to change the break-before value for specific topics.

But that should probably be managed as a separate issue--since I've proposed it I'm happy to take on the implementation task--it shouldn't be hard.
