### ISSUE TITLE
args.hdf should not have a root element

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2358]
The parameter `args.hdf` specifies an XML file that contains content to be placed in the document head, see [dita-ot docs: HTML-based output parameters](http://www.dita-ot.org/2.2/parameters/parameters-base-html.html).

`args.hdf` is parsed and needs to have a root element. Because of that, you cannot inject a bunch of `<link>` and `<script>` elements at once to, for example, include multiple JS and CSS files. You only can inject a single element.

If you put multiple elements in the XML file, SAX complains about that:

```
Error reported by XML parser Cause: org.xml.sax.SAXParseException; systemId: file:/../hdf.xml; lineNumber: 4; columnNumber: 2; The markup in the document following the root element must be well-formed.
```

It would be nice, if I could wrap more elements in a dummy root element, that would be unwrapped during processing.

**Comment by jelovirt** [comment]
Generally speaking `args.hdr` and `args.ftr` are not a particularly good feature and trying to implement something like this will make the code even more complex, especially if we were to add error recover for cases where the file is not a well-formed XML document.

**Comment by robander** [comment]
I think there's a distinction between `args.hdr` / `args.ftr`, and `args.hdr` (the bit that goes in the `<head>`. For the first two, there generally shouldn't be a problem with the wrapper element, because a `<div>` or `<header>` is appropriate and will not cause issues. With `args.hdr` there is no valid element that can be copied as-is into the HTML `<head>` element without validation issues.

For my own customizations we've supported `<div>` as a wrapper in this file (not in the others), which is discarded when injecting the content. That customization was added so long ago that I thought it was part of the core code.

**Comment by xephon2** [comment]
I looked at `dita2htmlImpl.xsl`, @robander was right. 

```xml
<!-- For header file processing, pull out the wrapping DIV if one is there -->
<xsl:template match="/div" mode="add-HDF">
  <xsl:apply-templates select="*|comment()|processing-instruction()|text()" mode="add-HDF"/>
</xsl:template>
```

So wrapping `<link>` and `<script>` elements in a dummy `<div>` works. I've tested this with `DITA-OT2.2.5`.

I close this issue and open a doc issue.
