### ISSUE TITLE
Fix CI build for release builds

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2395]
- [x] In the configuration.properties the `otversion` key has the value "2.3+69a962e"
- [ ] <del>HTML5 contains `sass` folder</del>
- [x] ODT contains `src`, `test` and `resources` folders
- [x] RTF contains `src`  folder
- [x] docsrc contains `temp` folder

**Comment by raducoravu** [comment]
+ "org.dita.odt" also contains "src", "test" and "resources" folders

**Comment by raducoravu** [comment]
+ "org.dita.wordrtf" also contains "src" folder.

**Comment by infotexture** [comment]
The `docsrc/` folder of the distribution package also contains an empty `temp/` subfolder that should be excluded from the build process.

**Comment by jelovirt** [comment]
I'm not sure if SASS should be left out of the distribution package. @infotexture @eerohele what's your take, should we distribute the SASS files even though we don't distribute any build file for convert them to CSS?

**Comment by infotexture** [comment]
Since the `sass` folder only takes up a few kilobytes, I would be inclined to include them for the benefit of those who would like to extend the defaults with their own mixins, partials, etc. 

That would allow web devs who are unfamiliar with DITA-OT to extend styling and simply regenerate the common CSS files using standard Sass practices, rather than requiring customization of the `org.dita.html5` plug-in.

To better support that use case, we might decide to ship a Sass build file later and provide an additional `args.sass` parameter to hook into the CSS pre-processing rather than overriding styles in `commonltr.css` later with a custom CSS file specified via `args.css` — but that should be treated as a separate issue.

**Comment by eerohele** [comment]
I agree with @infotexture. I can certainly see myself wanting to extend the default DITA-OT SASS files.
