### ISSUE TITLE
PDF2: XEP & FOP comparison

### ISSUE THREAD

**Issue by DJBHollis** [dita-ot/dita-ot#2418]
Based on: #2415

DOT 1.8.5 in Oxy 18 

DITA 1.2 spec.
XEP builds: -Xmx1536m
FOP builds: -Xmx1536m

DOT 2.2.3 in Oxy 18

DITA 1.2 spec.
XEP fails: -Xmx12288m
FOP builds: -Xmx1536m

DITA 1.3 Base
XEP builds: -Xmx1536m
FOP builds: -Xmx1536m

DITA 1.3 Technical Content
XEP fails: -Xmx12288m
FOP builds: -Xmx1536m

All Inclusive
XEP fails: -Xmx12288m
FOP builds: -Xmx1536m

Also tried XEP with an additional parameter: maxmemory with values up to 12288m, and still the build failed. Please note Radu's comments re. forked process.

**Comment by robander** [comment]
If the failure is in XEP, then I'm not sure what we can do about it - this sounds like a possible limitation in what XEP can handle within certain memory constraints. As @drmacro mentioned in #2415, it has always been the case that certain large documents require additional memory.

FWIW - when I search for `<xref>` elements in the full 1.2 spec, I find 65,601. In the full DITA 1.3 spec I find 108,339. I expect that in each case, the published spec ends up with many more, because so many of those are in sections reused with conref. There are many, many more added as a result of map relationships and index entries. I know that every link results in several pieces of FO markup and a certain minimum amount of size in the final PDF. I can easily imagine that a processor trying to store that much link information in an array, or in some other variable, might end up using what otherwise seems to be a ridiculous amount of memory.

**Comment by DJBHollis** [comment]
I'm surprised that XEP fails when FOP does not. I'd want to be sure that the issue is not related to the DOT in any way.

**Comment by jelovirt** [comment]
#2415 has already been opened, and this is just additional information related to it. This issue is neither a bug report or feature request, thus closing it.

**Comment by kbrown01** [comment]
Please note that I had no problems formatting all of the provided documents about using 1024MB memory in both 32bit and 64bit Java using RenderX XEP. 

https://github.com/dita-ot/dita-ot/issues/2415#issuecomment-225980606
