### ISSUE TITLE
Error when defining keys for submaps

### ISSUE THREAD

**Issue by dagoss** [dita-ot/dita-ot#2425]
I receive errors when attempting to define keys for maps in a lower directory to the root map. Consider the following example.

map.ditamap:

```
<map>
    <mapref href="submap/submap.ditamap"/>
</map>
```

submap/submap.ditamap:

```
<map>
    <mapref href="subsubmap/subsubmap.ditamap" keys="subsubmap"/>
</map>
```

This results in error messages like below when trying to process map.ditamap. It looks like the OT is attempting to resolve the key relative to the root map, not the submap where it is defined. Is this expected behavior?

> [mapref] Recoverable error on line 84 of maprefImpl.xsl:
>  [mapref]   FODC0002: java.io.FileNotFoundException:
>  [mapref]   /var/tmp/temp20160630101846309/subsubmap/subsubmap.ditamap (No such file or directory)
>  [mapref] file:/hdrs/goss/misc/mapref-test/submap/submap.ditamap:6:63: [DOTX031E][ERROR]: The file subsubmap/subsubmap.ditamap is not available to resolve link information.
>   [mapref] Recoverable error on line 357 of maprefImpl.xsl:
>   [mapref]   FODC0002: java.io.FileNotFoundException:
>   [mapref]   /var/tmp/temp20160630101846309/subsubmap/subsubmap.ditamap (No such file or directory)

(DITA-OT version 2.2.1)

**Comment by drmacro** [comment]
While this is probably a bug it normally doesn't make sense to define keys on local-scope submaps because such a key would have no value (there would be no reason to every refer to that key as submaps are not something you can link to for navigation purposes and after the map resolution process the original mapref topicref is not reflected in the merged map (which is probably the source of the error you're seeing).

One could argue that the current map merge process is not optimal and that a better approach would be to replace maprefs with topicgroup elements that reflect the properties of the mapref and then contain the direct child topicrefs of the referenced map. That would preserve the key while not disturbing the effective navigation structure of the merged map. But the OT doesn't currently work that way.
