### ISSUE TITLE
DITAval values with brackets are not interpreted

### ISSUE THREAD

**Issue by drdavesearle** [dita-ot/dita-ot#2457]
Windows 7; DOT 2.3.2 (also earlier 2.x.x versions)

If DITAval prop attribute value has brackets in it, then the gen-list process ignores them.  For example in the DITA file we have:

	<p platform="MAC(OS)">MAC OS description</p>

In the DITAval file:

	<prop action="include" att="platform" val="MAC(OS)"/>

The OT log shows:

gen-list:
[gen-list] Using Xerces grammar pool for DTD and schema caching.
[gen-list] Processing file:/C:/temp/test-ditavals.dita
[gen-list] [DOTJ031I][INFO] No specified rule for 'MAC=OS' was found in the ditaval file. This value will use the default action, or a parent prop action if specified. To remove this message, you can specify a rule for 'MAC=OS' in the ditaval file.
[gen-list] [DOTJ031I][INFO] No specified rule for 'platform=OS' was found in the ditaval file. This value will use the default action, or a parent prop action if specified. To remove this message, you can specify a rule for 'platform=OS' in the ditaval file.
[gen-list] Serializing job specification

Other DITAval attributes such as otherprops show the same effect. These values worked in DOT 1.8.5

**Comment by contrext** [comment]
Your use of DITAVAL is incorrect.

The prop spec should be att="MAC" val="OS"

That is, the value "MAC(OS)" is equivalent to MAC="OS" (the use of the @platform attribute doesn't really matter because you've used the generalized syntax.

See http://docs.oasis-open.org/dita/dita/v1.3/os/part3-all-inclusive/archSpec/base/usage-of-conditional-processing-attributes.html

So not a bug.

**Comment by drdavesearle** [comment]
Many thanks.
