### ISSUE TITLE
New common merge process

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2485]
We currently have a single merge process code in OT, the one originally developed for PDF. However, it’s not really optimal for general use and IMO is not particularly good. We should develop a new merging code based on this code and merge PDF to use it.

The current output from merge is

``` xml
<map>
  <opentopic:map>
    <!-- map contents -->
  </opentopic:map>
  <!-- topics -->
</map>
```

I suggest the new output is like compound topic, but can also contain a map. Also, the map should be output the the end of the document, because it's more efficient from processing point of view.

``` xml
<dita>
  <!-- topics -->
  <map>
    <!-- map contents -->
  <map>
</dita>
```

**Comment by drmacro** [comment]
An an alternative to re-implementing the current merge, which reflects XSLT 1 limitations, is to generate a much-smaller data set that supports numbering, grouping, and sorting, and then use map-driven processing to do full-publication processing, with the enumeration-supporting data set as a parameter to the final-form processing.

This avoids the cost and complexity of the merge processing with essentially the same memory footprint as processing the merged result.

**Comment by jelovirt** [comment]
I don't see that as an alternative, but rather a feature of the new merge processing. The process could be configured/modified to skip some of the content, to result in a smaller output document.

**Comment by drmacro** [comment]
My point is that there's no reason to physically merge the map and the topics--that's just a waste of I/O effort.

What is required is a convenient XML structure that reflects the navigation hierarchy of the publication so that you can use e.g. xsl:number to count things.

Given that then the topics can be processed in the context of the map by operating on the map and resolving topicrefs dynamically. Doing a literal merge of the entire data doesn't buy you anything at that point.

**Comment by jelovirt** [comment]
My point with modifying/configuring the merge was exactly that, you don't _output_ all the merged content. Regardless of what you write out, you still need to _read_ all the topics to collect the information you mentioned.

**Comment by drmacro** [comment]
Agreed, you do need to read all the topics, but you can do the necessary data collection as part of the final-form processing, meaning you don't need a separate preprocess stage that reads the topics then writes a data set to disk.

Of course, we could do all the preprocessing stages as part of the final-form processing as well--there's actually no justification for having multiple stages if all the processing is XSLT, which we're very close to having....

**Comment by jelovirt** [comment]
But if we don't collect the topic data, why run the merge process for that use case at all? We already have the merged map, isn't that enough?

**Comment by drmacro** [comment]
No, the merged map isn't enough because it can't be used to do numbering in a simple way (e.g., using xsl:number).

For that you need a merged structure that reflects the title hierarchy and reflects any things you might want to number relative to it (e.g., figures and tables).

For indexing you need to group and sort the index terms, likewise, for glossary sorting useful to build a grouped and sort list of glossary entries.

The merged map is appropriate for driving the processing of the topics to produce the final result but that process needs to have the enumeration data structure available. 

In the current PDF2 process that enumeration structure is inherent in the merged result, although the separation of the map structure from the merged topics makes it more complicated than necessary.

The current HTML process has nothing.

The D4P map-driven processing builds the enumeration support structure and then provides it as a parameter to the final-phase processing, which is applied to the map.

**Comment by raducoravu** [comment]
Seeing how hard-drive intensive is the DITA OT, for each stage processing thousands of files on the hard drive, one option would be to create the merged map at the very beginning, as the first step and then have all stages applied on that merged single XML.

**Comment by ballums** [comment]
Radu and Eliot,

I can offer some feedback on creating a single merged map at the beginning of the process.  That's how ePublisher handles DITA map inputs as that closely approximate's ePublisher expectations for legacy document inputs (Word and FrameMaker).

Since ePublisher has been working with a single merged map for all operations for the past 10 years, I can tell you the approach has its ups and downs.  The biggest issue relates to memory.  While you can side-step certain problems by running under 64-bit Java, the fact is, if you load a 110MB DITA map into memory, you have a lot of data to work with.  XPath operations are simple (you can use <xsl:number> operations).  But, breaking files back out into HTML chunks is quite a bit of work as ePublisher converts DITA hierarchies to flat content.  This issue that would not affect standard Java if you preserve the DITA map hierarchy in the merged document.

The main point is that some folks pull in a LOT of data using nested DITA maps.  I'd suggest you benchmark the generation of HTML files (roughly 1-1 per DITA topic) against a PDFs (merging all topics) and see how your memory/performance numbers line up.  In the past, when adding support for DITA-OT 1.8 to ePublisher, we encountered memory issues with 32-bit Java.  We did add support for 64-bit Java, but also wound up implementing an XSL merge that operates within 32-bit memory limits for large DITA map (100MBs+).  I understand there have been many updates to date merge code for later DITA-OT releases.  I'm not sure if the memory issue was addressed.  Might double-check before going down the single merged file path.
