### ISSUE TITLE
Remove the "args.breadcrumbs" parameter

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2554]
The parameter is documented and it connects to a parameter in the XSLT stylesheets called "BREADCRUMBS" which does nothing.
I think we should remove it, it is a source of confusion as we have users trying to set values to the parameter and expecting that it influences the output in some way.

**Comment by jelovirt** [comment]
The current code doesn't do anything with `args.breadcrumbs`, but we do want it to be possible to output breadcrumbs.

My preference is to remove `args.breadcrumbs` and `BREADCRUMBS`, since they don't work. If we at some point add support for toggling breadcrumbs with a parameter, we can use the old parameter names.

**Comment by raducoravu** [comment]
Yes, no need to leave unimplemented parameters based on a future wish list.
