### ISSUE TITLE
Proper publishing support for machinery tasks

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2557]
Machinery tasks have various elements like:

 "prelreqs" (+ topic/section task/prereq taskreq-d/prelreqs ) => Preliminary Requirements:
"reqconds" (+ topic/ul task/ul taskreq-d/reqconds ) => Conditions
"supequip" (+ topic/p task/p taskreq-d/supequip )=> Equipment
"closereqs" (+ topic/section task/postreq taskreq-d/closereqs ) => Closing Requirements
"reqconds" (+ topic/ul task/ul taskreq-d/reqconds ) => Conditions

for which we would need specific labels to be shown when the "args.gen.task.lbl" is enabled.

**Comment by robander** [comment]
It makes sense that this would be tied to the `args.gen.task.lbl` parameter, even if that feels a bit odd. Just because years-on, I don't like the parameter name, and think it should just Be On By Default, but ... the fun of legacy.

I think we still haven't really come up with a policy for how to handle strings where we only have one (or maybe 5) translations - I've heard a few different ideas but we haven't settled on anything. Not sure if this is the best place to hash that out - #2248 may be better. Or maybe a doc issue, since we'd have to actually document our decision somewhere?

**Comment by raducoravu** [comment]
Two more end users requested special handling for machinery tasks on the Oxygen forum:
https://www.oxygenxml.com/forum/post53304.html#p53304
