### ISSUE TITLE
"Specified path does not found" error in conref processing

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#2565]
Building attached DITA instance (20170113-diff.zip [20170113-diff.zip](https://github.com/dita-ot/dita-ot/files/704333/20170113-diff.zip) ) into XHTML causes "Specified path does not found" error in conref phase in DITA-OT 2.4.2.

[Command-line]
```
bin\dita -i D:\SVN\pdf5\diffs\20170113-diff\ja-JP\bmAce.ditamap -f xhtml -o D:\SVN\pdf5\diffs\20170113-diff\ja-JP\out --generate.copyouter=3 --clean.temp=no --dita.temp.dir=D:\SVN\pdf5\diffs\20170113-diff\ja-JP\tmp\xhtml --logfile=D:\SVN\pdf5\diffs\20170113-diff\ja-JP\log.txt -v
```

[Error portion of the log file]
```
conref:
   [conref] Transforming into D:\SVN\pdf5\diffs\20170113-diff\ja-JP\temp\xhtml
   [conref] Loading stylesheet D:\DITA-OT\dita-ot-2.4.2\xsl\preprocess\conref.xsl
   [conref] Processing D:\SVN\pdf5\diffs\20170113-diff\ja-JP\temp\xhtml\ja-JP\topic\tWhenConnectingASinglePrinter.dita
   [conref] Recoverable error on line 180 of conrefImpl.xsl:
   [conref]   FODC0002: java.io.FileNotFoundException:
   [conref]   D:\SVN\pdf5\diffs\20170113-diff\ja-JP\temp\xhtml\ja-JP\topic\..\..\collection-topic\tWhenConnectingPrintersStep01Template.dita (指定されたパスが見つかりません。)
   [conref] Error on line 277 of conrefImpl.xsl:
   [conref]   XTTE0570: An empty sequence is not allowed as the value of variable $domains
   [conref]   at xsl:apply-templates (file:/D:/DITA-OT/dita-ot-2.4.2/xsl/preprocess/conrefImpl.xsl#804)
   [conref]      processing /task/task[1]/title[1]
   [conref]   at xsl:apply-templates (file:/D:/DITA-OT/dita-ot-2.4.2/xsl/preprocess/conrefImpl.xsl#804)
   [conref]      processing /task/task[1]
   [conref]   at xsl:apply-templates (file:/D:/DITA-OT/dita-ot-2.4.2/xsl/preprocess/conrefImpl.xsl#34)
   [conref]      processing /task
   [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
   [conref] Processing D:\SVN\pdf5\diffs\20170113-diff\ja-JP\temp\xhtml\ja-JP\topic\tWhenConnectingMultiplePrinters.dita
   [conref] Recoverable error on line 180 of conrefImpl.xsl:
   [conref]   FODC0002: java.io.FileNotFoundException:
   [conref]   D:\SVN\pdf5\diffs\20170113-diff\ja-JP\temp\xhtml\ja-JP\topic\..\..\collection-topic\tWhenConnectingPrintersStep01Template.dita (指定されたパスが見つかりません。)
   [conref] Error on line 277 of conrefImpl.xsl:
   [conref]   XTTE0570: An empty sequence is not allowed as the value of variable $domains
   [conref]   at xsl:apply-templates (file:/D:/DITA-OT/dita-ot-2.4.2/xsl/preprocess/conrefImpl.xsl#804)
   [conref]      processing /task/task[1]/title[1]
   [conref]   at xsl:apply-templates (file:/D:/DITA-OT/dita-ot-2.4.2/xsl/preprocess/conrefImpl.xsl#804)
   [conref]      processing /task/task[1]
   [conref]   at xsl:apply-templates (file:/D:/DITA-OT/dita-ot-2.4.2/xsl/preprocess/conrefImpl.xsl#34)
   [conref]      processing /task
   [conref] Failed to transform document: An empty sequence is not allowed as the value of variable $domains
```
This surely works in the past when I used another the folder structure. But when I changed the folder structure for multiple language support, this error happen.

In my examination the referenced file path "D:\SVN\pdf5\diffs\20170113-diff\ja-JP\temp\xhtml\ja
-JP\topic\..\..\collection-topic\tWhenConnectingPrintersStep01Template.dita" should be "D:\SVN\pdf5\diffs\20170113-diff\ja-JP\temp\xhtml\ja-JP\topic\..\collection-topic\tWhenConnectingPrintersStep01Template.dita" because this file exists in temp folder.

I'm not sure whether this folder structure is not appropriate DITA-OT processing. But this structure is indispensable for my user to author/publish their contents without CMS.

**Comment by robander** [comment]
Reproduced in 2.4.3.

**Comment by lief-erickson** [comment]
I am having the exact same issue. My directory structure is just like @ToshihikoMakita's as shown in his 20170113-diff.zip.

**Comment by lief-erickson** [comment]
I'm not sure if this will help @ToshihikoMakita, but we are using git (Bitbucket Server) for our source control. We also do not use a (C)CMS. We found that by placing the 'common' content into its own repository and using [git-subrepo](https://github.com/ingydotnet/git-subrepo) we were able to put the common content in a location where the DITA OT was able to find and use it. This was relatively easy for us to do because we already had the common content in its own git repository. We can update, push, and pull common content separate from any product-specific content. Git's submodule and subtree were not sufficient for our needs. 

In our source, different product lines require the common content to be at a different level in the directory hierarchy, and git-subrepo works for us because it allows that.

If you're using git, git-subrepo may be a viable workaround for this issue, and may even be useful for other reasons.

We're on Windows and the git subrepo installation was a bit fiddly for us. We also set up custom actions in our Git client (SourceTree) to push/pull to the subrepo rather than having to use the terminal command line.

**Comment by ToshihikoMakita** [comment]
@lief-erickson 
Thank you for your suggestion. 
Unfortunately my user uses Subversion for their document management and waiting for fix of this issue.

**Comment by infotexture** [comment]
@ToshihikoMakita Until the issue is resolved, you could implement the workaround @lief-erickson proposed using Subversion's  [svn:externals](http://svnbook.red-bean.com/en/1.7/svn.advanced.externals.html) property.

You could manage the common content in an external repository and  use `svn:externals` to replicate the original folder structure in your project so the files are still available in the expected locations.

**Comment by ToshihikoMakita** [comment]
@infotexture Thank you for your information and useful link. 
I will consider adopting svn:externals in my project until this issue has been resolved.
