### ISSUE TITLE
Can't retrieve https external images for HTML5 transtype

### ISSUE THREAD

**Issue by shaneataylor** [dita-ot/dita-ot#2575]
Using the stock 2.4.2 HTML5 transformation, my topic contains the following reference to a non-local image:

```
<image href="https://www.webassign.net/images/circleAsm.gif" scope="external"/>
```

I get the following error:

```
[image-metadata] Failed to read image https://www.webassign.net/images/circleAsm.gif 
metadata: sun.security.validator.ValidatorException: PKIX path building failed: 
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid 
certification path to requested target
```

The image can be retrieved using http, but increasingly such resources use https.

**Comment by infotexture** [comment]
I tested this with the latest code from the `develop` branch and the image reference above and received a **403** (Forbidden) error, which suggests the request is valid, but the server may be refusing to respond to it:

```
[image-metadata] Failed to read image https://www.webassign.net/images/circleAsm.gif metadata:
Server returned HTTP response code: 403 for URL: https://www.webassign.net/images/circleAsm.gif
```

I received no such error when testing with another image that is available via HTTPS:

```
<image href="https://travis-ci.org/dita-ot/docs.png?branch=develop" scope="external"/>
```

Output is generated correctly and the image is referenced in output from its original external source as expected.

I repeated the test with the original reference and this time the request was honored, so this appears to be an issue with the availability of the referenced resource rather than a DITA-OT issue.

**Comment by shaneataylor** [comment]
@infotexture Did you try accessing the image directly by URL in your browser? Maybe I'm being fooled into thinking this is publicly available because it's available to me.

**Comment by infotexture** [comment]
Yes, I'm able to access the image via the browser.

The 403 errors during the Ant build seem to be intermittent.

**Comment by raducoravu** [comment]
This kind of problem:

> metadata: sun.security.validator.ValidatorException: PKIX path building failed: 
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid 
certification path to requested target

occurs when the Java application (the ANT process which drives the DITA OT) does not consider the certificate of the HTTPS web server valid.
Your web site is signed by "COMODO CA Limited".
You can google for problems like this: 
"COMODO CA Limited  unable to find valid  certification path to requested target"

Possibly updating to the latest possible Java VM might fix this problem.
