### ISSUE TITLE
empty nav toc in topic with @chunk="to-content" 

### ISSUE THREAD

**Issue by lionelmoi** [dita-ot/dita-ot#2577]
When @chunk="to-content" is specified on the topicref in and nav-toc set to partial the `<nav/>` element in the html5 output is empty.

**Comment by tomorales** [comment]
Ran into something similar to this. The problem seems to be this code in nav.xsl:

  <xsl:variable name="current-file" select="translate(if ($FILEDIR = '.') then $FILENAME else concat($FILEDIR, '/', $FILENAME), '\', '/')"/>
  <xsl:variable name="current-topicrefs" select="$input.map//*[contains(@class, ' map/topicref ')][dita-ot:get-path($PATH2PROJ, .) = $current-file]"/>

The current-topicrefs variable is supposed to be set to any topicrefs in the map whose @href attribute matches the value of the current-file variable. For example, if you're processing foo.dita, then <topicref href="foo.dita"> would match.

However, if the topicref to foo.dita has @chunk="to-content", then the DITA-OT rewrites the topicref so that it has the form <topicref chunk="to-content" href="foo.dita#topicid">, preventing the @href attribute from matching the current-file variable.

A solution to this problem is to first concatenate the first topic @id with the current-file variable, determine if there are any matching topicrefs, and (if not) then to fall back and try to find any topicrefs that match the current-file variable. I've verified that the following additions to nav.xsl fix this problem:

  <xsl:variable name="current-id" select="(//*[contains(@class, ' topic/topic ')])[1]/@id"/>
  <xsl:variable name="current-topicrefs" select="if ($current-id and $input.map//*[contains(@class, ' map/topicref ')][dita-ot:get-path($PATH2PROJ, .) = concat($current-file, '#', $current-id)]) then $input.map//*[contains(@class, ' map/topicref ')][dita-ot:get-path($PATH2PROJ, .) = concat($current-file, '#', $current-id)] else $input.map//*[contains(@class, ' map/topicref ')][dita-ot:get-path($PATH2PROJ, .) = $current-file]"/>

**Comment by lionelmoi** [comment]
I made a pull request with my fix : https://github.com/dita-ot/dita-ot/pull/2578

Maybe you could comment there?
