### ISSUE TITLE
Plugin installation looks for Ant code in base directory

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2583]
Reported in the google group, and I've reproduced on both 2.4.1 and 2.4.3:
https://groups.google.com/forum/#!topic/dita-ot-users/4lnue2bt8Is

Following the instructions in our documentation (CC: @infotexture), I've set up the "html-custom-css" transform type:
http://www.dita-ot.org/dev/dev_ref/html-customization-plugin-bundle-css.html

As reported in the issue, when I try to install (with either `bin\dita -install` or `bin\ant -f integrator.xml`), I get this message on the console:
```
C:\DITA-OT\dita-ot-2.4.3>bin\dita --install
[integrate] [Fatal Error] :-1:-1: Premature end of file.
[integrate] Premature end of file.
```

I tried changing `plugin.xml` to use a name other than `build.xml`:
`<feature extension="dita.conductor.target.relative" value="testbuild.xml"/>`

With that, it's clear that the integrator is looking for my build file in the DITA-OT base directory:
```
C:\DITA-OT\dita-ot-2.4.3>bin\dita --install
[integrate] C:\DITA-OT\dita-ot-2.4.3\testbuild.xml (The system cannot find the file specified.)
```

In my 2.4.1 install, I tried changing the actual file name (and `plugin.xml` entry) to `mybuild.xml`, with that failure. I then tried `happybuild.xml`, and ... it worked. Changing back to `build.xml` works. I have no idea and think I may have entered some non-deterministic test universe. But I can reliably reproduce this issue in 2.4.3.

I also built my own (similar) transform types before ever seeing this report, in 2.4.1, and did not encounter this issue. So again, I'm confused.

**Comment by robander** [comment]
I'm wondering if this is somehow related to Unicode byte-order-markers, but I'm not sure - still not able to figure out how I'm sometimes getting this to work, sometimes not. When I create a new file on Windows, using the file explorer -- "new text file" that is renamed to plugin.xml -- this seems to happen. When I copy in an existing XML file and tweak the values, or create a new XML file in Oxygen, I think it works.

**Comment by jelovirt** [comment]
Could you show the output for running integrator with verbose logging.

**Comment by robander** [comment]
Sure, attaching the logs from `dita` and `ant` integration process. I started over with a freshly unzippped copy of DITA-OT 2.4.1, no other modifications and no builds run so far.
* Create new directory com.example.html5.custom.css
* New text file, rename to "plugin.xml"
* Open file (Oxygen), text mode, paste in sample from doc
* Create new directory css
* New text file, rename to "custom.css"
* Open file (Oxygen), paste in sample from doc
* New text file, rename to "build.xml"
* Open file (Oxygen), text mode, paste in sample from doc
* `bin\dita -install -v -l initial.log`
* `bin\ant -f integrator.xml -v -l initialant.log`
* Rename build.xml to myBuild.xml
* Update plugin.xml so that extension uses myBuild.xml
* `bin\dita -install -v -l second.log`
* `bin\ant -f integrator.xml -v -l secondant.log`
* Renamed all logs from .log to .txt because github doesn't like `.log` :roll_eyes: 
[initial.txt](https://github.com/dita-ot/dita-ot/files/755009/initial.txt)
[initialant.txt](https://github.com/dita-ot/dita-ot/files/755012/initialant.txt)
[second.txt](https://github.com/dita-ot/dita-ot/files/755010/second.txt)
[secondant.txt](https://github.com/dita-ot/dita-ot/files/755011/secondant.txt)

**Comment by infotexture** [comment]
I was able to reproduce this on macOS Sierra and verify the user's [workaround from the original thread](https://groups.google.com/d/msg/dita-ot-users/4lnue2bt8Is/GgxYVBFkBwAJ):

> I launched the DITA command from the plugin directory and it works ! No error message.

The error is thrown when the `dita --install` command is run from the root directory of the DITA-OT installation:

```
~/D/W/D/O/dita-ot-2.4.3 $ bin/dita --install
[integrate] [Fatal Error] :-1:-1: Premature end of file.
[integrate] Premature end of file.
```

When the same command is run from the plug-in directory, the plug-in is correctly installed:

```
~/D/W/D/O/dita-ot-2.4.3 $ cd plugins/com.example.html5.custom.css/
~/D/W/D/O/d/p/com.example.html5.custom.css $ ../../bin/dita --install
```

The error is apparently not **caused by** using the `build.xml` filename used for the `dita.conductor.target.relative` extension — _it just makes it harder to trace_.

If I change the filename from `build.xml` to `custom-css-plugin-build.xml` and update `plugin.xml` accordingly, I get the same results @robander reported above:

> With that, it's clear that the integrator is looking for my build file in the DITA-OT base directory:

```
~/D/W/D/O/dita-ot-2.4.3 $ bin/dita --install
[integrate] /Users/username/D/W/D/O/dita-ot-2.4.3/custom-css-plugin-build.xml 
  (No such file or directory)
```

It still won't `--install` when run from the toolkit's root, but works fine when run from the plug-in's directory (just like when using the `build.xml` filename).

:boom: It seems the `.relative` part of the `dita.conductor.target.relative` extension isn't being interpreted correctly in this particular case.

Attaching plug-in created by copy-and-pasting code from the original [docs example](http://www.dita-ot.org/dev/dev_ref/html-customization-plugin-bundle-css.html): 

[com.example.html5.custom.css.zip](https://github.com/dita-ot/dita-ot/files/766810/com.example.html5.custom.css.zip)

_(All files were created with UNIX `LF` line endings, UTF-8 encoding, no BOMs)_
