### ISSUE TITLE
Add extra <div> container for note of type danger

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2609]
Let's say I have in the DITA topic:

```xml
<note type="danger">It's dangerous</note>
```
and I publish using "args.gen.task.lbl"="YES".

The resulting HTML content looks like this:
```html
<div class="dangertitle">DANGER</div>
<div class="note danger">It's  dangerous</div>
```

So it ends up as two sibling div's.
If for example I would publish note with type warning:

```xml
<note type="warning">It's dangerous</note>
```

the resulting HTML output looks like this:
```html
<div class="note warning"><span class="warningtitle">Warning:</span>  It's dangerous</div>
```
so it contains a div which contains everything else.
So we have an inconsistent approach, somehow in probably both cases we need a div which surrounds everything.

**Comment by robander** [comment]
I'm pretty sure this inconsistent approach was just carried over from our pre-DITA days of IBM formatting for different warnings in SGML->XHTML. I found it troublesome a while ago but didn't think it was worth changing because it might mess with people's CSS ... but at this point I think it's a good idea to use a consistent grouping for all the note types.

**Comment by jelovirt** [comment]
My preference would be to always output

```html
 <div class="note warning"><span class="warningtitle">Warning</span>  It's dangerous</div>
```

And have the CSS `.warningtitle` add the colon. That way you could also render the label on a separate line by just adding `display:block`.

The thing is, I don't know if we can change it at this stage.

In any case, the danger note type is a special case and we should preferably always output the same HTML for notes.

**Comment by raducoravu** [comment]
About the colon being added by the CSS, if we start doing that (which may not be OK for Arabic text) and the user searches in the browser page for "Warning:", will they find the text or not?

**Comment by jelovirt** [comment]
@raducoravu Browser find will match "Warning:".

I'm ok with keeping the colon as part of the generated label text, but it's again inconsistent with danger that has no colon and is in uppercase.

**Comment by raducoravu** [comment]
I would vote for "Danger:" which would be consistent with "Warning:". People can produce the upper case effect from the CSS for Danger if they choose to.

**Comment by jelovirt** [comment]
@raducoravu do you have interest in sending a PR for this?

**Comment by raducoravu** [comment]
This is not critical for us.

**Comment by robander** [comment]
Rather than making the colon part of the CSS - I'd be happy if we simply merged it into the generated text, so that "Warning" returned `Warning:` or `Avertissement :`

The main reason we had a distinct set of text for Colon was that in French, it appears with an extra space. I think that would be annoying to account for with CSS. Also: given that we tend to push new content to sit alongside a large set of old content, changing the CSS to add a colon would make the old content go from "Warning:" to "Warning::"

(Looking back - I much prefer the PDF2 string approach where the punctuation is just part of the variable, so that if 10 different strings end in a colon, we have those ten variables, rather than concatenating 10 variables (no colon) with one extra punctuation variable.

**Comment by robander** [comment]
Of course, thinking on it more, I realize that if customizations somewhere pull the "Warning" variable, those customizations would need to be updated as well. Probably no way to change this without a (potential) hit somewhere, I guess. But I still think that would take us to a better design, and the chances of an impact there seem minimal.

**Comment by jelovirt** [comment]
This has already been implemented in HTML5. The same modification was never made to XHTML.

**Comment by raducoravu** [comment]
Somehow I would have considered that most of the logic which outputs HTML would be done in common XSLTs both for XHTML and HTML5 outputs.

**Comment by jelovirt** [comment]
HTML5 and XHTML no longer have any share code, except common code for variable text and messages handling. The split was made because we can't change XHTML because of backwards compatibility and because want to improve HTML5. This enhancement to HTML5 can be ported to XHTML stylesheets if someone takes the task of maintaining the XHTML stylesheets.
