### ISSUE TITLE
DITA OT integrator should not look directly for resources in the basedir

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2612]
Let's say I have a separate build file located in some other folder which runs the DITA OT integrator:

      <project basedir="." name="bla" default="dist">
        <import file="d:/path/to/DITA-OT2.x/integrator.xml"></import>
          <target name="dist">
              <antcall target="strict"/>
          </target>
      </project>

it will fail with a message like:

            d:\projects\eXml\frameworks\dita\DITA-OT2.x\integrator.xml:46: C:\path/to/custom/buildDir/resources does not exist.

If we look inside the "integrator.xml" it should use in all places the "dita.dir" parameter but instead, in certain places like here:

          <fileset dir="${basedir}/resources">

 it uses the basedir parameter which usually points to the place where the ANT Java process has started.

**Comment by infotexture** [comment]
Could this be the root cause of #2583?

**Comment by raducoravu** [comment]
I had a similar impression when I had to decide if to add a new issue or not. I'm not sure though. The failure of the DITA OT integrator in this case is different than what @robander was experiencing.

**Comment by robander** [comment]
Strange - not sure that using `${basedir}` would be a cause for the other issue, since (without changing the content of the build file) I was able to get it to work. And, like my other plugins, I didn't set my own value for `basedir`. But ... hard to say. I was also running from the DITA-OT root directory so `basedir` should have matched `dita.dir`.
