### ISSUE TITLE
Image "scale" attribute is ignored

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#263]
Converted from [SourceForge issue 1852733](http://sourceforge.net/support/tracker.php?aid=1852733), submitted by su-laineyeo

The user can set a "scale" attribute on the <image> element. However, outputs always display  the image at 100% of actual size, regardless of the contents of the "scale" attribute.

**Comment by GrahamHannington** [comment]
> the bug is fixed in html

Is it?

Several years later, I'm using DITA-OT 3.3.4 to build HTML5 output.

My DITA source contains the following `<image>` element:

````
<image href="graphic.svg" placement="inline" scale="120"/>
````

Note:

- The `<image>` element refers to an external SVG file where the root `<svg>` element has `width` and `height` attributes
- The `<image>` element contains a `scale` attribute, but no `width` or `height` attribute

Given the comment "the bug is fixed in html", in the HTML5 output, I'd expected to see something like:

````
<img src="graphic.svg" width="n">
````

where n is the value specified by the `width` attribute of the `<svg>` element, scaled up by a multiplication factor of 1.2.

I understand that my expectation involves DITA-OT "delving" into the SVG file to get the specified width. And I realize that  might be expecting too much. But the statement "the bug is fixed in html" was unqualified. And this is what the `scale` attribute appears to offer; what it "says on the tin".

How is "the bug is fixed in html" true for this use case?

## About my use case

I export SVG from CorelDRAW, where I have drawn the objects at "actual size"—for example, with 10 pt text—appropriate for use in PDF output.

However, for HTML(5) output, that SVG image is "too small" in the context of the custom CSS of the surrounding HTML. The HTML CSS sets the body text font size to 16px, which is larger than the text in the SVG image. I want the text in the SVG image to be rendered at the same font size as the text outside of the image.

I have a workaround for this: I export the SVG from CorelDRAW "scaled-up" by a factor of 1.2. For PDF output, I use a `width` attribute on the DITA `<image>` element to set the SVG to its original, smaller, actual size.

But that's a faff. It would nice to have the alternative of exporting the SVG at its original actual size (as drawn in CorelDRAW, with 10 pt text, which works for PDF), and just specify `scale="120"` in the DITA `<image>` for HTML (e.g. `deliveryTarget="html"`), even though I'm not thrilled at the prospect of the resulting (to me, inelegant) `width` attribute in the HTML `<img>` element.

Interestingly, PDF output (at least, using Apache FOP; I haven't yet tested other XSL-FO processors, such as AH), unlike HTML output, _does_ honor the `scale` attribute in this context (external SVG file). So, instead of having to specify the actual absolute width of each image for PDF output, I can specify a constant `scale` attribute to scale down all scaled-up-for-HTML SVG images to their original "actual" size.

**Comment by raducoravu** [comment]
@GrahamHannington the SVG size detection in the DITA OT seems to have been added in DITA OT 2.3: https://github.com/dita-ot/dita-ot/issues/2230

 If you can reproduce the problem with the latest DITA OT 3.6.1 maybe you can add an issue for it, specifying in that issue details about how to reproduce the problem and attaching a sample SVG for tests.

Recently my colleague added and proposed a fix for this issue: https://github.com/dita-ot/dita-ot/issues/3785
It could be reproduced when the width and height specified in the SVG were not in pixels but in measuring units like in or cm.

**Comment by GrahamHannington** [comment]
> If you can reproduce the problem with the latest DITA OT 3.6.1 maybe you can add an issue for it, specifying in that issue details about how to reproduce the problem and attaching a sample SVG for tests.

Hi @raducoravu, always good to hear from you, thanks for the reply.

I've just tried this myself in DITA-OT 3.6.1. It works fine.

That is, building html5 output from the following DITA source:

````
<image href="graphic.svg" scale="200"/>
````

results in an HTML `<img>` element with appropriately scaled `width` and `height` attribute values; but only, as you point out (and as described in #3785), if the `<svg>` element `width` and `height` attribute values are numeric values only, with no trailing unit qualifier (not even `px`).

With apologies, I wasn't being entirely honest in my original post. I'm not using vanilla DITA-OT, I'm using DITA-OT with proprietary plugins. I suspect (I could be wrong), based on a cursory comparison of the DITA-OT XSLT and the plugin XSLT, that the plugin XSLT overrides the vanilla DITA-OT XSLT in this area, but lacks this functionality. I've initiated contact (indirect contact only; I have no direct contact) with the plugin developers.
