### ISSUE TITLE
Branch filtering prohibits key scopes to properly work

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2643]
I'm attaching a sample project, I'm testing with DITA OT 2.4.4.

[keyscopesAndBF.zip](https://github.com/dita-ot/dita-ot/files/885046/keyscopesAndBF.zip)

So I have a DITA Topic which looks like this:

            <!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
            <concept id="concept_qlr_spc_dt">
                <title>TEST <keyword keyref="product"/></title>
            </concept>

referenced twice in a DITA Map like this:

     <topichead navtitle="Product1Scope" keyscope="ks1">
      <keydef keys="product"><topicmeta><keywords><keyword>P1</keyword></keywords></topicmeta>
      </keydef>
      <topicref href="product.dita"/>  
     </topichead>
     <topichead navtitle="Product2Scope" keyscope="ks2">
      <ditavalref href="test.ditaval"/>
      <keydef keys="product"><topicmeta><keywords><keyword>P2</keyword></keywords></topicmeta></keydef>
      <topicref href="product.dita"/>
     </topichead>

The "test.ditaval" is an all-inclusive file filter.

When publishing to XHTML output for the "Product2Scope" the computed title of the HTML document generated from "product.dita" should be "TEST P2" but it is not properly computed.

The title seems to be properly computed if I remove the <ditavalref> from the second keyscope.

**Comment by SanFanDocu** [comment]
I get a correct output after adding a suffix to the ditavalref:

```
<ditavalref href="test.ditaval">
   <ditavalmeta>
      <dvrResourceSuffix>_P2</dvrResourceSuffix>
   </ditavalmeta>
</ditavalref>
```
However I do not understand the interrelation between suffix (used for file separation) and the correct handling of scoped key value.
Especially because the OT generates numbered suffixes automatically to separate the files correctly if no suffix is defined in the map.

Regardless the toolkit throws an irritating info massage for the multiple used key:
`[DOTJ045I][INFO] The key "product" is defined more than once in the same map file. The reference href="null" is ignored.`
