### ISSUE TITLE
Something about Ant

### ISSUE THREAD

**Issue by mironovalexey** [dita-ot/dita-ot#2675]
1. Perhaps it makes sense to add Ant [if/unless namespaces](https://ant.apache.org/manual/ifunless.html) to the [build project root](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/build_preprocess_template.xml#L9).
Since DITA-OT Ant version is 1.9.7, these namespaces automacally open the possibility to use if and unless attributes on tasks and inner elements.
Also Ant itself can be upgraded (http://ant.apache.org/antnews.html)  (release notes https://archive.apache.org/dist/ant/).

1. Despite the fact that there is [preprocess.mapref.skip property](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/build_preprocess_template.xml#L336), we have no chance to skip mapref resolution. Because the keyref task contains its own mapref resolution pipeline (do we really need to resolve them twice?), and that one does not respond to `preprocess.mapref.skip`.
It doesn't affect the result of full preprocessing, but mapref resolution is likely to break ditamap validation in some cases. So for partial preprocessing it may be useful to have a possibilty to switch it off.
With (1) it is quite simple:
```xml
<pipeline message="Resolve mapref in ditamap" taskname="mapref" unless:set="preprocess.mapref.skip">
```

3. The BranchFilterModule gives birth to a new (filtered) topics, which are [added to the .job.xml](https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/module/BranchFilterModule.java#L223). But the [branch-filter task](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/build_preprocess_template.xml#L219) doesn't rewrite file lists, they are [rewritten later - in the chunk task](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/build_preprocess_template.xml#L409). The chunk task execution depends on `preprocess.chunk.skip` property and can be skipped, then these new topics will never be exploded and processed.
I think it would be useful to add the following lines to the end of the branch-filter task.
```xml
<job-helper file="fullditatopic.list" property="fullditatopiclist"/>
<job-helper file="fullditamapandtopic.list" property="fullditamapandtopiclist"/>
```

(2) и (3) will reduce the number of dependencies between tasks, so they can be easily switched off without breaking the output. It's concered with [this discussion](https://github.com/dita-ot/dita-ot/pull/2672#issuecomment-298951918).

**Comment by jelovirt** [comment]
1) Adding ant-contrib has been discussed before, but thus far it has not been added because a longer term goal for the project is explicitly not add more functionality to Ant. By adding extensions to Ant to make the plugin configuration more of a programming language gives programmers move features to use in their configuration, but at the same time it makes it even more impossible to reduce the use of Ant. Ant is a completely useless programming language and we should not try to pretend we should use it just because we're stuck with it right now.

**Comment by mironovalexey** [comment]
@jelovirt Jarno, I am not talking about ant-contrib library. It is [core Ant feature](https://ant.apache.org/manual/ifunless.html) available since 1.9.1.

**Comment by jelovirt** [comment]
2) While we have a property to skip mapref processing, it's retained for historical reasons. Many parts of preprocessing rely on mapref processing, and if you want to disable it, then you have to disable also e.g. keyref processing.

**Comment by jelovirt** [comment]
@mironovalexey how nice of Ant to add features like that in minor releases. They clearly don't follow semver.

That I support, it's something Ant should have had from start.

**Comment by jelovirt** [comment]
3) File lists are deprecated and obsolete, they will be removed in 3.0. (Historical not, 3.0 was supposed to be released in 2016, but we pushed it back because we felt we didn't have enough features for 3.0. It's all PR, really.)

**Comment by jelovirt** [comment]
1) See  #2677

**Comment by robander** [comment]
General comments ... 

1. I'll probably start using some of those if/else functions in my own code now that I know about them. With it being a core part of Ant, I wouldn't mind seeing them in DITA-OT.
2. I'm a little nervous about the idea of "partial preprocessing". We've moved more and more to the idea of `preprocess` as a black box. Any one step might depend on steps that came before; we don't have a design goal that the steps should operate independently, or that you can skip a step that would otherwise need to be resolved. While you can still extend preprocess steps for advanced usage, the general design goal is that you throw DITA into `preprocess`, and then work with what comes out.
The `skip` properties are mostly historical, and were really intended to let you speed up processing when you know a step isn't used. For example, `preprocess.mapref.skip` property could let you avoid running `mapref` if the input is a topic, or if you know you don't have map references. But if you _do_ have map references, any step after that is free to assume they're resolved.
3. As @jelovirt indicated those list files are obsolete, so new extensions shouldn't be using them - the `.job.xml` file contains the "current" info about files.

**Comment by mironovalexey** [comment]
>1. I'll probably start using some of those if/else functions in my own code now that I know about them. With it being a core part of Ant, I wouldn't mind seeing them in DITA-OT.

These attributes are unavailable until we add the [corresponding namespace declarations](https://ant.apache.org/manual/ifunless.html) to the [build project root](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/build_preprocess_template.xml#L9).

```xml
<project xmlns:dita="http://dita-ot.sourceforge.net"
              xmlns:if="ant:if"
              xmlns:unless="ant:unless"
              name="ditaot-preprocess">
```

**Comment by jelovirt** [comment]
Closing this because if we need to add the `if` and `unless` namespaces into e.g. `build_preprocess_template.xml`, then the first RT to use those namespaces can add them.
