### ISSUE TITLE
Unresolved keyrefs to nested topics and elements

### ISSUE THREAD

**Issue by mironovalexey** [dita-ot/dita-ot#2691]
When keyref points to a non-root topic or element, [KeyrefParser](https://github.com/dita-ot/dita-ot/blob/develop/src/main/java/org/dita/dost/writer/KeyrefPaser.java#L363) does not process it correctly.

There are some errors in calculation of topic and element IDs and, as a result, we get the wrong `@href`attribute.

[test.tar.gz](https://github.com/dita-ot/dita-ot/files/1003628/test.tar.gz)

**Comment by jelovirt** [comment]
The [spec] says

>For references to topics, maps, and non-DITA resources, the value of the @keyref attribute is simply a key name (for example, keyref="topic-key").
>
> For references to non-topic elements within topics, the value of the @keyref attribute is a key name, a slash ("/"), and the ID of the target element (for example, keyref="topic-key/some-element-id".)

If we are the nitpick the spec, the latter case doesn't say it includes nested topics. However, I think the intent of the spec is to allow referencing nested topics with the slash syntax. @robander could you confirm?

The problem here is that the keyref doesn't contain the information whether the ID after the slash is a topic ID or an element ID (of the first topic that contains an element with that ID). In order to correctly process this, the `KeyrefPaser` would need to actually parse the target file and check which ID it is.

[spec]: http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part3-all-inclusive/archSpec/base/using-keys-for-addressing.html

**Comment by mironovalexey** [comment]
Ok, let's postpone the link to the nested topic for now and take a look at the keyref that points to the non-topic element of the nested topic.
**ditamap**
```xml
<keydef href="topic.dita#nestedtopic" keys="topic-fragment"/>
```
**source topic**
```xml
<xref keyref="topic-fragment/nestedtopic-section"/>
```
**preprocessed topic**
```xml
<xref  ... href="topic.dita#roottopic/nestedtopic-section" .../>
```

But it should be

**preprocessed topic**
```xml
<xref  ... href="topic.dita#nestedtopic/nestedtopic-section" .../>
```

**Comment by robander** [comment]
I see this was opened / closed before I even logged in today, but just wanted to follow up because much of this does depend on specification definitions.

@jelovirt was correct in the initial response that for any `<topic>` level element, the specification requires that you declare a key directly. With the `topickey/elementid` syntax, the `/elementid` portion can only be for a non-topic element referenced within a topic.

@mironovalexey was also correct in the last comment -- you can declare a key for a specific topic in a DITA document like `topic.dita#nestedtopic`. That key can be used to directly reference the nested topic; it can also be combined with `/elementid` inside of `@keyref` as a way to reference a non-topic element nested within the topic with `id="nestedtopic"`.
