### ISSUE TITLE
Wrong xref resolution of conrefed xrefs pointing to inner fragment ids

### ISSUE THREAD

**Issue by mironovalexey** [dita-ot/dita-ot#2715]
**topic1:**
```xml
...
<p conref="topic2.dita#topic2/myid">
...
```

**topic2:**
```xml
<concept id="topic2">
...
<p id="anchor">...</p>
...
<p id="myid"><xref="#topic2/anchor">THIS LINK IS BROKEN in topic1</xref></p>
...
<p id="myid-ok"><xref="topic2.dita#topic2/anchor">but this - is not</xref></p>
...
</concept>
```

[test.tar.gz](https://github.com/dita-ot/dita-ot/files/1047325/test.tar.gz)

It looks as if (A) links are resolved in the same way as (C) in [this table](http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part3-all-inclusive/archSpec/base/handling-xref-and-conref-within-topics.html#handling-xref-and-conref-within-topics).

**Comment by drmacro** [comment]
For the first xref, which only has a fragment ID, the processor should resolve it in the context of the containing topic (topic2, not topic1), which is what I think your expectation is--that the link as reflected in the conreffing element's location is a link back to concept "topic2". This is because the only thing the processor can know about the reference is its original source location. That is, except for "this topic" fragment identifiers, there is no conref-specific magic for address resolution in DITA.

So I agree that the behavior reported is a bug.

Note that if you use a "this topic" fragment ID ("#./elementid"), then the link is resolved in the context of the *referencing* element (topic1), not the context of source topic (topic2).

But I would argue that using conrefs in this way is very bad practice: that is, you should not be conreffing to elements in topics that are not resource-only topics (often called "warehouse topics"). Doing so creates a very tangled web. Adding xrefs with direct URI references adds additional complexity that will be hard to manage and will often produce either incorrect, confusing, or ambiguous results. All xrefs should use key references, but especially xrefs in re-used elements (other than xrefs that use "this topic" fragment IDs, of course).

For example, in the context of topic1, where there would be a link back to topic2, where you would then see the same paragraph you just came from, I would expect users to be very confused. 

One reason we added the "this topic" fragment ID feature in DITA 1.3 was so that you could reliably an unambigously conref elements containing fragment-id-only xrefs and have those always resolve to elements in the reference of the using topic. Without this feature there is *no way to do this*.

So while the OT's behavior in this case is incorrect per the spec, you should never construct your source in this way.

**Comment by Nikulinnn** [comment]
I agree that using conrefs in this way is a bad practice. 
But the point is, (A) and (C) links from the [table](http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part3-all-inclusive/archSpec/base/handling-xref-and-conref-within-topics.html#handling-xref-and-conref-within-topics) should be processed differently according to the specification. Previous versions of OT did not feature this bug. 
We have tons of documents and many of them have such conrefs. It's a good idea to rethink the architecture of each one of these documents. But doing this will take a lot of time. And since the current behavior is a actually a bug we hope that it can be fixed.

**Comment by mironovalexey** [comment]
@drmacro Dear Eliot, thank you for the detailed answer. I generally agree on "tangled web" argument, but sometimes one main document is the "fragment warehouse" for some related docs. The latest ones pull fragments from main doc and conrefed xrefs point back to main. The thing is, our team maintain a lot of such documents. Since DITA OT 1.x didn't have such a problem, I've submitted this issue.

**Comment by mironovalexey** [comment]
@jelovirt and other contributors, I need your help.

I am trying to fix the wrong xref resolution within the conrefed topics/elements. But there's one problem with tests - they contain a lot of incorrectly resolved links.

Here is an example. [This topic](https://github.com/dita-ot/dita-ot/blob/develop/src/test/resources/conref/src/lang-common0.dita) contains links to inner elements: 
[#href="topic/fig"](https://github.com/dita-ot/dita-ot/blob/develop/src/test/resources/conref/src/lang-common0.dita#L60), [#href="topic/table"](https://github.com/dita-ot/dita-ot/blob/develop/src/test/resources/conref/src/lang-common0.dita#L63). Being included to [another file](https://github.com/dita-ot/dita-ot/blob/develop/src/test/resources/conref/src/lang-common1.dita) they should point back to lang-common0.dita.
So the [expected result](https://github.com/dita-ot/dita-ot/blob/develop/src/test/resources/conref/exp/preprocess/lang-common1.dita#L74) for `#topic/fig `processing should be [href="lang-common0.dita#topic/fig"](url). And the generated text should be `Figure 1` (not [图 1](https://github.com/dita-ot/dita-ot/blob/develop/src/test/resources/conref/exp/preprocess/lang-common1.dita#L74)) since `lang-common0.dita/topic@xml-lang="en-us"`. I'm not sure if I should replace this text because of the meaning of this test.

The situation is exacerbated [here](https://github.com/dita-ot/dita-ot/tree/develop/src/test/resources/lang/src). All these files contain the same conrefed links.

What is the best way to proceed?
