### ISSUE TITLE
Upgrade to FOP 2.2

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2736]
Upgrade PDF2 FOP to use FOP 2.2. Current FOP dependency is to version 2.1

**Comment by Simalot** [comment]
Would it be possible to deliver the fontbox jar that is shipped with fop? I've had to copy it into our directories to be able to support OTF. We just moved our dev system to 2.2 the other day and have not seen any issues (and it resolved a few problems we had run into with 2.1).

**Comment by jelovirt** [comment]
Fontbox JAR is 1.5 MB, which I don't particularly like. But since it's bundled in the default FOP distribution, we should bundle it too.

**Comment by lagivan** [comment]
Why is this issue closed? It seems that the latest DITA-OT release 2.5.2 from August 2 still includes FOP 2.1.

**Comment by robander** [comment]
The 2.5.x hotfix releases only include bug fixes, rather than new features or major enhancements. Upgrading the embedded FOP is an enhancement rather than a bug.

For what it's worth - we are now using FOP 2.2 with the 2.5 release without any problems. @Simalot made that change for us just before this issue was opened, so he did it manually, but I think if you grab the [FOP directory](https://github.com/dita-ot/dita-ot/tree/develop/src/main/plugins/org.dita.pdf2.fop) from the develop branch, replace the directory in your 2.5 release, and re-run the plugin install, it should work fine. Of course you'd have to remember to repeat that any time you upgrade to a new 2.5.x hotfix.
