### ISSUE TITLE
Flagging with rev/revprop not working

### ISSUE THREAD

**Issue by chrizzbee** [dita-ot/dita-ot#2738]
- I believe this to be a bug, not a question about using DITA-OT.
- I read the [CONTRIBUTING][] file.

## Expected Behavior
In a ditamap, when using a ditaval file that has flagging defined with **revprop**, I expect that content profiled with the **@rev** attribute gets flagged/highlighted accordingly.

## Actual Behavior
I could not get this to work in the actual DOT 2.5.

## Steps to Reproduce

See Gist with the files involved:
https://gist.github.com/chrizzbee/bc904f8c701183acc10731898039cef3

I referenced the ditaval file directly in the map, below <title>. I then ran the transformation with oXygen and DOT 2.5. The two paras are not flagged. Also when I put the ditavalref into the topicref seems not to work.

Only when I use the ditaval file directly in the oXygen transformation scenario (together with the built-in DOT that comes with oXygen 19), it does work. If I do the same but with DOT 2.5 it does not work.

## Environment

* DITA-OT version: 
  2.5
* Operating system and version _(Linux, macOS, Windows)_: 
  Win7 x64
* How did you run DITA-OT?
   oXygen 19
* Transformation type _(HTML5, PDF, custom, etc.)_: 
  PDF, HTML

[CONTRIBUTING]: https://github.com/dita-ot/dita-ot/blob/develop/.github/CONTRIBUTING.md

**Comment by StanDoherty** [comment]
I had the same experience this past weekend . . . I kept receiving an error message about the default flagging parameter value not being valid (?).  The same files processed correctly in dita-ot-2.3.x and dita-ot-2.4.x.

**Comment by robander** [comment]
This sounds like it might be the same issue reported here, with a fix: https://github.com/dita-ot/dita-ot/pull/2749

**Comment by jelovirt** [comment]
@robander this is not #2749. The issue is that current flag processing doesn't support branch filtering. #2748 should fix this, at least for preprocess2. This needs to be checked for the current `develop` code and preprocess.

**Comment by shaneataylor** [comment]
Sounds related to #2576 as well.

**Comment by sethpark** [comment]
I'm having issues with 2.3.3 (I cant upgrade because my environment is limited to JRE 7). Here is the feedback I'm getting:

[preprocess_flag] Error on line 0
[preprocess_flag]   XTTE0505: Required item type of result of template ext-getrules is element(); supplied
[preprocess_flag]   value has item type document-node()
[preprocess_flag]   at xsl:call-template name="ext-gen-prop" (file:/ditaot/xsl/preprocess/flagImpl.xsl#428)
[preprocess_flag]   at xsl:call-template name="ext-getrules" (file:/ditaot/xsl/preprocess/flagImpl.xsl#433)
[preprocess_flag]   at xsl:call-template name="ext-getrules" (file:/ditaot/xsl/preprocess/flagImpl.xsl#376)
[preprocess_flag]   at xsl:call-template name="getrules" (file:/ditaot/xsl/preprocess/flagImpl.xsl#86)
[preprocess_flag]   at xsl:call-template name="getrules" (file:/ditaot/xsl/preprocess/flagImpl.xsl#86)
[preprocess_flag]   at xsl:apply-templates (file:/ditaot/xsl/preprocess/flagImpl.xsl#125)
[preprocess_flag]      processing /topic/title[1]/ph[1]
[preprocess_flag]   at xsl:apply-templates (file:/ditaot/xsl/preprocess/flagImpl.xsl#125)
[preprocess_flag]      processing /topic/title[1]
[preprocess_flag]   at xsl:apply-templates (file:/ditaot/xsl/preprocess/flagImpl.xsl#81)
[preprocess_flag]      processing /topic
[preprocess_flag] Failed to transform document: Required item type of result of template ext-getrules is element(); supplied value has item type document-node()
