### ISSUE TITLE
Close dita-ot-developer mailing list

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#2746]
Close down dita-ot-dev@googlegroups.com and redirect users to join Slack.

- [x] Send announcement to list
- [x] Remove links from documentation  dita-ot/docs#147
- [ ] Turn mailing list into read-only

**Comment by jelovirt** [comment]
Should we close down the mailing list, as in delete it, or just make it read-only?

**Comment by robander** [comment]
Vague preference for "make it read-only" because there are still links to it floating around, particularly in "about DITA-OT / how to participate" presentations. It might cause confusion or frustration if people follow those links and don't find anything - might be better to find the read-only list with a final message directing users to Slack.

**Comment by jelovirt** [comment]
Removed all rights to post to list, effectively turning it into a read-only list.
