### ISSUE TITLE
Branch filtering not working in OT 2.5.3?

### ISSUE THREAD

**Issue by juliovaz** [dita-ot/dita-ot#2798]
## Expected Behavior
I have a small project which I'm using as a POC of branch filtering. In this example, I use @conkeyref to bring in the content I require. Each branch has a different ditavalref which should filter out the content excluded by the @product value. 

## Actual Behavior
All of the content that should be filtered out on a particular branch is not being filtered out. Looking at the temp files, the content is brought in. Global filtering appears to be working. This fails even if I use a simple conref, so it appears as if filtering is not being invoked for each branch.
[branch_filter_example.zip](https://github.com/dita-ot/dita-ot/files/1337158/branch_filter_example.zip)

## Steps to Reproduce

1.  Unzip the attached test files
2.  Run dita -i branch_filter_example -f html5
3. Launch the resulting output file

## Environment

* DITA-OT version: 2.5.3
* Operating system and version: Windows 10
  _(Linux, macOS, Windows)_
* How did you run DITA-OT? oXygen 19 and command line
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_
* Transformation type: webhelp on oXygen, HTML5 in command line.
  _(HTML5, PDF, custom, etc.)_

**Comment by lionelmoi** [comment]
Hi ! It seems the `concept-reuse.dita` file is not included in your build.

**Comment by juliovaz** [comment]
[branch_filter_example.zip](https://github.com/dita-ot/dita-ot/files/1340995/branch_filter_example.zip)
Sorry about that. I've attached it to this reply.

**Comment by lionelmoi** [comment]
The behavior you are describing seems to be normal.

Branch-filtering happens before key resolution (see http://www.dita-ot.org/2.5/dev_ref/DITA-OTPreprocess.html). 

Your `<ditavalrefs>` elements are nested under `<topicrefs>` pointing to topics where no `@product` attributes are used. 

```
    <topicref href="first_branch.dita" keys="branch_1">
        <ditavalref href="product_a.ditaval"/>
        <topicref href="new_topic.dita" keys="new_topic"/>
        <topicref href="second_topic.dita"/>
    </topicref>
    [...]
```
Nothing is profiled in `first_branch.dita`

When [Branch-filtering](http://www.dita-ot.org/2.5/dev_ref/preprocess-branch-filter.html) happens nothing is filtered because nothing is profiled.

You profiled things in your keydef.
```
    <keydef keys="reusable" href="concept_reuse.dita"/>
```
But the `<ditavalref>` does not apply here.

There are several strategies to make it work.

The easiest one would be to profile in the `<topicref>`:
```
<concept id="new_topic">
    <title><ph conkeyref="reusable/filtered_product_name" product="producta"/><ph
            conkeyref="reusable/filtered_product_nameb" product="productb"/> Description</title>
    [...]
```

Another solution, maybe more elegant :


1. Nest the reused concept in each branch and add a `@keyscope ` to each branch.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE map PUBLIC "-//OASIS//DTD DITA 1.3 Map//EN" "map.dtd">
<map>
    <title>Branch filtering</title>
    <topicref href="first_branch.dita" keyscope="a">
        <ditavalref href="product_a.ditaval"/>
        <topicref href="new_topic.dita" keys="new_topic"/>
        <topicref href="second_topic.dita"/>
        <keydef keys="reusable" href="concept_reuse.dita"/>
    </topicref>
    <topicref href="first_branch.dita" keyscope="b">
        <ditavalref href="product_b.ditaval"/>
        <topicref href="new_topic.dita" keys="new_topic2"/>
        <topicref href="second_topic.dita"/>
        <keydef keys="reusable" href="concept_reuse.dita"/>
    </topicref>    
</map>
```
2. Nest all different version of the `filtered_product_name` under inside a `<ph >` element with the `@id`.
```
    <ph id="filtered_product_name">
        <ph product="producta">Product A</ph>
        <ph product="productb">Product B</ph>
    </ph
```
This way you only need  `<ph conkeyref="reusable/filtered_product_name"/>` to refer to the filtered product name.

Since the keydef is in the branch, it is filter during  [Branch-filtering](http://www.dita-ot.org/2.5/dev_ref/preprocess-branch-filter.html) and when the [Keyrefs are resolved](http://www.dita-ot.org/2.5/dev_ref/preprocess-keyref.html) only the filtered product name remains.

Working ditamap and file: [branch_filter_example-keyscopes.zip](https://github.com/dita-ot/dita-ot/files/1349300/branch_filter_example-keyscopes.zip)


There are other ways but I think I will make a pull-request in the doc repo rather than a response to this thread 😃

**Comment by jelovirt** [comment]
@lionelmoi do you feel this should be closed as invalid?

**Comment by juliovaz** [comment]
I didn't realize that the filtering processed before keys. Not what I
expected and forces a different strategy when it comes to how to set up
reusable content.

I would have expected the keys to get resolved, the content to come in and
then get filtered.

I want to avoid cluttering content with extraneous coding so I'll have to
consider a variation of the second recommendation.

Julio Vazquez
sent from Android

**Comment by drmacro** [comment]
The initial result of branch filtering is a new effective map reflecting the application of the ditavalRef elements (in particular, the synthesis of new branches, one for each child ditavalref within a branch, as well as modification of the key names, scopes, or effective resource URIs).

Thus, the effective key space cannot be determined until branch filtering is applied to the map and the effective map is constructed.

Once the effective map is constructed, then filtering will be applied to any referenced topics as defined by any branch-level ditavals and any global filtering conditions. Key definitions that are outside the scope of a filtered branch will not be affected by that branch's filtering.

If you want key definitions to be filtered and they are not in the navigation branches to which branch filtering is applied then you need to also need to filter the map branches that contain the key definitions.

**Comment by lionelmoi** [comment]
@jelovirt yep it's more of a doc issue

**Comment by juliovaz** [comment]
I appreciate the clarifications. I guess that I should have looked at the
OT documentation about the implementation as the spec doesn't address the
order of resolution.

Julio Vazquez
sent from Android

On Oct 2, 2017 10:00 PM, "Eliot Kimber" <notifications@github.com> wrote:

The initial result of branch filtering is a new effective map reflecting
the application of the ditavalRef elements (in particular, the synthesis of
new branches, one for each child ditavalref within a branch, as well as
modification of the key names, scopes, or effective resource URIs).

Thus, the effective key space cannot be determined until branch filtering
is applied to the map and the effective map is constructed.

Once the effective map is constructed, then filtering will be applied to
any referenced topics as defined by any branch-level ditavals and any
global filtering conditions. Key definitions that are outside the scope of
a filtered branch will not be affected by that branch's filtering.

If you want key definitions to be filtered and they are not in the
navigation branches to which branch filtering is applied then you need to
also need to filter the map branches that contain the key definitions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dita-ot/dita-ot/issues/2798#issuecomment-333717290>,
or mute
the thread
