### ISSUE TITLE
Handling of the "DOTX012W" error message

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2817]
If you look in the docs for this specific error message:
http://www.dita-ot.org/dev/user-guide/DITA-messages.html

it says that the message should not appear anymore. But it still does.

I'm attaching a sample project but I think you can obtain this easier if you a step conref from a standard DITA task to a DITA general task.

[testMessage.zip](https://github.com/dita-ot/dita-ot/files/1394534/testMessage.zip)

**Comment by xephon2** [comment]
I reported this here #2169, thought it would be my mistake.

**Comment by raducoravu** [comment]
Right, I saw that, as the documentation says that the message should no longer be given there is still stuff to figure out, at least to update the docs that the message would still be given for certain cases.

**Comment by infotexture** [comment]
Happy to revise the docs accordingly once we're certain whether it's the docs or code that need fixing.

Comments in #2169 seemed inconclusive in that regard.

**Comment by shaneataylor** [comment]
One use case that triggers this (at least in DITA-OT 2.3.1) is attempting to reuse a step between a task and troubleshooting topic. This is an important use case, as it's not uncommon for a troubleshooting step to duplicate a step that you should normally have performed in the task.

**Comment by robander** [comment]
This issue is kind of a pet peeve of mine, and this is a perfect example of why.

The specification created this rule about domains in order to prohibit ~clever~ unwise use of `@conref` that brings in something you shouldn't have. I'm fairly confident that this case has _almost_ never been encountered or prohibited; instead, the rule only ends up breaking valid cases like this one.

That said ... with 3.0, I'm no longer able to get this message with task pulling steps from troubleshooting or vice-versa (with html5 and `preprocess` or with pdf and `preprocess2`)
[2817.zip](https://github.com/dita-ot/dita-ot/files/1518315/2817.zip)

**Comment by robander** [comment]
But I am able to reproduce with 3.0 using the samples from @raducoravu in the original report. So perhaps disregard my previous post...
