### ISSUE TITLE
Language variables for note labels in custom plug-in are ignored

### ISSUE THREAD

**Issue by annette-b** [dita-ot/dita-ot#2848]
My plug-ins were created with DITA OT 1.8.5 and I recently refactored them to work with DITA OT 2.x. (I use the DITA OT version bundled with Oxygen 19.1 but located outside Oyxgen installation folder, in a shared directory.). With DITA OT 1.8.5, I could overwrite the default labels for notes in the variables files of my plug-ins. Now, with DITA OT 2.x, it no longer works. strings from common\strings-fr-fr.xml (for example) are used instead.
If I comment out the corresponding strings in strings-fr-fr.xml, then the variables of my plug-in are correctly picked up. 
Note that the images customized for the warning notes are correctly picked up from my plug-in as well as variables for Table of contents title, Index title, bullet lists, etc. It seems that the issue is only on peril note labels.

## Steps to Reproduce

1. Customize language variables such as `<variable id="Important">Information</variable>` in custom_plugin\cfg\common\vars\fr.xml
2. Run the transformation scenario to output a French PDF. 
= Warning note of type "Important" is still "Important" and not "Information".
3. Comment out `<!--<str name="Important">Important</str>-->` in DITA_OT\xsl\common\strings-fr-fr.xml
= Warning note of type "Important" appears as "Information".

Expected: we shouldn't have to comment out strings to define custom labels.

## Environment

* DITA-OT version: 2.5
* Operating system and version: Windows 7 SP1
* How did you run DITA-OT? transformation scenario in oXygen
* Transformation type: PDF

**Comment by xephon2** [comment]
Hi @annette-b, you should follow the [migration instructions](http://www.dita-ot.org/3.0/dev_ref/migration.html). I assume that you still use the `insertVariable` template instead of the `getVariable` template, see [Migrating to release 2.1](http://www.dita-ot.org/dev/dev_ref/migrating-to-2.1.html).

**Comment by annette-b** [comment]
This is not a template that I have customized. Regarding note labels, I rely on the placeNoteContent template in topic.xsl. My only customization (for this) is in the language variable files.
(And I did replace insertVariable template with getVariable template.)

**Comment by xephon2** [comment]
Could you please paste your `plugin.xml`?

**Comment by annette-b** [comment]
Here it is (I replaced the name of the company with xxxxxxxx):
```
<?xml version='1.0' encoding='UTF-8'?>
<plugin id="com.xxxxxxxx.custpdf_DITAOT2x">
  <require plugin="org.dita.pdf2" />
  <feature extension="dita.conductor.transtype.check" value="custpdf" />
  <feature extension="dita.transtype.print" value="custpdf" />
  <feature extension="dita.conductor.target.relative" file="integrator.xml" />
</plugin>
```

**Comment by xephon2** [comment]
You should use the `dita.xsl.strings` extension point, as it is explained in [Customizing generated text](http://www.dita-ot.org/dev/dev_ref/plugin-addgeneratedtext.html). Because your strings are used, if you comment out the existing strings, it seems that your strings do not correctly override the defaults. And this is probably because you did not use the extension point.

**Comment by annette-b** [comment]
Thanks @xephon2 . I'll try this. 
However I'm wondering why the mechanism that used to work in DITA OT 1.8.5 no longer works, and only for note labels.

**Comment by xephon2** [comment]
@annette-b this cannot be answered without debugging your plugin. Probably you define a `configuration.dir` in your `integrator.xml`, as it is explained in the 1.8.5 docs ([Customizing PDF output](http://www.dita-ot.org/1.8/readme/dita2pdf-customization.html)). Things have changed from **1.8.5** to **2.x**.

**Comment by xephon2** [comment]
@robander, this should probably be tagged with `support` and should be closed.

**Comment by annette-b** [comment]
Hi again. I looked at the strings customization and I don't understand why we have two ways to translate strings. It seems that changes in the commons/vars folder are still supported: http://www.dita-ot.org/dev/dev_ref/pdf-plugin-structure.html but then when should we prefer one method over the other? How do they work together? The variables IDs have not changed between 1.8.5 and 2.x, so it's hard to see why some are picked up and others are not.
This may not be the best place to ask this. I can send my questions to the DITA yahoo mailing list, if it's more appropriate.

**Comment by xephon2** [comment]
Yes, asking at the [dita-users](https://groups.yahoo.com/neo/groups/dita-users/info) mailing list is preferred. My personal opinion (not official DITA-OT opinion) is, that the [Customization folder approach](http://www.dita-ot.org/dev/dev_ref/pdf-customization-approaches.html) is a design issue. You always start small, then your plugin grows and gets more and more complex and then this approach will fail. And because it is not easier to follow the Customization folder approach, I'd always recommend to follow the instructions given at [PDF plug-in structure](http://www.dita-ot.org/dev/dev_ref/pdf-plugin-structure.html). There is a very good book written by Leigh White about PDF plugins: [DITA for Print: A DITA Open Toolkit Workbook, Second Edition](https://www.amazon.de/dp/1937434540/ref=cm_sw_em_r_mt_dp_RZefAb5WFT789). Without looking at your code, I cannot help you any better. Sorry!

**Comment by robander** [comment]
@xephon2 I missed your tag earlier while I was out of the office - thanks for helping out with this one. I don't have much to add except that _in general_, the `dita.xsl.strings` point you mentioned is the best way to go. That overrides strings globally, so the only time it doesn't work is if you want (for example) to have one PDF style use "Important" and another use "Hey this is really important". In that case, a configuration directory within a plugin should give you what you need.
