### ISSUE TITLE
--logfile does not work with "equals" form

### ISSUE THREAD

**Issue by xephon2** [dita-ot/dita-ot#2849]
## Expected Behavior
It should work.

## Actual Behavior

**(1)** Executing the **dita** command without `--logfile` works, this is good 😄 .

```shell
[stefan@vaio logfile-test]$ dita --input map.ditamap --format pdf
```

**(2)** Executing with `--logfile=foo.log` does not work, but it _should_, see [Building output using the dita command](https://www.dita-ot.org/3.0/topics/build-using-dita-command.html).

```shell
[stefan@vaio logfile-test]$ dita --input map.ditamap --format pdf --logfile=foo.log
Error: Error: Unknown argument: /home/stefan/workspace/DITA/dita-ot/build.xml
Usage: dita -i <file> -f <name> [options]
   or: dita --propertyfile=<file> [options]
   or: dita --install [=<file>]
   or: dita --uninstall <id>
   or: dita --help
   or: dita --version
```

**(3)** Executing without the `=` char between parameter and value also works, but it _should not work_.

```shell
[stefan@vaio logfile-test]$ dita --input map.ditamap --format pdf --logfile foo.log
```

## Environment

* DITA-OT version: **3.0**
* Operating system and version: **Manjaro Linux**
* How did you run DITA-OT? **dita** command
* Transformation type: does not matter

**Comment by infotexture** [comment]
Reproduced on macOS 10.12.6 w/ latest code from `develop` @ 4cee2e4, so the issue is not specific to Linux. As noted in #2968, the `-l` short option works fine, so the error appears specific to the long-form option. 

Also confirmed that removing the equals sign between the option and the filename per **(3)** above indeed allows the build to complete successfully: `--logfile logfile.txt`, so it looks like the implementation should be updated to agree with the CLI help & docs descriptions.

**Comment by dflock** [comment]
Still a problem as of today with 3.3.1 - same error, same problem - docs here still say `--logfile=...`: https://www.dita-ot.org/dev/topics/build-using-dita-command.html

**Comment by infotexture** [comment]
@jelovirt Any preference on how to best resolve this?

With the changes in #3245, the other long-form options all support the "equals" form, so it looks like it would be best to adjust the implementation to ensure the same in `--logfile` for consistency.

If that's not likely to happen soon, I'd send a PR to align the CLI help & docs to reflect the current implementation.
