### ISSUE TITLE
Correct translations for various kind of notes in German

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2864]
Feedback from one of our end users about the various kind of static texts used for various note `@type` values :

        strings-de-de.xml and strings-de-ch.xml have a serious translation error.
      'Danger' should be trasnlated as 'GEFAHR', not 'Vorsicht'. 

Basically their translation agency suggested:

Danger->Gefahr
Warning->Warnung
Caution->Vorsicht
Important->Achtung
Note/Notice->Hinweis

**Comment by raducoravu** [comment]
I asked @xephon2 for a second opinion, this is his feedback:

            short answer: Yes, that's correct, the text is wrong and should be
            changed, as suggested.
            
            much longer answer:
            This is something, why I have problems to take the whole technical
            documentation environment seriously in general. This label is not wrong
            in the meaning of "the translation is wrong". It is wrong, because it
            violates standards. The most important standard here is the american
            ANSI Z535.4. You can buy the norm from the ANSI. There are also other
            normative documents from the ISO, but most Germans look at the ANSI
            Z535.4 for the labels. On page 25 (Annex D) you'll find a list of
            labels in multiple languages, also "GEFAHR"<->"DANGER".
            The whole appearance of safety notes is normed by ANSI and ISO. So
            changing a single label does not fix the safety note problem, because
            the safety note will stay "wrong". The whole safety note topic should
            be refactored in the toolkit. This is probably the most important
            topic, why Germans and others would never consider using DITA/DITA-OT
            in a machinery context. It's really primarily because of their invalid
            safety notes, because everybody is afraid of creating something unsafe
            and than getting the punishment.

**Comment by raducoravu** [comment]
I found a copy of the "ANSI Z535.4" on the web and indeed it has in Annex D a table where it explains how each label should be translated to German and to other languages.

**Comment by SanFanDocu** [comment]
Agree @xephon2: For medical device sector we are using ANSI Z535.4 for all languages.

But there is one undocumented exception for German: 

Most professionals (machine/medical industry) recommend to use `Achtung` for the note/notice level instead of the 1:1 translation `Hinweis`. 
The professionals say that `Hinweis` does not represent the risk level  "product damage" correctly defined by ANSI for `notice`. 
`Hinweis` would be understood as "good to know but not important" (similar to `tip`).

If you follow this recommondation you have to translate:
`Danger->Gefahr`
`Warning->Warnung`
`Caution->Vorsicht`
`Important->Wichtig` (1:1 translation, no standardization available) 
`Note/Notice->Achtung`

In our company we divide the similar warning levels note/notice into
`Notice->Achtung`
`Note->Hinweis`
This is our own rule to keep the `Hinweis` level to represent information below product damage risk level which is not defined by ANSI.

**Comment by robander** [comment]
Don't have a strong feeling on this one - the labels provided today are the ones we've been using for years, except that we've never used the new(ish) `type="notice"`. I'm sure that there was no previous attention to the value we use today as `notice`.

**Comment by raducoravu** [comment]
@xephon2 fancy to make a pull request for this?

**Comment by xephon2** [comment]
@raducoravu Never was fancier before #2871

**Comment by raducoravu** [comment]
👍

**Comment by raducoravu** [comment]
Fixed by @xephon2 in #2871
