### ISSUE TITLE
Add "Related terms" category for related links to glossentries

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2872]
When the relationship table defines links between a topic and others, those links are automatically grouped in the published output at the end of the topic HTML content in various categories: "Related topics", "Related tasks", "Related concepts" and "Related information".
Our particular end user would like to have a particular category for related links to glossentry topic types, category which could be called "Related terms". 

So for example in the translation files like "xsl/common/strings-en-us.xml" we would need a new mapping like:

          <str name="Related glossentrys">Related terms</str>  

which would be used in the XSLTs for HTML and PDF based outputs similar to the ones for concepts, tasks and references for the category labels when a topic has related links to glossary entries.

**Comment by xephon2** [comment]
This requirement should be generalized. `<glossentry>` is just another specialized DITA topic. We need an easy to configure mechanism based on conventions, how users can quickly set this up for specialized topic types.

**Comment by robander** [comment]
It _should_ be possible to do this by putting a column header on the reltable column. But, this doesn't seem to be working for me now. When I put the title in the column using `@navtitle` I get the issue reported in #2432. If I add a dummy `@href` to that reference the build continues but I get an ambiguous rule match for the glossary topic. If I use `<title>` inside the column instead, I also get the ambiguous rule match. In either case, my two glossary entries end up under "Related concepts".

So - that _should_ be the easy configuration mechanism, because it's part of the spec and _should_ work across implementations, it just ... doesn't seem to work now, or else I'm making some obvious error in the sample I quickly created.

All that being said - @raducoravu I wonder, were you asking for DITA-OT to add explicit / universal grouping support for glossary terms along with task/concept/reference, as opposed to "some ability to make new groups"?

**Comment by robander** [comment]
Ahh update on the earlier response -- the `<relcolspec>` approach _is_ working when:

1. I fix the `$href` bug so that you can just specify a title
1. I fix the ambiguous rule message (for HTML5, that issue doesn't exist for XHTML)
1. I add a title to _every_ relcolspec -- if I only add to some of the columns, either the headers are ignored or links are ignored; if I add to all columns, headers are used and links appear properly

**Comment by raducoravu** [comment]
Similar to what's done for tasks/concepts we could have also had out of the box support for naming the category "Related terms" when the relcolspec had a glossentry type:

           <relcolspec type="glossentry"/> 

But I think it's great that the generic way of naming categories now works because from what I understand customers can now name the categories whatever they want without the need of XSLT customizations.

**Comment by robander** [comment]
> But I think it's great that the generic way of naming categories now works because from what I understand customers can now name the categories whatever they want without the need of XSLT customizations.

Yes -- with the addition that it works today if (and only if) you:

1. You follow the pattern of having each topic type in its own reltable column (this is a good practice but not required), and
1. Have titles for every column (you can't use the default "Related reference" but also add your own "Related terms") -- I've got a fix for that in #2873, it should use the default for known items if you don't customize
