### ISSUE TITLE
Appending @outputclass to the colspec element results in a validation error

### ISSUE THREAD

**Issue by ArugaAnt** [dita-ot/dita-ot#2915]
## Expected Behavior
Append @outputclass to the colspec element.

In the specification of DITA 1.3, it is defined that it is possible to add @outputclass to the colspec element.
http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part3-all-inclusive/langRef/base/colspec.html#colspec

## Actual Behavior
Appending @outputclass to the colspec element results in a validation error.

## Possible Solution
Correct the DTD according to the specification of DITA 1.3

## Environment
* DITA-OT version:3.0.3
* Operating system and version:Windows10
* How did you run DITA-OT?:oXygen
* Transformation type:HTML5

**Comment by jelovirt** [comment]
This is a bug in OASIS DTDs, ping @robander

**Comment by drmacro** [comment]
I think this is an error in the spec. colspec has never allowed the @outputclass attribute and definitely does not in DITA 1.3. Thus the reference to @outputclass should not be in the reference entry topic for colspec. Robert or I can bring this to the TC for possible correction in a future errata to DITA 1.3.

In addition, it's difficult to see how specifying @outputclass on colspec could ever have any value since colspec only exists to define the geometry of the columns and otherwise would not contribute to any normal presentation of the table (which is, I'm sure, why @outputclass was never included on it in the first place).

In addition, the 1.3 specification says that the RNGs are the normative definition of the vocabulary:

"While the files should define the same DITA elements, the RELAX NG grammars are normative if there is a discrepancy."

So while the text of the spec is in error in saying that @outputclass is allowed on colspec the grammars are correct in not allowing it.

**Comment by robander** [comment]
Eliot is correct - this is a bug in the DITA 1.3 specification, which must have come in when all of the attribute sections were redesigned from the 1.2 specification model. The attribute was not there in 1.2 and there was no intention of adding it to 1.3.

**Comment by robander** [comment]
Marking this closed - the grammar files are those distributed by OASIS. Regardless of which is in error (the specification or the grammar), it was not intended to be present, and at this point OASIS is not going to add the attribute in the official grammar files.
