### ISSUE TITLE
Index collection fails if title is wrapped in ph indexterm

### ISSUE THREAD

**Issue by Enigma644** [dita-ot/dita-ot#2940]
## Expected Behavior

Trying to do HTML Help output to CHM file.

## Actual Behavior

No CHM produced, NullPointerException in log.

## Possible Solution

Seems to be something to do with indexterm being in the title and also being in the body.

## Steps to Reproduce

[testFiles.zip](https://github.com/dita-ot/dita-ot/files/1943570/testFiles.zip)
1. Unzip.
2. Correct paths in bat for your setup.
3. Run makeCHM.bat

## Copy of the error message, log file or stack trace

 [pipeline] file:/C:/Users/James/Desktop/swap/DOTK/input/TestTopic.dita:3:146: [DOTX037W][WARN]: No title found for this document; using "***" in XHTML title bar. 
Error: The following error occurred while executing this line:
C:\Stuff\DITA-OT-3.0.3\plugins\org.dita.htmlhelp\build_dita2htmlhelp.xml:90: java.lang.NullPointerException

## Environment

* DITA-OT version:3.0.3
* Operating system and version: Winx64
* How did you run DITA-OT?
Call "C:\Stuff\DITA-OT-3.0.3\bin\dita.bat" /transtype:htmlhelp -i="C:\Users\James\Desktop\swap\DOTK\input\map.ditamap" -o="C:\Users\James\Desktop\swap\DOTK\output" -l="C:\Users\James\Desktop\swap\DOTK\log.log"
* Transformation type:
htmlhelp

**Comment by Enigma644** [comment]
Yes, the whole title. It was a convenient way to index the topic as I'm also doing args.indexshow=yes

**Comment by Enigma644** [comment]
Also worth noting is that if a section title is fully wrapped in <ph><indexterm>, then it is missing from the output and you just get a  comment.

As a workaround, I'm currently putting a single space after the indexterm, as this makes it work.

**Comment by drmacro** [comment]
I would suggest that using "indexshow" to get around the general need to have index term markup in addition to the text that warrants the index entry is bad practice.

It will only produce appropriate results when all the index entries are identical to the base text, which cannot always be the case generally.

If you're indexing in the topic title the better markup would be to put the index entry in the topic prolog.

**Comment by Enigma644** [comment]
All my index terms are in the base text and adding markup there is a far better user experience that having a mess of terms in the prolog. Also, marking up inline means that index terms are already there when sections are re-used between documents.

**Comment by robander** [comment]
I have to say that like @drmacro this markup makes me very nervous, even while I agree that the code should never crash with a null pointer error.

I can understand how you arrived at it - as you say, reused sections get indexed automatically, and it's easy to select the text and surround it with the term. While index terms are not intended to be rendered with the content, the `args.indexshow` parameter is a clever way to get around that. That said ... I think over time you'll run into more problems, much like the one you saw with section titles treated as missing.

The `args.indexshow` parameter was created to help with content reviews -- so that reviewers could see exactly where the terms are defined while also reviewing the final publication. As such, it only results in "shown" terms when they are in the topic content / when they are pulled from the prolog to show as part of the content. There are a lot of other places where we explicitly ignore index terms -- those processes will not be updated to say "ignore except with indexshow", because that's not what the parameter is intended for. Offhand I can think of a few places where that would happen, and you've already encountered some of them:

- Section titles -- if the title is empty, generating an empty heading results in something like `<h2/>` that a lot of browsers _really_ don't handle well. That's why we check for any text content or [element content that is not hidden] before creating the heading.
- Topic titles (in a TOC, in the HTML `<title>` that appears with the browser window, in PDF bookmarks, in running headers and footers, etc): all of these will be processed in a way that drops index terms
- Cross references -- any time you cross reference a topic (or anything really), index terms will be ignored when link text is generated
- Any other location where content is pulled, as opposed to reused-with-conref, such as when short descriptions are pulled for link previews

I'm sure there are more, those are just some of the most common. 

Rather than the existing parameter that shows index terms in the content, it seems like what you'd really need here is a parameter that means "treat index terms as both an index term and also treat them as part of the content flow". 

The easiest way I can think of to get processing like that to work -- and also avoid the various issues you're seeing now -- would be to add a custom step (early) in the preprocess that takes your title content and treats it as both inline and as an index. The benefit to that approach is that you can keep editing as you are now, but also avoid all of the issues I listed above, along with all of the other ones I'm missing, _and also any future code that pulls content without pulling index terms._ A step like that could really go from either direction. For example, something like one of these:

- If every title should be indexed: when you find a title that does not have an indexterm, generate an indexterm in that title with the same contents as the title
- Or, if you find a title that _only_ has an indexterm, keep that term while also copying the contents into the title itself
- Or, if you find a title that has content and an _empty_ index term, copy the contents into that term
- I'm sure there are several options like this, all of which would depend on your overall content structure / what's easiest to manage when editing.

**Comment by robander** [comment]
The NPE in this issue is not specific to `htmlhelp` -- it will show up with the same content for any transform type that makes use of `org.dita.dost.module.IndexTermExtractModule` (including `eclipsehelp`).

When building Eclipse or HTML help, there is already a warning that the topic contains no title and that the `<title>` element in HTML is set to `***`. We should use the same default in the index collection when the term needs to be associated with a topic title. This will fix the NPE and allow builds to complete.

I don't expect to add any additional support around `INDEXSHOW`, for the reasons Eliot and I gave above.

**Comment by robander** [comment]
Updated the title to indicate that this issue is not specific to HTML Help.

**Comment by robander** [comment]
Fixed the NPE for 3.1.2 as described above.
