### ISSUE TITLE
Topic with conref to self cannot be published to XHTML or HTML5

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#2948]
If you take a DITA topic like this:

            <!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
            <topic id="my_topic">
                <title>My topic</title>
                <body>
                    <p id="pid">test</p>
                    <p conref="#my_topic/pid"/>
                </body>
            </topic>

and publish it to XHTML or HTML 5 (without any DITA Map) using DITA OT 2.x or 3.0.3, the output folder will contain no HTML document.
Possibly this occurs somehow because the topic starts being considered a resource-only topic.

**Comment by robander** [comment]
Repropduced with latest code.

When I check the `.job.xml` file, it is marked as resource-only:
```
<file src="file:/C:/DITA-OT/TESTGITHUB/2948/2948.dita" 
     uri="2948.dita" path="2948.dita" 
     result="file:/C:/DITA-OT/TESTGITHUB/2948/2948.dita" 
     format="dita" has-conref="true" resource-only="true" 
     target="true" input="true">
```

When I create a map and only reference this topic, it is generated as expected.

**Comment by jelovirt** [comment]
Our integration tests have very few tests that publish topics, so no wonder bug like this has not been found before.

**Comment by robander** [comment]
Right.

The problem here is that 

- When we find the conref, the topic goes into the `conrefTargets` set
- It's not listed in a map, so it never gets added to `normalProcessingRole` set
- Anything in the conref set but *not* in the normal role set is treated as a `pureConrefTarget`, and added to resource-only

I tried to adjust lists in the reader, but that got complicated (if root element is topic AND this is the input file then add it to the normal role set?) ... realized it's easier and safter after everything is processed, if the `rootFile` is marked as resource only, remove it from that set. I can imagine other features might result in a file being added to that set, but the root input file is never resource-only, so should always be removed if it ended up there.
