### ISSUE TITLE
NPE when adding a keyref on a DITA element which does not allow one

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3008]
This is also a question related to the DITA 1.3 specs, so maybe @robander can help a little bit here.
Let's say someone creates a DITA DTD specialization and adds a new element which extends the DITA <p> element. But their new element is allowed to have the keyref attribute on it. The DITA OT processing only expects the keyref attribute to be defined on specific DITA elements, see "org.dita.dost.writer.KeyrefPaser.keyrefInfos". But I do not see anything in the DITA 1.3 specification stating that only certain element types can have the keyref attribute specified on them.
So right now the publishing breaks with a NullPointerException when you have a DITA element with an unexpected keyref set on it.

As a quick experiment, let's say that inside a DITA topic somewhere in a paragraph I add this non-existing DITA element:

       <booboo class="- topic/p topic/booboo " keyref="bulb"/>

and then I publish to HTML5 setting the "validate=false" parameter, I will get a NullPointerException reported with DITA OT 3.1 (but also with older DITA OTs):

	org.dita.base\build_preprocess.xml:280: java.lang.NullPointerException
	at org.dita.dost.writer.KeyrefPaser.processElement(KeyrefPaser.java:478)
	at org.dita.dost.writer.KeyrefPaser.startElement(KeyrefPaser.java:468)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(Unknown Source)
	at org.dita.dost.writer.TopicFragmentFilter.startElement(TopicFragmentFilter.java:79)
	at org.dita.dost.writer.ConkeyrefFilter.startElement(ConkeyrefFilter.java:83)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)

**Comment by robander** [comment]
Re: the specification and adding `@keyref` -- to comply with the spec, DITA requires that any specialized element have "A set of attributes that are the same or a subset of those of the element from which it was specialized". Per that rule, adding `@keyref` to a specialized paragraph is not valid, because the new attribute set is not the same or a subset of those on paragraphs: http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/archSpec/base/specialization-rules-elements.html

You could get into edge cases where specialized attributes are available on `<booboo>` but also constrained to not appear on `<p>`, but in that case the attributes would have to be based on `@props` or `@base`. I don't think it was ever considered necessary to say "Do not give your specialized attributes the name `@keyref`"; that said, if you did so, it would still be a specialization of those attributes and should not pick up the usual keyref behavior. (It would also be hard to implement if following the other spec rules - you'd need a lot of constraint modules to avoid declaring `@keyref` twice on everything that has it.)

As far as the NPE goes - that should still be considered a bug because any NPE shows something wasn't handled properly, but in this case the proper behavior should just be to ignore `@keyref` on anything not in that list from `org.dita.dost.writer.KeyrefPaser.keyrefInfos`.

**Comment by robander** [comment]
Test doc to reproduce, building with `-Dvalidate=false`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//IBM//DTD DITA IBM Topic//EN"  "ibm-topic.dtd">
<topic id="badkeyref" xml:lang="en-us" class="- topic/topic ">
<title class="- topic/title ">Invalid keyref</title>
<body class="- topic/body ">
<p class="- topic/p " keyref="invalid">Paragraph</p>
</body>
</topic>
```
