### ISSUE TITLE
Must set absolute value for args.cssroot to get CSS included in html5 and xhtml

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#3016]
## Expected Behavior

specifying only `args.css` with an absolute path and `no` value for `args.cssroot` should result in the CSS being included in HTML output when `args.copycss` is `yes`

## Actual Behavior

Final value of `args.css.file` is just the CSS filename so copying of CSS fails.

## Possible Solution

Not sure how best to fix this since it depends on whether or not `args.css` is or is not absolute,
but the bug is

```xml
<basename property="args.css.file.temp" file="${args.css}"/>
```
in `build_dita2html5_template.xml` (and in `org.dita.xhtml/build_general_template.xml`).

As this assumes that `args.cssroot` is also set.

## Steps to Reproduce

1. Set `args.css` to the absolute path of the CSS file
2. Do not set `args.cssroot` to a value
3. Set `args.copycss` to `true`
4. Generate HTML5
5. Observe that CSS was not copied and not referenced in generated HTML

## Environment

* DITA-OT version: 2.5.4
* Operating system and version: macos
* How did you run DITA-OT? dita command
* Transformation type: html5

**Comment by robander** [comment]
Pretty sure this goes back to the original mess of options built up around CSS parameters, which goes back to pre-DITA-OT beta days, which goes back to tools that existed before DITA-OT. When something didn't work, typically another parameter was added to handle the problem rather than fixing the problem (because fixing the problem also meant breaking existing builds). The result is kind of a mess.

In the early days `args.css` could *only* be a file name, but I see that the documentation now allows either the file name or an absolute path, so I assume the absolute path worked at some point. It's not something I've used recently so I'm not sure what might have changed, or when...

**Comment by drmacro** [comment]
I suspect that most users either just used args.cssroot from the start or they had multiple CSS files and so had to use it.

In my case the CSS is set in the plugin so there didn't seem to be a reason to use two parameters where one should work.

I can try to puzzle out the best solution at some point but it's not immediately obvious from the Ant code what that is.

**Comment by larrykollar** [comment]
Indeed, `args.cssroot` requires a full path to work. But [the documentation](https://www.dita-ot.org/3.1/parameters/parameters-html5.html) says the cssroot is relative to the location of the input map. So one would *expect*, if the map and CSS files are in the same directory, that `args.cssroot` should default to "."

Setting `args.cssroot` to "." (sans quotes, of course) makes no difference. If you want your custom CSS included, you have to specify the full path.

**Comment by infotexture** [comment]
Testing this again today, I verified what @larrykollar points out above: custom CSS **is** included when an **absolute** value is set for `cssroot`.

Testing on the latest docs source files, these command options produce the desired results  
_(note the use of `$PWD` to force an absolute path in `args.cssroot` & `args.hdr`)_:

```bash
dita --input=userguide.ditamap --format=html5 \
     --args.copycss=yes \
     --args.csspath=css \
     --args.cssroot=$PWD/resources \
     --args.css=dita-ot-doc.css \
     --args.gen.task.lbl=YES \
     --args.hdr=$PWD/resources/header.xml \
     --args.html5.toc=toc \
     --nav-toc=partial
```

The docs assume this is treated as relative

> The value you enter here will be interpreted relative to the location of the input map file

but with relative values for `args.cssroot` (either `./resources` or just `resources`), no CSS is included.

Though we could certainly adjust the docs to work around the issue by demanding an absolute path for `cssroot`, I assume this is a regression that would better be fixed in the underlying code.

@jelovirt @robander Any preferences?

**Comment by infotexture** [comment]
Reported earlier in related issue #2965, in which @raducoravu remarks:

> it seems to be considered relative to the folder in which the process started

**Comment by robander** [comment]
Before adding anything I should say ... as I've said elsewhere ... these parameters are all kind of a mess, together they support all kinds of functionality but as a result it can be hard + use too many parameters to just do the simple stuff. Given that I've been using some versions of these parameters since DITA-OT 1.0, so I'm more or less used to them, I'm probably also not the best one to say what the most _usable_ solution is or should be. So with that in mind...

> The challenge I see is that if we change the code so that `args.cssroot` will always be converted to an absolute path before handed forward is that people will then expect that to occur everywhere.

Yeah, some people probably will, but ... I'm not sure if we should worry about that. We deprecated / removed the old Java command line, and everything in our docs / presentations / etc tries to push people to interact with DITA-OT using the `dita` command. So if the right solution is "Handle it one simple way with `dita` command and others have to work harder", I think it's acceptable to document it that way. Just becomes another reason to use `dita`. (Plugins are always / already an odd case where best practice is already to explicitly use properties like `dita.plugin.org.example.dir` for any items referenced in the plugin.)

For any of our options, including `css` or `cssroot`, I always get queasy about this:
> The value you enter here will be interpreted relative to the location of the input map file

Because ... if I'm in `/source/` and run this command:
`bin/dita -f html5 -i projectA/input.ditamap --args.cssroot somevalue --args.hdr commonHDR.xml`
I would expect the `args.cssroot` and `args.hdr` parameters to be relative to the directory where I'm typing the command. I don't think everybody feels this way though? I work in command lines a lot and I often use tab shortcuts to complete file names -- so it feels natural that these parameters would be relative to the directory I'm in, not relative to another parameter that is already relative to the directory I'm in. (I feel queasy just reading that to make sure I typed it right.)

`tl;dr:` I don't really like how these work now; I also don't like how it's documented; I don't know how best to fix / make it simple without breaking conditions, but I do think it's OK to make it easy for `dita` commands and harder for `ant` commands. Not sure any of this fixes the originally reported issue, in which case -- if we support an absolute path for `args.css`, using `args.copycss yes` should really result in copying the CSS file to output.

**Comment by hestonhoffman** [comment]
I ran into this today and it took me a while to figure out that an absolute path was required for `args.cssroot` as the docs still say "The relative path to the file can be specified with args.cssroot." It doesn't look like that docs commit made it in (dita-ot/docs@b92657e).
