### ISSUE TITLE
Dita-OT 3.1 and 3.1.1 do not process xmlelement / xmlatt

### ISSUE THREAD

**Issue by hscherzer** [dita-ot/dita-ot#3022]
## Expected Behavior
The elements `xmlelement `and `xmlatt `should be processed appropriately.

## Actual Behavior
A warning is produced
[topic-reader] [DOTJ030I][INFO] No 'class' attribute for was found for element `xmlatt`. 
The element will be processed as an **unknown or non-DITA element**.
[topic-reader] [DOTJ030I][INFO] No 'class' attribute for was found for element `xmlelement`. 
The element will be processed as an **unknown or non-DITA element**.

## Possible Solution
Appeared with version 3.1 / 3.1.1, the version 3.0.3 does not show that behavior. That's no solution but a hint.

## Steps to Reproduce

1. Simply create a document that contains at least one `xmlatt `and/or `xmlelement`
2. or ... run the attached files by `runxmp.bat`, using the DITA-OT 3.1 or 3.1.1

## Environment

* DITA-OT version: 3.1 and 3.1.1
* Operating system and version:
Windows 7 Professional

* How did you run DITA-OT?
 `dita` command ... see attached example `runxmp.bat`
* Transformation type:
pdf2  with the original 3.1.1 distribution
[xmp.zip](https://github.com/dita-ot/dita-ot/files/2206100/xmp.zip)

**Comment by raducoravu** [comment]
I cannot reproduce the problem using a stock DITA OT 3.1.1 downloaded from the DITA OT web site, without any changes made to it.

**Comment by hscherzer** [comment]
Thanks for caring ... If found the reason why you might not have seen the problem.

A **plain copy** of the latest Dita-OT 3.1.1 does not show the problem. That's your case and I can see the same, but didn't know that the following is relevant ...

Issuing a simple `T:\Dita-OT3>call ant -f integrator.xml` on such plain Dita-OT 3.1.1 should be allowed and will do plugin-integration. I did not put any plugin on the plain configuration but simply issued this command on the fresh download of OT 3.1.1.

The result is, that after issuing `T:\Dita-OT3>call ant -f integrator.xml` the problem **will appear** in the log file, at least that is what I could see after short research according to  your observations.

**Comment by raducoravu** [comment]
I tried to run the integrator in two ways:

bin\dita.bat -install

and:

bin\ant.bat -f integrator.xml

but I could not reproduce the problem. For me the catalog-dita.xml after running the integrator contains the proper order of the plugins.

Instead of invoking on your side "call ant -f integrator.xml" which invokes your "ant" process could you call instead "bin\ant -f integrator.xml" to invoke the DITA OT's bundled ANT? Maybe the fact that ANT is the one in the DITA OT or an external one might influence this, although I cannot reproduce even this scenario.

If you still encounter the problem, I can reopen the bug, maybe @jelovirt can look in the code to see why the reference to the v1_3 catalog is added after the one to the v1_2 catalog, from what I remember there was a special processing which made sure that the reference to the v1_3 catalog.xml came first in the catalog-dita.xml. In the properties file "config/configuration.properties" there is a "plugin.order" property which should be used to decide the order of loading and usage for these two plugins.

**Comment by raducoravu** [comment]
Reopening because I'm not quite happy with this "configuration.properties" situation. Maybe @jelovirt can help with advice.
So there are two configuration.properties, one in the "lib/" folder and one in the "config/" folder.
The class "org.dita.dost.util.Configuration" does something like this:

            final ClassLoader loader = FileUtils.class.getClassLoader();
            configurationInputStream = loader.getResourceAsStream(CONF_PROPERTIES);
            if (configurationInputStream != null) {
                properties.load(configurationInputStream);
            } else {
                final File configurationFile = new File("lib", CONF_PROPERTIES);
                if (configurationFile.exists()) {
                    configurationInputStream = new BufferedInputStream(new FileInputStream(configurationFile));
                    properties.load(configurationInputStream);
                }
            }

so depending if in the classpath the folder "config" or the folder "lib" comes first, it will load either one "configuration.properties" or another. The fallback is that it loads the "configuration.properties" from the "lib/" file which is probably incorrect because that "configuration.properties" only keeps the DITA OT version.
How about if we remove the "lib/configuration.properties" completely and move its information to "config/configuration.properties"?

**Comment by jelovirt** [comment]
The description and title of this issue doesn't reflect the configuration.properties issues. This should be closed and a new issue should be raised with title and description that reflects questions about configuration.properties.

**Comment by hscherzer** [comment]
I agree to Jarno that this is formally correct, however, this thread has an evolution from the original effect (xmlelement) to the actual reason of **wrong priority of the associated handlers**. If any user in this world has the same problem, s(he) will first get the <xmlelement> problem and will be happy to "find" it as title in this thread rather then the intellectual consequence of wrong order priority of DITA- modules.

From that point of view, it would be much better to have the "effect" in the title than the **deep thought** reason. For the problem workout - of course another title would match. I hope this is an understandable reasoning but if it only continues with a different title - that won't be the problem.

**Comment by jelovirt** [comment]
To be implemented in #3024.
