### ISSUE TITLE
Better customization for trademark symbol in PDF

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3072]
Based on [this discussion](https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/43963).

In the XSLT stylesheet [org.dita.pdf2\xsl\fo\topic.xsl](https://github.com/dita-ot/dita-ot/blob/e8b18d682926716c078443378db165d8f53fa350/src/main/plugins/org.dita.pdf2/xsl/fo/topic.xsl#L185) there is an XSLT
template which deals with the DITA `<tm>`:

```xslt
<xsl:template match="*[contains(@class, ' topic/tm ')]">
```

maybe it could delegate to some language-specific configuration files.

**Comment by jelovirt** [comment]
Would it be enough to move the different symbols into string variables, so you could have language specific overrides?

**Comment by robander** [comment]
Interesting, that would not have worked with the way I was imagining it.

Our variables tend to be generic, so that they can be used in different output transforms -- either plain text, plain text with placeholders, or (for images) a path to the image. It can't be the actual image markup, because it would have to be specific to FO or HTML or (whatever else). I don't think we want to introduce variables that could either be a character/string _or_ an image path, which means we'd need two variables, which starts to seem a bit more complex than necessary.
