### ISSUE TITLE
Relax domain requirementrs for DITA to XDITA conref

### ISSUE THREAD

**Issue by carlosevia** [dita-ot/dita-ot#3084]
## Expected Behavior

Conref content from a DITA topic to an XDITA topic.

## Actual Behavior

Transform does not conref and gives the following error message:
"[DOTX012W]: When you conref another topic or an item in another topic, the domains attribute of the target topic must be equal to or a subset of the current topic's domains attribute. Put your target under an appropriate domain. You can see the messages guide for more help."

## Possible Solution

Relax domains to allow conref. Ask @robander for his opinion/proposed solution.

**Comment by robander** [comment]
Discussed previously with Carlos, but this isn't really a DITA / XDITA thing -- that's just where it has come up because of the domains mismatch.

Back in DITA 1.0 the original idea for conref validation envisioned 1) an environment where every team had different shells and different domains, together with 2) a lot of reuse between those teams, which would require 3) complex tooling that would perform any required generalization on any reused element that required it. In addition, the expectation was that if you had a case where content reuse pulled in something that was not valid, this would be prohibited, and Everyone Would Be Happy. For many reasons this is not really how things turned out.

The latest [conref language in the spec](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/archSpec/base/conref-processing.html#concept_wf2_3sb_lq) describes how domains are compared to ensure validity, but does not say that reuse should be *prohibited* in case of mismatch -- it says we should tolerate specializations and generalize when we can:
> When pulling content with the conref mechanism, if the referenced element is the same type as the referencing element, and the set of domains declared on the @domains attribute in the referenced topic or map instance is the same as or a subset of the domains declared in the referencing document, the element set allowed in the referenced element is guaranteed to be the same as, or a subset of, the element set allowed in the referencing element.
> 
> ...(conref push info) ...  processors resolving conrefs SHOULD tolerate specializations of valid elements and generalize elements in the pushed or pulled content fragment as needed for the resolving context.

There is an additional topic on processing documents with [different domains](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/archSpec/base/module-compatibility.html#module-compatibility), which does imply that constraints would prohibit a content reference -- but even that should only apply to strict constraints. Adding the emphasis here: 
> When a copy operation is unsafe, processors MAY compare the copy source to the copy target to determine if the copy source satisfies the constraints of the copy target. **If the copy source meets the copy target constraints, the copy operation can proceed.** Processors SHOULD issue a warning that the copy was allowed but the constraints are not compatible. If the copy source does not meet the constraints of the copy target, processors MAY apply generalization until the generalized result either satisfies the copy target constraints or no further generalization can be performed. If the copy operation can be performed following generalization, the processor SHOULD issue a warning that the constraints are not compatible and generalization had to be performed in order to complete the copy operation.

In the end -- the only case where [the spec demands that we *not* resolve a conref](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/archSpec/base/constraints-conref-compatibility.html#conref-compatibility-constraints) is when the referencing document has incompatible strict constraints. In the case Carlos described of DITA / XDITA, there are no constraints in place, so we should not prohibit reuse. I do think it's valid to issue a warning about incompatible domains, because you may be pulling in something unexpected. But we should still resolve the content reference, instead of ignoring it as we do today.
