### ISSUE TITLE
Enable Extension of FO-Engine-Specific Plugins

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#3099]
## Description

Currently the .fop, .axf, and .xep plugs do not provide extension points. They should.

In addition, they each include the dita.xsl.xslfo extension point in their top-level XSLT files, which they should not.

## Possible Solution

Change the extension point in the XSLT to a plugin-specific name and declare the extension in each plugin's plugin.xml file.

## Potential Alternatives

None.

## Additional Context

Use case was implementing a small extension to table entry handling just for FOP to add zero-width spaces to enable line breaking of long strings. Realized that there was no direct way to do this and noticed the inappropriate import extension.

**Comment by raducoravu** [comment]
> In addition, they each include the dita.xsl.xslfo extension point in their top-level XSLT files, which they should not.

I noticed this morning the same problem, implementing the "dita.xsl.xslfo" extension adds references to your XSLT in 4 difference XSLT stylesheets.

**Comment by drmacro** [comment]
It's an easy fix and I can make it just don't have time right at this moment.

**Comment by drmacro** [comment]
The problem goes back to at least 2.5.4

**Comment by jelovirt** [comment]
We can't remove the old `dita.xsl.xslfo` extension point and replace them with formatter specif extension points for backwards compatibility. We can add e.g. new `fop.xsl.xslfo` to add FOP specific extension point to add imports to FOP shell stylesheet.

**Comment by drmacro** [comment]
But those extension points can't do anything since they duplicate the base one. They only result in redundant imports of the same extension XSLTs unless I've seriously misunderstood what is happening.

In addition, the extension points are not declared in the plugin.

They should have never been there.

**Comment by jelovirt** [comment]
If we remove `dita.xsl.xslfo`, existing plugins will break, because they will not use `fop.xsl.xslfo` extension point. We can break those plugins in DITA-OT 4.0, but I see no point breaking the old plugins like this.

**Comment by robander** [comment]
> But those extension points can't do anything since they duplicate the base one. They only result in redundant imports of the same extension XSLTs unless I've seriously misunderstood what is happening.

That's not what is happening today -- the 4 imports go into 4 different shells. None of them go into the main `topic2fo.xsl` file that is imported by all of the shells.

I think that one of the imports is generally a no-op (`org.dita.pdf2/xsl/fo/topic2fo_shell_template.xsl`) because the three known formatters will all use one of the other three shells. But ... it's the "default" in the absence of those 3 so it makes sense to define it.

The other three imports all go into the formatter-specific shell for FOP, AXF, or XEP -- none of them go into the common file.

I do think you could have an extra, formatter-specific import _after_ that one. But with the current design, each of the 3 shells will import your `dita.xsl.xslfo` extension after everything else.

**Comment by drmacro** [comment]
I see--I had misunderstood how those plugins worked.

However, they still need to have their own plugin-specific extension points for the reason I gave. I will try to develop a pull request for this at some point.
