### ISSUE TITLE
Temporary plugin installation locations

### ISSUE THREAD

**Issue by mkarg** [dita-ot/dita-ot#3112]
## Description
When running CI build machines, these machines often have to render lots of projects in parallel. For each render job, the set of needed plugin differs. There is no point in time when it is kown to the administrator of the machine, which plugins all those render jobs might need. Also, due to the nature of CI, plugins and plugin versions will change it fast pace, i. e. a job which needed plugin-v1 in build #n might need plugin-v2 in build #n+1, but a second job might still need plugin-v1.

## Possible Solution
Render jobs should be able to use plugins without the need to install them on the build machine. The optimal solution would be that a render job has a dependency which is a plugin-ZIP. Maven unpacks the ZIP to the project's target folder, and DITA-OT uses that folder as an additional plugin source. All plugins found there are used, even if not registered in DITA-OT.

## Potential Alternatives
There is no feasible alternative.

## Additional Context
Also happens on time-shared machines (terminal servers, shared workstations, etc.) when two people want to process lots of jobs with lots of custom plugins.

**Comment by mkarg** [comment]
@c-kunz FYI

**Comment by jelovirt** [comment]
Because DITA-OT plugin system is based on extension points that change code/functionality in other plugins, this would be difficult to implement because it's not how the plugin system was designed to work.

This can be made to work, but then we would need to redo the whole plugin system. To me this sounds equivalent to having a classpath in a Java process that changes dynamically.

**Comment by robander** [comment]
I had this use case a few years ago but eventually backed off when realizing that it really did mean starting over with plug-ins.

I previously made something like this work in a system outside of DITA-OT (but which reused most of the DITA-OT), but it was extremely inefficient. Basically in DITA-OT terms -- if it detected a situation where non-standard plug-ins were needed, it used a wrapper script to make a full copy of DITA-OT in the temp directory, install the plug-ins to that copy, run that DITA-OT.

I think if I was starting over today, I would probably use something like canned Docker containers that have the plug-ins I need -- there might be 2 or 5 or 20 different containers, and then use the one that has the plugins / transform types / styles I need. But I haven't thought about this use case for a few years so that's just my quick response today.

**Comment by mkarg** [comment]
@jelovirt Well... actually what Maven does *is* setting up class paths dynamically. That's the essence of the dependency system.
