### ISSUE TITLE
More consistent handling for table without frame attribute specified on it

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3143]
Let's say I have a DITA table without the `@frame` attribute set on it. In the HTML output the table has no frame, in the PDF output it has a frame. 
What should be the proper behavior? Unfortunately the DITA 1.3 specs does not seem to state what the default frame value is.

**Comment by xephon2** [comment]
:+1: for frame="all" everywhere

**Comment by robander** [comment]
This is the kind of thing the specification intentionally avoids for most elements (specifying what the default rendering should be), but I'd agree we should be consistent. I seem to remember being confused at some point because XHTML and PDF had always put on a frame by default, and I noticed HTML5 did not, but then forgot about the issue because I was working on something else at the time.
