### ISSUE TITLE
Common index preprocess

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#3145]
## Description

Add preprocessing module that collects index terms and groups them. The grouping should be extendable so plugins can contribute grouping code to handle e.g. additional languages.

**Comment by drmacro** [comment]
Rather than a preprocess, which would then require capturing the relation between each index entry and its original location, I would prefer a common XSLT module usable from any final-form transform that generates the same kind of generic index structure implied here to which you then apply final-form-specific processing (e.g., generate the FO or HTML index or whatever navigation structure is appropriate.

The reason for wanting it not as a preprocess is that there will sometimes be a need to either synthesize additional index entries based on semantic markup or otherwise adjust the index and that adjustment will likely need to differ for different deliverable forms.

In addition, only the final-form transform knows what the mapping from source elements to deliverable anchors is so any pre-processed index structure will still need to then be mapped to the source elements and then to their deliverable-specific anchors, rather than having the mapping happen naturally as part of the initial index generation (where presumably the code for generating deliverable anchors for a given element is well encapsulated). In the case of PDF in particular, as long as we continue to use the current merge process, the mapping is particularly tedious to handle.

Or maybe this is the impetus to abstract element-to-deliverable-anchor mapping out to a preprocessing stage based on a general architecture by which final-form transforms contribute preprocessing extensions that manage the mapping so that preprocessing and final form processing will reliably produce the same anchor for the same element for given deliverable? Such a facility is a prerequisite (or at least a serious convenience) for cross-deliverable addressing, where the anchor may be either generated by a deterministic function or looked up in some database reflecting the last-published (or target published) version of the deliverable.
