### ISSUE TITLE
Update Xerces to 2.12.0

### ISSUE THREAD

**Issue by eerohele** [dita-ot/dita-ot#3150]
Xerces 2.12.0 was released in May this year. Might be worth updating DITA-OT to use it.

**Comment by robander** [comment]
I wonder if this fixes the grammar caching issue that drops DTD entities (we have to run every build with grammar caching turned off because of the occasional use of entities). The release notes aren't very explicit ... I see one crediting @raducoravu that just says "Fixed various bugs and made various improvements. "

**Comment by raducoravu** [comment]
@robander No, grammar pool issue still opened:
https://issues.apache.org/jira/browse/XERCESJ-1205

**Comment by robander** [comment]
Updated with #3191 .
