### ISSUE TITLE
DITA OT 3.2.1: All "commons-attr.xsl" in "org.dita.pdf2\xsl\fo\topic.xsl" should be changed to "topic-attr.xsl"

### ISSUE THREAD

**Issue by sykim7** [dita-ot/dita-ot#3170]
## Expected Behavior

In "DITA-OT-3.2.1\plugins\org.dita.pdf2\xsl\fo\topic.xsl" file,
a correct path (for example,  `<xsl:with-param name="path" select="'../../cfg/fo/attrs/topic-attr.xsl'"/>`) must be passed to the path argument for the attrSet argument to work properly.

For example, the value passed to the attrSet argument in `<xsl:with-param name="attrSet" select="concat('__align__', $imageAlign)"/>` is used to get expected renderings like centered block images, and the possible $imageAlign values such as "__align__center" are found in "DITA-OT-3.2.1\plugins\org.dita.pdf2\cfg\fo\attrs\topic-attr.xsl'."

(By the way, this bug is found by my colleague, Sunhill.)

## Possible Solution

Just change all "commons-attr.xsl" in "org.dita.pdf2\xsl\fo\topic.xsl" to "topic-attr.xsl".

## Steps to Reproduce

1.
2.
3.

## Environment

* DITA-OT version: 3.2.1
* Operating system and version: Windows
* How did you run DITA-OT? Ant
* Transformation type: PDF

**Comment by raducoravu** [comment]
In the XSL "plugins/org.dita.pdf2/xsl/fo/topic.xsl" there is at some point a call template like this:

        <xsl:call-template name="processAttrSetReflection">
                <xsl:with-param name="attrSet" select="concat('__align__', $imageAlign)"/>
                <xsl:with-param name="path" select="'../../cfg/fo/attrs/commons-attr.xsl'"/>
            </xsl:call-template>

If you look in the XSLT stylesheet "plugins/org.dita.pdf2/xsl/common/attr-set-reflection.xsl" the "processAttrSetReflection" template has various switches, one of them taking care of the "__align__center". The passed "path" parameter seems to be taken into account only in the last instance.
So the current code works in my opinion.

But indeed the code seems convoluted, @robander do you have an opinion on this? I would have assumed the XSLT template "processAttrSetReflection" not to have all those different individual switch cases. Or at least when the "processAttrSetReflection" is called from the "topic.xsl" avoid sending a "path" parameter value to it.

**Comment by robander** [comment]
@raducoravu I think my only opinion is to agree that the `processAttrSetReflection` code is convoluted :+1: 

I do not really like that code but have never tried to change it. I believe it has been there since the `pdf2` code was originally developed in Idiom.

**Comment by jelovirt** [comment]
It's been a while since I've taken a look at the attribute reflection code. There may be some things it allows us to do that plain XSLT 2.0 doesn't, but I think the whole reflection code should be refactored out and replaced with something else.

**Comment by jelovirt** [comment]
Alas, this may be a backwards incompatible change, so we may need to hold off until 4.0? @robander

**Comment by robander** [comment]
We don't have to hold to 4.0, but it might affect how we refactor?

We've made other incompatible changes at release boundaries (not hotfix boundaries), and they should be listed in the migration instructions.

It's been a long time since I looked at this, so I remember it was ugly but I don't know what would be needed to refactor. If we kept / deprecated the `processAttrSetReflection` template around but changed our code to call something else, that might be fine for 3.3. Anybody with overrides that call it would still work but would want to start updating.

I'm not sure if that would work here because of the weird way file names are passed. I don't know if we could refactor in a way that custom attribute sets still work as they do today, for anybody who has not customized other code.
