### ISSUE TITLE
empty nav when the topic has a space in its name for nav-toc=partial in HTML5

### ISSUE THREAD

**Issue by plus-** [dita-ot/dita-ot#3213]
## Expected Behavior
Every topic accessed in the HTML5 output should display the nav when setting `nav-toc=partial`

## Actual Behavior
Whenever a topic has a space in its name (properly linked from the ditamap using a `%20`), the topic will not have any nav in the output.

## Steps to Reproduce
1. Take any content, put a space in a topic name and change the link from the topicref associated
2. Run the html5 output with `nav-toc=partial`
3. Open the topic from the index.html

## Environment

* DITA-OT version: 3.2.1
* Operating system and version: Windows 10
* How did you run DITA-OT? command line
* Transformation type: HTML5

**Comment by robander** [comment]
Reproduced with latest `develop` code; the TOC is inserted in all topics without spaces, but the topic with spaces in the file name has this where the navigation should be:
`<nav role="toc"><ul></ul></nav>`

**Comment by robander** [comment]
The problem shows up here:
https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.html5/xsl/nav.xsl#L58

The `$FILENAME` parameter is passed in as `test file.dita` instead of `test%20file.dita`, so `$current-file` ends up with the same value; that value does not match the `topicref/@href` value when we collect `$current-topicrefs`. 

I'm testing this on Windows like the original report - I wonder if other systems pass in the FILENAME param as a space or as %20?

**Comment by plus-** [comment]
Just wanted to add the bug exists on 2.5.4 as well.

**Comment by robander** [comment]
Fixed with #3229.
