### ISSUE TITLE
Cannot Use Keyscope within a conref source

### ISSUE THREAD

**Issue by cqbnzxy** [dita-ot/dita-ot#3259]
**My DITA environment**: DITA OT 3.0, DITA 1.3
**Problem Description:** 
 I have a step <cmd> that appear many times in my book: 　Log in to `<ProductName>.` 
So I used conref for it.
`<cmd id="v3630908" conref="t3630882.dita#t3630882/log_in"></cmd>`

But I also need the product name to change in each submaps (my submaps all have the same structure). Such as:
Map A: Log in to Product A.
Map B: Log in to Product B.
So I used key in the conref source file (t3630882.dita):
`<cmd id=”log_in”> Log in to <ph keyref=”product_name”></ph>.</cmd>
`
In my referencing maps, I defined the keyscope, keys, and conreffed the above <cmd>.
In map A:
`<map keyscope="A">
<keydef  keys="product">
<topicmeta >
<keywords>
<keyword>Product A</keyword>
</keywords>
</topicmeta>
</keydef>
<topicref format="dita" type="task" href="t3630899.dita"></topicref></map>
`
In map B:
`<map keyscope="B">
<keydef  keys="product">
<topicmeta >
<keywords>
<keyword>Product B</keyword>
</keywords>
</topicmeta>
</keydef>
<topicref format="dita" type="task" href="t3630899.dita"></topicref></map>
`
## Expected Behavior
All keyref should be resolved.

## Actual Behavior
But the keyref within the conref is not resolved.
The same key instances are resolved successfully in other places though.

[keyscope_conref_source files.zip](https://github.com/dita-ot/dita-ot/files/2981195/keyscope_conref_source.files.zip)

**Comment by drmacro** [comment]
In my tests with 3.3 as released the resolved map does not reflect the key scopes defined by either the maprefs or by explicit scopes on the submaps (if I add them). I tried both preprocess and preprocess2.

**Comment by raducoravu** [comment]
One of our end users reported this as well. 
I switched to using conkeyref instead of conref, the keys are resolved but they are resolved to the same value so the key scope is no longer applied:
[keyscope_conref_source files-conkeyref.zip](https://github.com/dita-ot/dita-ot/files/3319419/keyscope_conref_source.files-conkeyref.zip)

**Comment by raducoravu** [comment]
One of our end users reported this as well. 
I switched to using conkeyref instead of conref, the keys are resolved but they are resolved to the same value so the key scope is no longer applied:
[keyscope_conref_source files-conkeyref.zip](https://github.com/dita-ot/dita-ot/files/3319419/keyscope_conref_source.files-conkeyref.zip)

**Comment by raducoravu** [comment]
Probably in the first case (using plain conrefs) it would have helped if the publishing pipeline would have resolved first the conrefs and then the keyrefs. But there is no parameter to control the order in which these two are called.
The second case (conkeyrefs and keyrefs) should have worked. So I consider this a bug.
