### ISSUE TITLE
@locktitle with no navtitle results in unresolved xref when it should not

### ISSUE THREAD

**Issue by drmacro** [dita-ot/dita-ot#3290]
Given this topicref:
```
<topicref href="topics/topic-03.dita" locktitle="yes" keys="topicref-03"/><!-- No navtitle -->
```
And this xref to key "topicref-03":
```
<xref keyref="topicref-03"/>
```

The resulting xref in e.g., HTML5 output is "topics/topic-03.dita" when it should be the title of the topic (e.g., "Topic Three").

The ToC is correct so the issue appears to be in the xref resolution.

Per the DITA spec, if @locktitle is yes but there is no navigation title then the topic's title is used.

[locktitle-test-01.zip](https://github.com/dita-ot/dita-ot/files/3109697/locktitle-test-01.zip)

Tested with out-of-the-box OT 3.3 HTML5 transform run from Oxygen.

**Comment by robander** [comment]
I think this is a content error - it does not make sense to set `locktitle="yes"` without setting a title.

In other areas of DITA-OT, if you reference a file where we do not have a title (like `<xref href="some.dita" scope="peer"/>`), we will use the file name as the title / link text. That seems like an appropriate thing to do here, where you've explicitly said "Lock in this title" but you do not provide the title.

I'm not finding content in the spec that tells me this:
> if @locktitle is yes but there is no navigation title then the topic's title is used.

Looking at the specification here: http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/langRef/attributes/commonMapAttributes.html#topicref-atts__locktitle

The first part says
> If the @locktitle attribute is set to "yes", the content of the <navtitle> element or @navtitle attribute is used for a navigation title, if it is present.

I'm guessing that you read "if it is present" to mean "if not, use the topic's title" ... but that's not actually stated, it only says to use the title if present. In the actual definition of the `yes` value it does not provide for any alternative or fallback, it just assumes that the title will be specified.

I think I'd prefer to treat this as working-as-designed (input that does not make sense does not have to give ideal output).


It seems to me that using the file name is sort-of the correct behavior for this, because the file name is also used for any other situation
