### ISSUE TITLE
Block shortdesc is not a block

### ISSUE THREAD

**Issue by thendarion** [dita-ot/dita-ot#3305]
Okay, so this is something I don't really understand:
```topic__shortdesc``` only inherits ```body```, but not ```common.block```,
hence ```format-shortdesc-as-block``` does not really format shortdesc as block...
What am I missing? Did I just find a bug?

**Comment by robander** [comment]
It does format as a block because it is using `<fo:block>`.

I am not sure why it does not use `common.block`, but it may be because a lot of plugins do special formatting for short descriptions, and do not want to pick up the same common rules that are used for blocks within a topic.

The current output is correct, and the `common.block` attribute set is not required here, so I think this can be closed.

**Comment by thendarion** [comment]
thx :)
