### ISSUE TITLE
fn/@id="-dita-use-conref-target" does not work

### ISSUE THREAD

**Issue by ToshihikoMakita** [dita-ot/dita-ot#3332]
## Expected Behavior
`<fn id="-dita-use-conref-target" conkeyref="COMMON-FN/fn_common"/>` should fetch `@id` from the conkeyref target. 

## Actual Behavior
The conkeyref result of fn does not contain `@id` attribute.

## Possible Solution
`id="-dita-use-conref-target"` should be honored.

## Steps to Reproduce
1. Copy the following three files and build PDF2.
    https://gist.github.com/ToshihikoMakita/a36dd8abe58163368f77773992e5e144
2. You can confirm that `fn` in file in temp folder converted from cFnConkeyrefTest.dita does not contain `@id` attribute.

## Copy of the error message, log file or stack trace
There is no error messages in build process.

## Environment

* DITA-OT version: 3.3.2
* Operating system and version: Windows 10
* How did you run DITA-OT?
  oXygen PDF2 transformation scenario.
* Transformation type:PDF

**Comment by robander** [comment]
This is a usage for `fn/@id` that I haven't seen before and had never considered.

I can see why it is not working -- the DITA specification explicitly says that the `@id` attribute is **not** retrieved from the referenced element. There is no exception for the `-dita-use-conref-target` value on this attribute (I'm sure this was never considered). Here are the rules for [resolving content references](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/archSpec/base/conref-attributes-specified-on-elements.html):

> The attribute specifications on the resolved element are drawn from both the referencing element and the referenced element, according to the following priority:
> 1. All attributes as specified on the referencing element, except for attributes set to "-dita-use-conref-target".
> 2. All attributes as specified on the referenced element except the `@id` attribute.
> 3. The `@xml:lang` attribute has special treatment as described in The xml:lang attribute .

I see in your sample that you have this sort of markup for the reuse:
`.<fn conkeyref="COMMON-FN/fn_common" id="-dita-use-conref-target"/><xref href="#./fn_common" format="fn"/>`

Is there a reason that you are trying to pull in a footnote for reference, and then creating it, instead of just pulling in the footnote? I would normally just reuse the footnote like this, which works for me in HTML5 output:
`.<fn conkeyref="COMMON-FN/fn_common"/>`

That results in a footnote without an ID, so it appears right at that point in the document.

**Comment by ToshihikoMakita** [comment]
The original intention requested from the user is:

- Define most commonly used `fn` in shared module.
- Use it by using `conkeyref`.
- Reference it by `xref` using `@id` attribute originally defined in shared module.

So the `fn/@id` is indispensable. However as your referenced `@id` attribute is explicitly rejected to use from the referenced element.

[2.4.2.3 Processing attributes when resolving conrefs](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part1-base/archSpec/base/conref-attributes-specified-on-elements.html)

I will inform this to the user and author `@id` attribute in the referencing `fn`.
