### ISSUE TITLE
More useful error message when we have a broken image reference

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3340]
Let's say I have a DITA topic referencing a missing image.
When producing the PDF the error message received during the "gen-list" phase will be something like:

    [DOTX008E][ERROR] File 'file:/C:/Users/radu_coravu/Desktop/path/to/image.png' does not exist or cannot be loaded.

but maybe it could also state the system ID (maybe even line number) of the DITA topic file where the image is referenced.

**Comment by robander** [comment]
Marking this as a bug, because I consider it a defect that we do not tell you where the reference is located, but knowing the code I'm not sure if this can be easily resolved. The process adds references into a queue when it finds them and processes later, but this means when we try to copy images we are just working from the list, and do not know the source location.
