### ISSUE TITLE
Specifying "-debug -verbose" in the dita command line seems to favor "verbose"

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3342]
I think that it should favor "-debug" because it outputs more console output.

**Comment by jelovirt** [comment]
When multiple arguments that define the same thing are uses, the last of wins. I'd prefer to not change this, because then we'd need to start defining multiple rules for resolving multiple same arguments. A simple fix would throw an error when duplicates are defined, but that would be backwards incompatible.

**Comment by raducoravu** [comment]
Makes sense
