### ISSUE TITLE
Move to Java 17

### ISSUE THREAD

**Issue by jelovirt** [dita-ot/dita-ot#3359]
Java 8 is currently still LTS but e.g. Oracle's commercial distribution has been discontinued and the latest LTS version is 17. While e.g. AdoptOpenJDK plans to backport fixes until 2023, new features are being added to the language and it would be nice to be able to use them.

Move to Java 17 in the build configuration to allow using Java 9-17 features.

**Comment by raducoravu** [comment]
Would that mean that using Java 1.8 would not work anymore to start the DITA OT? Because we still have Oxygen installation kits with Java 1.8 bundled.

**Comment by jelovirt** [comment]
Yes, the minimum version would be 11. Note that this is for DITA-OT 4.0. There has been no discussion or decision on how many 3.x versions with Java 8 we will release.

**Comment by raducoravu** [comment]
I do not know much about the release timeline. What's the next release of the DITA OT? Will DITA OT 3.4 be released at the DITA OT Day? Or do you plan to release 4.0 there?
Because if you plan 4.0 for next year we'll probably also switch next year to Java 11 or newer (13).
We plan to release Oxygen 22 next year in January and somehow I would want it to have a bundled DITA OT which still works with Java 1.8.

**Comment by jelovirt** [comment]
[Java 14](https://openjdk.java.net/projects/jdk/14/) was released 2020-03-17.
