### ISSUE TITLE
Element is displayed as flagged instead of filtered

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3418]
Let's say I have a DITA topic with an element inside:

    <p props="changed">This is changed text.</p>

and a DITAVAL file containing these rules:

      <val>
         <prop att="props" action="exclude"/>
         <prop att="props" val="changed" action="flag" backcolor="yellow"/>
      </val>

Right now if I publish to HTML the element is displayed and flagged as yellow.
But according to the specification:

http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/archSpec/base/flagging.html#flagging

      When the same element evaluates as both flagged and filtered (for example, flagged because of a value for the @audience attribute and filtered because of a value for the @product attribute value), the element should be filtered.

So I think in this case the element should be excluded by the DITAVAL and not flagged.

[oxygen_dita_ditaval.zip](https://github.com/dita-ot/dita-ot/files/3867599/oxygen_dita_ditaval.zip)

**Comment by robander** [comment]
Good question - but I think the current behavior is correct.

This is not the example that the spec was trying to address with that example. The spec topic is trying to address what happens when you have `@audience` evaluate to "flag" and `@product` evaluate to "exclude". In that example, because the product is excluded, the flag does not matter. In this case you've got a general "exclude" rule for `@props` but also a "flag" rule for a specific value. I think this is the case described here, with the 2nd and 3rd list items:
http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/ditaval/ditaval-prop.html

With your example - using `<prop att="props" action="exclude"/>` sets a default rule of "exclude" for that attribute. That default is only used for values that do not specify rule for a specific props value. In this case, when you set the specific "flag" it means the default rule is not used.

**Comment by raducoravu** [comment]
Thanks, I’m closing the issue
