### ISSUE TITLE
Missing xref href is not trapped

### ISSUE THREAD

**Issue by Number9Solutions** [dita-ot/dita-ot#3422]
## Expected Behavior
Given the following XML:
&lt;xref class="- topic/xref "&gt;Some text&lt;/xref&gt;
I would expect that the DITA-OT would throw an error DOTX028E (missing href)

## Actual Behavior
In DITA-OT 3.2 (and presumably 3.4), no error is thrown.
In some prior versions of the DITA-OT (e.g. 2.2.5), a DOTX017E (empty href) error is thrown rather than DOTX028E (missing href)

## Possible Solution
Unknown.

## Steps to Reproduce
Generate any output (pdf, html, etc.) that includes a topic with an xref that does not have an href attribute.

## Copy of the error message, log file or stack trace
N/A.

## Environment

* DITA-OT version: 3.2
* Operating system and version: Windows
* How did you run DITA-OT?
 dita command
* Transformation type:
HTML5

**Comment by robander** [comment]
Removing this message was an intentional change in DITA-OT 3.2; it is not invalid markup, and in fact is the preferred markup when disabling a link for some contexts. For example, I've encountered it in situations like this:
`See <xref keyref="relatedProduct"/> for info on this other product`

Where the HTML markup turns that into a link to information about another product, while the PDF markup turns that into a text-only "link" that has the name of a PDF book. In earlier releases, that resulted in a build error from the build for the text-only resolution, even though the output was exactly what was expected / intended.

The change was made as part of: https://github.com/dita-ot/dita-ot/pull/3030/

**Comment by Number9Solutions** [comment]
Good to know. Thanks, Robert!
