### ISSUE TITLE
Potential security vulnerability: target="_blank" ?

### ISSUE THREAD

**Issue by thendarion** [dita-ot/dita-ot#3480]
hi,

I just came accross this:
https://developers.google.com/web/tools/lighthouse/audits/noopener

and realized that external links simply have target="_blank" in the output

what's your take on the situation?

**Comment by jelovirt** [comment]
Sounds simple enough. We just have to make it easy to disable for those users who still want the old behaviour.

**Comment by jelovirt** [comment]
It would be nice to implement this by adding some `external-link` attribute set, but using that would be difficult. We'd have to do something like

```xml
<xsl:variable name="atts" as="element()">
  <dummy xsl:use-attribute-sets="external-link"/>
</xsl:variable>
<xsl:sequence select="$attr/@*"/>
```

And that's way too verbose because it would need to be duplicated multiple times.

The other option would be to use a template mode and it would likely work.

**Comment by thendarion** [comment]
could we quickly port this to XHTML too, please :D

I'll open a ticket for that
