### ISSUE TITLE
sectiondiv element should accept child title OR default XSL should transform sectiondiv/data/title

### ISSUE THREAD

**Issue by AnimatIan** [dita-ot/dita-ot#3614]
## Expected Behavior

When I author a sectiondiv, I expect to add a title for that.  I should be able to add a title element, but this is not allowed.  That title element should also be transformed by default XSL to an appropriate level heading in HTML output (for example)
## Actual Behavior

- In sectiondiv, a title element is not allowed, but I can add a data/title element.
- In default XSL, sectiondiv/data/title is not processed to output.

## Possible Solution

As a workaround, I use custom XSL to transform sectiondiv/data/title to output HTML heading based on the section/title template use:

```
<!-- Pass through to get sectiondiv title -->
	<xsl:template match="*[contains(@class, ' topic/data ')]" >
		<xsl:apply-templates/>
 	</xsl:template>

  <xsl:template match="*[contains(@class, ' topic/sectiondiv ')]/*[contains(@class, ' topic/data ')]/*[contains(@class, ' topic/title ')]">
	<!-- Add 1 extra for parent section -->
    <xsl:param name="headLevel">
      <xsl:variable name="headCount" select="count(ancestor::*[contains(@class, ' topic/topic ')])+2"/>
      <xsl:choose>
        <xsl:when test="$headCount > 6">h6</xsl:when>
        <xsl:otherwise>h<xsl:value-of select="$headCount"/></xsl:otherwise>
      </xsl:choose>
    </xsl:param>
    <xsl:element name="{$headLevel}">
      <xsl:attribute name="class">sectiontitle</xsl:attribute>
      <xsl:call-template name="commonattributes">
        <xsl:with-param name="default-output-class" select="'sectiontitle'"/>
      </xsl:call-template>
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>
```

## Steps to Reproduce

1. In a DITA topic, add a sectiondiv
2. In the sectiondiv, try to add a title element (fails)
3. In the sectiondiv, add a data/title element (succeeds)
4. Using default XSL in DITA OT, transform the topic to HTML5 - the sectiondiv/data/title is not output

## Environment

**<oXygen/> XML Author 22.1, build 2020072902**

* DITA-OT version:
* Operating system and version:
  _(Linux, macOS, Windows)_  Windows 10
* How did you run DITA-OT?
  _(`dita` command, Ant, `startcmd`, oXygen, other editor, CMS, etc.)_  oXygen
* Transformation type:
  _(HTML5, PDF, custom, etc.)_  HTML5

**Comment by drmacro** [comment]
The sectiondiv element is not intended to be titled (none of the "div" elements in DITA are intended to be titled).

So your expectation is at odds with the intent of the spec.

Beyond that, putting <title> in <data> would, by definition of <data>, have no default effect, because <data> (metadata container) is not rendered by default.

It looks like you have an information design problem that you were trying to solve by using DITA markup in a way it was not intended to be used.

The <section> element is titled but explicitly *does not contribute* to the title hierarchy represented by topics (either as defined in a map or by literal nesting of topics).

The only titled elements that can be used within <section> (or <sectiondiv>) are <fig> and <table>, but those are probably not what you want either.

If you are looking to create a hierarchy of titles the only correct way to do that is with topics, either through maps (hierarchies of topicref/topichead) or through literal nesting within a single XML document.

**Comment by jelovirt** [comment]
Closing as feature request that goes against DITA spec. This can be implemented in a plug-in if needed.
