### ISSUE TITLE
Add RELAX NG schemas to catalog

### ISSUE THREAD

**Issue by infotexture** [dita-ot/dita-ot#3641]
We currently ship 2 RELAX NG schemas that can be used to validate plug-ins and project files:

- `resources/project.rnc`
- `resources/plugin.rnc`

When these schemas are referenced in files with **relative** URIs as in our own docs [/samples/project-files/html.xml](https://github.com/dita-ot/docs/blob/develop/samples/project-files/html.xml#L2), validation may fail if these files are opened or maintained outside the toolkit directory _(as is common in many custom development projects)_. 

## Potential solution: add to catalog

In discussion with @raducoravu, he commented:

> if for example the `catalog-dita.xml` would have had an URI mapping
> for the `project.rnc` schema like:
>
>     <uri name="http://www.dita-ot.project.com/project.rnc
>     <http://www.dita-ot.project.com/project.rnc>"
>     uri="../../resources/project.rnc"/>
>
> you could have used that absolute URI when referencing the
> `project.rnc` from your XML and Oxygen would have found the target
> by going through the XML catalog support.

### — but to _which_ catalog?

> So the RNC file is located in `dita-ot/resources/project.rnc`.
>
> The `dita-ot/catalog-dita.xml` is deprecated and should not be modified further by adding an extra mapping in our case.
>
> The `dita-ot/plugins/org.dita.base/catalog-dita.xml` seems to be intended to map schemas or plugin IDs, XSLTs. Adding in it a reference to a folder 2 levels up 
> `../../resources/project.rnc` seems ugly to me.
>
> So I do not know where that catalog entry should be added, maybe an extra `catalog.xml` could be added to `dita-ot/resources` with some mappings for `plugin.rnc` and `project.rng`?

The catalog approach seems like the right way to handle this in a vendor-neutral way, as any XML editor with catalog support _(at least those aware of DITA-OT catalogs)_ would then be able to validate files based on these schemas regardless of file location.

The `project.rnc` file [declares a namespace](https://github.com/dita-ot/dita-ot/blob/develop/src/main/resources/project.rnc#L1), so we might want to do something similar for the plugin schema:

    default namespace = "https://www.dita-ot.org/project"

@jelovirt @robander Any thoughts?

**Comment by infotexture** [comment]
@jelovirt @robander 

- The RELAX NG schemas were published to public URLs with dita-ot/website#455
- https://github.com/dita-ot/docs/commit/08e4f4ea6aab69d18a089b98a1ae77cac7aeac62 switches the docs samples to use the new public URLs

Should we add a new catalog to the `resources/` folder of the distribution package (alongside the schemas), or add these entries to one of the other existing catalogs, like `org.dita.base/catalog-dita.xml`?

**Comment by robander** [comment]
I think it probably makes sense to add these to a catalog. My first thought would be -- don't add a new catalog into `resources/` just because we've slowly moved most things out of root directories and into plugins, and for it to be picked up by most OT users, it would have to get referenced from the catalog in the base plugin.

Although that could mean -- add a new catalog in `resources/` and then in the base plugin, add one line to the template,
`<nextCatalog catalog="../../resources/whatever-catalog-name.xml"/>`

It's not pretty but I'm not sure we have a pretty way to reference those files?

**Comment by raducoravu** [comment]
Or create a DITA OT plugin containing both schemas from the "resources" folder and an XML catalog plus remove the "resources" folder. The Java code could access the schemas using an URI resolver created over the main DITA OT catalog-dita.xml.

**Comment by jelovirt** [comment]
Background: Our directory structure is a mess.  The `src` is really the source directory for the `org.dita.base` plugin, but because our source Git repo's directory structure tries to also be the final distribution directory structure, various files and directories overlap in Git.

The `resources` directory in the distribution package is not used by DITA-OT code and is there just for convenience for the users. You can remove that directory and DITA-OT code will still work. So in that sense we could just have a `catalog.xml` there that only has entries to plug-in and project configuration RNGs.
