### ISSUE TITLE
Error in mapref stage when passing dita map as resource

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3724]
I'm attaching a sample DITA project
[chemistry_crash_single_topic.zip](https://github.com/dita-ot/dita-ot/files/6242590/chemistry_crash_single_topic.zip)

on Windows I'm running this command line:
```batch
dita -i C:\Users\radu_coravu\Downloads\chemistry_crash_single_topic\iugux\installation_preparation\overview_of_installation_process.dita ^
  --resource=C:\Users\radu_coravu\Downloads\chemistry_crash_single_topic\iugux.ditamap ^
  -f html5 ^
  --temp=tmp ^
  --clean.temp=no ^
  -v
```

then I get an error reported in the "mapref" stage:

     [mapref]   I/O error reported by XML parser processing
     [mapref]   file:/C:/Users/radu_coravu/Desktop/dita-ot-3.6/bin/tmp/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap: C:\Users\radu_coravu\Desktop\dita-ot-3.6\bin\tmp\C:\Users\radu_coravu\Downloads\chemistry_crash_single_topic\iugux.ditamap (The filename, directory name, or volume label syntax is incorrect)

As you can see the absolute path to the dita map gets concatenated to the absolute path to the temporary files folder, producing an invalid file path on Windows.
Looking in the .job.xml at the entry for the DITA Map:

```xml
        <file src="file:/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap"
            uri="file:/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap"
            path="C:\Users\radu_coravu\Downloads\chemistry_crash_single_topic\iugux.ditamap"
            result="file:/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap"
            format="ditamap" resource-only="true"/>
```
it is the only entry with an absolute `@path` attribute.

When the method "org.dita.dost.module.MaprefModule.processMap(FileInfo)" gets called, the input file gets computed by appending two absolute file paths one to another:

```java
    File inputFile = new File(job.tempDir, input.file.getPath());
```
which is invalid on Windows.

The same thing works on Mac because the file path does not contain a drive name and "new File(job.tempDir, input.file.getPath())" manages to produce a valid file path.

**Comment by raducoravu** [comment]
As a proposed fix in the method GenMapAndTopicListModule.processParseResult(URI) update the uplevels depending also on the extra resources:

        if(resources != null) {
        	for (URI uri : resources) {
				updateUplevels(uri);
			}
        }

**Comment by kirkilj** [comment]
I'm going to attach my test content when I return to my office, but I wanted to mention that 3.7.3 and 3.7.4 seem to do something much worse than just concatenating 2 absolute paths. The source resource map is getting overwritten with a preprocessed version of itself on Windows as if it was the temp file. Subsequent processing produces validation errors in the modified source map during the build. This only started happening to writers when we enhanced our Oxygen custom plugin to automatically add the DITA Map Manager context map as a --resource parameter when rendering a single topic.

It's behaving as if it's just taking the 2nd absolute path in the concatenated Frankenstein path as the temp file path, which is the original resource map's location.

**Comment by raducoravu** [comment]
@kirkilj you should also test with DITA OT 4.1 and maybe open a new issue instead of contributing to this one.

**Comment by kirkilj** [comment]
Hi @raducoravu, that was going to be my next step. I actually downloaded the develop branch for testing, but I'll try 4.1 as well, and if it's still an issue, I'll open a bug. 

We haven't moved to 4.x yet, because a couple of our plugins stopped working, so we had to put it off until Q4 this year. I couldn't figure out how to create a transform to do the same with 4.x, so I'll just use the command line instead. I've got a deadline to hit tonight (this morning already), so it will probably need to wait until tomorrow. I'm going to attach a zip here anyway in case you have time to verify before I do and have the time. If not, no worries.

I changed the directory structure slightly from your zip from this ticket and converted the RNG doctypes to DTDs. There was also a broken key, so I fixed it. The zip includes a .git folder in case the history is useful in some bizarre way.

The build finishes with no errors and shows the resultant topic html with the keyref resolved, but if you look at the map in text mode, you'll see that it was overwritten. This never shows in our Jenkins builds because the correct output is generated and the Jenkins workspace evaporates when the job finishes. It's only local builds where writers started noticing.

[cli_resource_corruption_single_topic.zip](https://github.com/dita-ot/dita-ot/files/12734607/cli_resource_corruption_single_topic.zip)

**Comment by kirkilj** [comment]
Since we can't move to 4.1 right now, I'm also going to see if using a relative path for the resource map from either the topic path or project path works-around the path concatenation issue.

**Comment by kirkilj** [comment]
Just an Oxygen question: I also noticed that the command line generated by the XHTML transform in Oxygen 25.1 wraps all the -D parameters in double-quotes, including the -D prefix, but the pathnames as part of the -i, -o, or -t parameters do not. What happens if a pathname contains a space?

`"C:\dita-ot-3.7.2\dita/bin/dita.bat" -v -f xhtml -o C:\Users\kirkilis\Downloads\chemistry_crash_single_topic/out/topic-xhtml -t C:\Users\kirkilis\Downloads\chemistry_crash_single_topic/forensics/temp/topic-xhtml -i C:\Users\kirkilis\Downloads\chemistry_crash_single_topic\content\installation_preparation\overview_of_installation_process.dita "-Dclean.output=yes" "-Dargs.debug=yes" "-Dargs.resources=C:\Users\kirkilis\Downloads\chemistry_crash_single_topic\content\iugux.ditamap" "-Dclean.temp=no"
`

**Comment by raducoravu** [comment]
@kirkilj about the Oxygen question, you can test this for yourself, if these specific -i,-o.. parameters contain whitespaces, Oxygen will start wrapping their values in double quotes when creating the command line.

**Comment by raducoravu** [comment]
@kirkilj I found a bit of time and looked into the "chemistry_crash_single_topic" archive you attached.
Can you give me some precise steps to reproduce the problem?
Let's say I'm using a stock DITA OT 4.1.1, I see inside the archive there are two "iugux.ditamap", files, which one should be the root map? 
I used this one in my tests "chemistry_crash_single_topic/content/iugux.ditamap"
Also what topic should I publish to XHTML? I tried with "chemistry_crash_single_topic/content/installation_preparation/overview_of_installation_process.dita" because it seems to have a keyref.

So I publish to XHTML the "installation_preparation/overview_of_installation_process.dita" using as value of "args.resources" the path to "chemistry_crash_single_topic/content/iugux.ditamap", the publishing seems to work and the "chemistry_crash_single_topic/content/iugux.ditamap" map is not overwritten.
But I also do not get this error when using the DITA OT 3.7 bundled with Oxygen 25.1.

**Comment by kirkilj** [comment]
I came back to this issue and realized I dropped the ball and didn't follow-up on @raducoravu's last comment. I just retested the local publishing of a single topic while passing in a resource map on the command line using 3.7.4. Just as before on Windows, it overwrites the resource map with a somewhat preprocessed version of itself. We've tested it completely outside of Oxygen using the Maven command line and get the same results as well, even when using relative paths. If you notice below, the temp directory was not used for the resource map like the others. The original file was treated as the temp variables.map file.

![image](https://github.com/dita-ot/dita-ot/assets/128799/a16eb228-18b0-4b55-9eb7-2b1cafad6f90)

**This incorrect behavior does NOT happen in 4.2.3**, so this was addressed on some ticket along the way. I haven't tracked the specific ticket down yet, but it's not critical.

We'll alter our Oxygen plugin to suppress adding a resource map to our command line constructor when locally building an XHTML topic with a resource file until we've moved to the current 4.x OT release train.
