### ISSUE TITLE
Key reference in content referenced content not properly expanded when using key scopes

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3733]
I'm attaching a sample project file, the main DITA Map is "hzm1617899793683.ditamap" and it can be published to PDF:
[keyscope-conkeyref-keyword-fail-1.zip](https://github.com/dita-ot/dita-ot/files/6355677/keyscope-conkeyref-keyword-fail-1.zip)

There is a topic named "xge1617899981044.xml" referenced as resource-only in multiple key scope contexts.
Paragraphs from this topic are reused in other topics via conkeyref, for example in "jxk1617900527138.xml".

Key references are expanded by the DITA OT before content references. The "org.dita.dost.module.KeyrefModule.processTopic(FileInfo, KeyScope, boolean)" method considers that it should not create unique files for each reference to the "xge1617899981044.xml" topic because it is resource-only:

      final int increment = isResourceOnly ? 0 : 1;

In my opinion the condition should be something like:

     final int increment = isResourceOnly && ! ditaFormat ? 0 : 1;

**Comment by raducoravu** [comment]
My final patch in the "org.dita.dost.module.KeyrefModule.processTopic(FileInfo, KeyScope, boolean)" method from the DITA OT Java code looks like this:

     /**
      * Determine how topic is processed for key reference processing.
      *
      * @return key reference processing
      */
     private ResolveTask processTopic(final FileInfo f, final KeyScope scope, final boolean isResourceOnly) {
         //EXM-47806 Possible patch, increment counters more eager for references to resource only topics.
         boolean ditaFormat = f.format == null || "dita".equals(f.format);
         final int increment = isResourceOnly && ! ditaFormat ? 0 : 1;
         final Integer used = usage.containsKey(f.uri) ? usage.get(f.uri) + increment : increment;
         usage.put(f.uri, used);

         if (used > 1) {
             final URI result = addSuffix(f.result, "-" + (used - 1));
             final URI out = tempFileNameScheme.generateTempFileName(result);
             final FileInfo fo = new FileInfo.Builder(f)
                     .uri(out)
                     .result(result)
                     .build();
             // TODO: Should this be added when content is actually generated?
             job.add(fo);
             return new ResolveTask(scope, f, fo);
         } else {
             return new ResolveTask(scope, f, null);
         }
     }

**Comment by FranceBaril** [comment]
Hi, 

I asked Radu for a build with the patch for this issue because I have a client that urgently needs for keyscope to work in conreffed content. I was able to confirm that it works for HTML and PDF (XSL-FO) outputs. 

I had problems testing with maps and topics that used XSD and had to convert everything to DTDs, not sure if it was related to the patch or the specific Oxygen publishing engine configuration. 

Is it possible to let us know when this patch will be pulled into the main branch? A date will help us decide if we sit back and chill or if we need to implement our plan B that implies a lot of conditional filters and ditavalref.

Thanks!
