### ISSUE TITLE
ID processing of con(key)ref-ed elements

### ISSUE THREAD

**Issue by Snafu** [dita-ot/dita-ot#3736]
## Expected Behavior
Elements keep their ID as specified. Links to conrefed element IDs should work

## Actual Behavior
Element IDs are randomized to prevent duplicate IDs. PDF and HTML result differs. HTML can link to the topic but not the actual ID, PDF link does not work at all.

## Possible Solution

1. Only randomize IDs if they are not unique in the context
2. Do not randomize IDs and only accept first ID occurrence in any given context ingoring any other equal IDs. Similar to key behaviour in keyscope context.

## Steps to Reproduce
Create PDF / HTML from https://gist.github.com/Snafu/fe99e12669ae98707722631764d623e8

## Copy of the error message, log file or stack trace
Not releveant

## Environment
Any DITA-OT environment

* DITA-OT version: DITA-OT version 3.6.0
* Operating system and version:
  Windows
* How did you run DITA-OT?
  Directly or via oXygen
* Transformation type:
  HTML 5, PDF, HTML PDF

**Comment by Snafu** [comment]
The current behaviour is actually described in [this ticket](https://github.com/dita-ot/dita-ot/issues/1091). I want to re-start a discussion on the implemented behaviour since I see a clear DITA spec violation.

After many hours of dealing with exactly this issue I would like to know if the opinions have changed regarding this issue in the meantime. I know that the linked issue has been closed in 2013, almost a decade ago, but the problem still exists.
I have a use case where I cannot modify input data and it is exactly in the format that krivenia reported on SourceForge. I do, however, have to link to specific content within the conref-ed topic. This is as of today not possible due to aforementioned reason.

I don't understand the resoluiton that has been adopted. Like krivenia I cannot find the behaviour that IDs are changed in the DITA standard and from my point of view it is currently clearly violating DITA 1.3. See [Processing attributes when resolving conrefs](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/archSpec/base/conref-attributes-specified-on-elements.html#concept_m3j_jvb_lq)
It clearly states the following:

> A given attribute value on the resolved element comes in its entirety from either the referencing element or the referenced element; the attribute values of the referencing and referenced elements for a given attribute are never additive, even if the property (such as @audience) takes a list of values.
>
> If the referenced element has a @conref attribute specified, the above rules should be applied recursively with the resolved element from one referencing/referenced combination becoming one of the two elements participating in the next referencing/referenced combination. **_The result should preserve without generalization all elements that are valid in the originating context, even if they are not valid in an intermediate context._** 

Let me also share my thoughts on the discussion above. I do not see why changing the ID is required in the first place. DITA has the - in my mind _very_ annoying - way of handling keyscopes in a completely different way than anybody ever dealing with any kind of scope would expect. A very useful use case for keyscopes is prevented by design. Quoting from [Understanding Scoped Keys in DITA 1.3](https://www.oasis-open.org/committees/download.php/56472/Understanding%20Scoped%20Keys%20In%20DITA%201.3.pdf):
> The fact that a key definition at a higher level always takes precedence over one at a lower level would seem to prevent theuse of inherited, or fallback key definitions, and that is indeed the case. By "fallback," we mean the following situation: ...

My point is, if it was decided to go for this solution regarding keys, why couldn't a similar approach be done for IDs. Since currently the IDs of con(key)ref-ed topics are randomized there is no chance of linking to them. Therefore an approach that only accepts the first ID in a specific context and ignores duplicate IDs in the same context would be an equally suitable solution. A warning message could be issued but there is no need to stop the build. A webbrowser won't stop rendering a website if you give the same ID to two different HTML tags either.

**Comment by raducoravu** [comment]
If you want to attempt a workaround for this with a custom DITA OT plugin there is a DITA OT plugin extension point named "dita.xsl.conref":
https://www.dita-ot.org/dev/extension-points/all-extension-points.html#all-extension-points__dita.xsl.conref

which would allow a DITA OT plugin to contribute an XSLT stylesheet and overwrite content from the "plugins/org.dita.base/xsl/preprocess/conrefImpl.xsl" stylesheet.
If you look inside the "conrefImpl.xsl" it uses in various places the "generate-id" function, probably in one of those places it updates the IDs from the conreffed fragment to be unique.

**Comment by Snafu** [comment]
Hi raducoravu,
thanks for the tip with the DITA OT plugin. I'll definitely have a look.
I would be interested though in other peoples opinions on the matter. As I said, from my point of view it is a DITA spec violation and the renaming of an ID that is unique is completely unnecessary and does not bring any benefit, only a downside of guaranteeing that you cannot link to a "conref-ed" element ID. As a result, I would like to see this fixed in DITA but to be fully backwards compatible maybe only activate the new behavior, that being only rename on conflict, if it is activated via command line option, e.g. --lazy.rename=yes or --rename.id=[conflict,always,never].
I've tracked the issue down to the pre-processing stage, but haven't had a chance to poke around more in the Java code since the ".\gradlew dist" step fails for me on the HTML plugin (around 90% of progress). Some Saxon error. I'm using Zulu 8 JDK on Windows 10 Pro. Any help with getting the setup running appreciated (direct message or I open another issue regarding build setup).

**Comment by raducoravu** [comment]
@Snafu there is a DITA OT slack channel, maybe you can ask for help related to building the project on the general channel, but also give more details about it, for example the error message you receive in the console.

**Comment by robander** [comment]
While this behavior has certainly bugged me in the past, I want to note that the DITA spec is silent on this issue. The topic "Processing attributes when resolving conrefs" is explicitly about resolving attributes on the referencing element (the one with `@conref`) and the referenced element (the one addressed by that `@conref` attribute). It does not address what to do with ID attributes nested within that referenced element, so that behavior is left up to implementations.

This behavior has bugged me in the past when I've occasionally run into it. I'd be happier if there were a reliable way to set up these links. FWIW, here is a bit more info about why it currently works this way - meant as "how we ended up here", not "it has to work this way":

* In the first DITA-OT releases, before this generate-id attribute handling was introduced, the IDs were not changed as content came in. At the time, there were steps later in the processing chain that threw errors for duplicate IDs. Most of the rules around conref come down to "This cannot resolve in a way that would be invalid as a source doc" -- and duplicate IDs in a topic are not valid. Generated IDs guaranteed validity for this.
* Beyond the errors, it also resulted in unstable linking. For example, assume that I link to `<fig id="testanchor">` in a file. It works as authored, and works through many publishes. Then, `id="testanchor"` happens to get pulled in from someone else's topic using `@conref`, and is first in document order. Now my links are broken: they go to the wrong spot, and link text is either wrong (pulling a title from the new element) or invalid (just a file name if the new element has no title).
* We can assume that the one in the topic must be the one you want, but that's not guaranteed. If someone deep links into `testanchor` that comes in with conref, but then you add that same ID into your topic, links break in a way that is hard or impossible to catch during processing. Depending on your editor, this *might* be caught at authoring -- but it's not actually invalid because you don't have a duplicate ID within the topic.

The current behavior can change, but we would need to figure out how to handle those edge cases without breaking content / without putting a lot of "this might be broken but probably not" errors in the log.

**Comment by Snafu** [comment]
Thank you for the detailed explanation robander. What bugs me the most in the current implementation is that the PDF output shows you a link but when you click on it nothing happens because the target ID has been renamed. Therefore you have dead links in the PDF, which are not stripped away even with the "remove-broken-links" parameter set to "true".

In my specific use case we have DITA topics generated by an external tool. This external tool makes use of conrefs and conkeyrefs in some configurations. The tool ensures that all IDs in the entire map are unique, because it generates the IDs based on the unique identifiers of the data source. Therefore it is impossible to have duplicate IDs in this setup but because of the ID randomization you cannot link to specific elements.
Is there some other way how to work around in the meantime? Still have to evaluate the plugin that raducoravu mentioned.

**Comment by robander** [comment]
@Snafu The only way to work around it would be a plugin like Radu mentioned - you could override the code from `conrefImpl.xsl` that replaces the IDs, and ensure that they are not modified.

**Comment by Snafu** [comment]
I've had a look at org.dita.base\xsl\preprocess\conrefImpl.xsl but since I'm not familiar with XSLT I'm no understanding everything 100%. What I can see is that the generate-id function is defined in org.dita.html5\xsl\functions.xsl and org.dita.xhtml\xsl\xslhtml\dita2htmlImpl.xsl but nowhere else, which seems odd to me. The functions are both harmless, they just do a string join of topic and element.
Nevertheless I sifted through the code got the main idea of all the transformations. At line [533](https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.dita.base/xsl/preprocess/conrefImpl.xsl#L533) looked it looked like I had found what I had looked for. I changed it according to [this gist](https://gist.github.com/Snafu/44346e879d588a83b764b3938c45b20d) and my intermediate file now has the correct IDs and in the PDF the link now works as well 😊
Would be great if you could give me any feedback if anything else is affected by my change. From my interpretation not, since I only modified the line that changes the ID attribute of the "included" elements.

Thanks for your help, didn't have to sort out the .\gradlew dist issue after all.

**Comment by stunorton** [comment]
I wanted to note that coincidentally my team has run into this issue now as well, almost at the same time. It seems pretty clear to me that this is a case for which the "solution" is worse than the initial problem. In order to avoid the danger of duplicate link targets, we are producing unstable link targets that break from one publication to the next. Until now I was not aware that this fix also caused PDF links to break, which is even worse.

Thanks all for working on this! I will also ask our team to take a look at this problem and the possible solution.

**Comment by Snafu** [comment]
@stunorton I agree with you that the cure is worse than the disease, at least it seems that way nowadays and definitely is that way for my scenario. I can fully understand the history that @robander explained but in hindsight it would have been nice to add a command line switch to let the user decide if the IDs will be renamed or not.

**Comment by Snafu** [comment]
Hi all,
I see that three has been someting going on. I've also improved my solution, since I forgot to also take care of the ID part in references.
My change (with added parameter) can be viewed here: https://github.com/dita-ot/dita-ot/commit/b420530b92c377b02d64497b49ac66dc4ae4ed54
I wanted to create a change request but still have to update the docrsc file I think.

**Comment by mumashankar** [comment]
Hi all,
Thanks for discussing this issue. We are impacted by this. 

So, is this issue being fixed in upcoming DITA-OT releases?

**Comment by Snafu** [comment]
Hi @mumashankar,
there is a pull request by @jelovirt https://github.com/dita-ot/dita-ot/pull/3739 that fixes the issue. The fix only generates new IDs if an ID is already present in the topic. The feature branch is currently awaiting a code review before it can continue in the workflow. We'll just have to wait for the normal workflow to be completed, the good news is that it is being fixed 😊

Regarding when this will be available, this usually depends not only on when the fix is merged in to the development branch but how the releases are scheduled. So it could be that even though it might be in the development branch soon that it won't be in the next DITA-OT release. Maybe one of the developers can give you a more detailed answer.

**Comment by mumashankar** [comment]
Thank you @Snafu.
