### ISSUE TITLE
Allow the messages.xml to also specify an URL where more details about problem are found

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#4059]
Let's say by DITA OT plugin has a messages.xml file with messages like:

     <message id="PDFJ002E" type="ERROR">
        <reason>The build failed due to problems encountered when sorting the PDF index.</reason>
       <response>Please address any messages located earlier in the log.</response>
     </message>

maybe besides the reason, the message could also have an optional link to a web site where more details could be found.
Some kind of:

     <reason seeAlso="https://somesite/target">The build failed due to problems encountered when sorting the PDF index.</reason>

**Comment by infotexture** [comment]
🤔 Wondering the same.

In the DITA-OT docs, we use `conaction="pushreplace"` to augment the message text with additional details as shown in the [error messages](https://www.dita-ot.org/dev/topics/error-messages.html) topic. Many of those contain links.

To keep log messages brief, we consciously add these details in the docs, rather than generating longer messages for each error. There's certainly nothing to stop anyone from adding links to custom messages with the current format. 

Unless logging systems and/or terminal applications render these as clickable hyperlinks, I'm not sure how useful plain text URLs would be if users have to copy/paste to visit them.

Tools like oXygen could be configured to auto-link any plain text URLs in their own log views, but that wouldn't seem to require an additional attribute in the log format.

Perhaps @raducoravu could provide more details on what use cases this change would enable.

**Comment by raducoravu** [comment]
Oxygen gathers various [DOTYYY] errors from the console and presents them in a separate tab. For each [DOTYYY] error we have a small link to the left of the message which takes people to the userguide topic @infotexture using the error code as the URL anchor.
<img width="745" alt="Screenshot 2022-11-24 at 12 27 39" src="https://user-images.githubusercontent.com/1005979/203761362-e8a9caba-41a4-4396-96f8-1149176323f4.png">

There are people creating their own plugins, having their own messages.xml with custom codes like [CUSTOMPDFYYY] which Oxygen should also  gather (it does not gather them now) and maybe they also want to add a custom URL for each message where people can read more about it. So this is why I thought the messages.xml would be a good place where for each message maybe to add an extra URL pointing to additional documentation.

But the messages.xml does not seem to have a DTD or to be validated in any way when loaded so this is probably not something the DITA OT should do anything about as we can suggest the end users to add the URL in a certain way to the XML message file (maybe as a processing instruction or as some kind of attribute) and change Oxygen to recognize such constructs, keep a mapping between error codes and URLs and use the mapping when it detects an error code in the console.
