### ISSUE TITLE
Footnote in <title>, footnote text appears in <xref>

### ISSUE THREAD

**Issue by markgif** [dita-ot/dita-ot#4269]
## Expected Behavior

An xref to a title element should show the content of <title> without the <fn> text. When published, the <fn> text should only appear in a footnote.

## Actual Behavior

The <fn> text appears in the cross reference.

## Possible Solution

I fixed this in version 2.5.4, so I will refrain from doing a PR. But I tested it with DITA OT 4.0.2 and the bug is still there. Here is my fix in OT 2.5.4 in links.xsl (see "markg" changes):

    <xsl:template match="*[contains(@class,' topic/xref ')]" name="topic.xref">
    <xsl:variable name="destination" select="opentopic-func:getDestinationId(@href)"/>
    <xsl:variable name="element" select="key('key_anchor',$destination, $root)[1]"/>
      
    
    <xsl:variable name="element2">
      <xsl:apply-templates select="$element" mode="removefn"/>
    </xsl:variable>

    <xsl:variable name="referenceTitle" as="node()*">
      <xsl:apply-templates select="." mode="insertReferenceTitle">
        <xsl:with-param name="href" select="@href"/>
        <xsl:with-param name="titlePrefix" select="''"/>
        <xsl:with-param name="destination" select="$destination"/>

        
        <xsl:with-param name="element" select="$element2"/>
      </xsl:apply-templates>
    </xsl:variable>
    [...]
    </xsl:template

    
    <xsl:template match="fn" mode="removefn" />
    <xsl:template match='@* | node()' mode="removefn">
      <xsl:copy>
        <xsl:apply-templates select='@* | node()' mode="removefn"/>
      </xsl:copy>
    </xsl:template>

## Steps to Reproduce

1. Add a footnote to a <title> element like this:
    &lt;fig id="figureID">
         &lt;title>Washing the car &lt;ph>&lt;fn>HEY( fig footnote )&lt;/fn>&lt;/ph>&lt;/title>
         &lt;image href="../image/carwash.jpg" alt="washing the car" height="171" width="249"/>
    &lt;/fig>
2. Do a cross ref to the <title> element:
&lt;p> For more information, see &lt;xref href="washingthecar.dita#washcar/figureID" />&lt;/p>

3. Run a PDF (this was only tested on pdf output), and the footnote text appears in the cross reference like this:
For more information, see Washing the car HEY( fig footnote )

[garage.zip](https://github.com/dita-ot/dita-ot/files/12387358/garage.zip)

## Environment

* DITA-OT version: 2.5.4, 4.0.2
* Operating system and version: Windows 10
* How did you run DITA-OT? Oxygen
* Transformation type: pdf2

**Comment by chrispy-snps** [comment]
I'll take a look at this.

**Comment by chrispy-snps** [comment]
The `<title>` element's content model is restrictive in the child elements it allows. However, one of those elements is the `<ph>` element, whose content model is more permissive. This allows unintended elements to "sneak in" to a `<title>` element.

Here is the list of elements disallowed in `<title>` that can sneak in via `<ph>`:

```
<codeblock>
<div>
<dl>
<equation-block>
<equation-figure>
<fig>
<fn>
<hazardstatement>
<imagemap>
<indexterm>
<indextermref>
<lines>
<lq>
<msgblock>
<note>
<object>
<ol>
<parml>
<pre>
<screen>
<simpletable>
<sl>
<syntaxdiagram>
<table>
<ul>
<xref>
```

I will make a testcase to see what the current publishing behaviors are for each element, specifically for:

* How link target text is computed for references using that `<title>` in `topicpull`
* How the `<title>` element itself is published in format-specific output transformations

Then we can decide how each sneaky element should be handled (unwrapped to text, omitted, etc.).

**Comment by chrispy-snps** [comment]
In the following testcase:

[4269.zip](https://github.com/dita-ot/dita-ot/files/12445792/4269.zip)

For the PDF and HTML5 publishing of `<title>` content elements, the behaviors seem correct:

* `<fn>` elements add a footnote to the title where appropriate.
  * The numbering seems off, possibly due to `<fn>` elements in the TOC.
  * This can probably be categorized as unsupported.
* `<indexterm>` elements are not published.
* `<xref>` elements compute their usual link target text.

For `topicpull` link target text computed from `<title>` content elements, only the `<fn>` element seems to be problematic:

* `<fn>` elements include the actual full footnote text (incorrect!).
* `<indexterm>` elements are not published.
* `<xref>` elements with explicit link text use that text.
* `<xref>` elements without target text are empty.
  * This might be because link text computations are not recursive.
  * This can probably be categorized as unsupported.
