### ISSUE TITLE
Update Apache FOP to version 2.9

### ISSUE THREAD

**Issue by jlacour31** [dita-ot/dita-ot#4272]
A new FOP version is available: https://xmlgraphics.apache.org/fop/2.9/releaseNotes_2.9.html
With all its satellite libraries:
 - Apache XML Graphics Commons
 - Apache FOP-PDF-Images
 - Apache Batik (1.17)

Also in `org.dita.pdf2.fop/lib` there's an extra fop.jar which seems useless.

**Comment by raducoravu** [comment]
Possibly one of the reason for this release was also to patch this security problem in Batik 1.17:
https://nvd.nist.gov/vuln/detail/CVE-2022-44729

**Comment by raducoravu** [comment]
The problem is that the FOP 2.9 library which was supposed to contain all FOP classes is now somehow placed with an almost empty content on Maven:
https://repo1.maven.org/maven2/org/apache/xmlgraphics/fop/2.9/
Probably all 3 libraries fop-core, fop-events and fop-util need to be individually used instead.
