### ISSUE TITLE
coderef tag when scope=peer doesn't work

### ISSUE THREAD

**Issue by amyhiggins** [dita-ot/dita-ot#4417]
Referring to the directory structure below, say I'm building plugin2 with dita-ot (tested with versions 3.7 and 4.2).

If file.dita references code_example.c in a coderef tag, the output results in an empty codeblock when I add the scope=peer attribute to the tag. If I don't add the attribute to the tag, it builds fine, but unfortunately it's seems to be required when building individual plugins with Oxygen XML WebHelp (which is what I'm using).

Tested the pdf and html transform too, and they gave the same results. So I don't think it's limited to Oxygen.

.
├── plugin1
│   └── code_example.c
├── plugin2
│   ├── main.ditamap
│   └── topic
│       └── file.dita

**Comment by robander** [comment]
In all dita-ot processing, `scope="peer"` is treated as a reference to a file that is not available to the toolkit for build purposes. For example, if you use `scope="peer"` on a topicref in a map, the referenced topics will no longer build (even if they really are present). Unless I'm missing something, I think this is consistent with all other processing for `scope="peer"`.

**Comment by raducoravu** [comment]
As @robander  said, if you want the code to actually appear you should not add scope=peer to it.
About this remark:

     but unfortunately it's seems to be required when building individual plugins with Oxygen XML WebHelp

Can you give us more details? Probably the cause is the link is outside of the main DITA Map folder.
If you are building the output from inside Oxygen, we have a transformation parameter named "fix.external.refs.com.oxygenxml" which might help if enabled:

https://www.oxygenxml.com/doc/versions/26.0/ug-editor/topics/dita-ot-external-refs.html

Recent versions of the DITA OT have a "preprocess2" processing option which no longer has problems with references outside of the published DITA Map folder but the default WebHelp output obtained with Oxygen is obtained with an older "preprocess" stage which has this problem.

**Comment by amyhiggins** [comment]
Ah okay, setting the `scope="peer"` issue aside, you seem to have pinpointed my problem ("...the default WebHelp output obtained with Oxygen is obtained with an older "preprocess" stage which has this problem"). Thanks for the help!

**Comment by raducoravu** [comment]
@amyhiggins if you are publishing using an Oxygen transformation scenario, if you open the DITA Map in the Oxygen DITA Maps Manager view and use the "Configure Transformation Scenarios" toolbar button, press "New->DITA OT transformation" and you will be able to choose "WebHelp Responsive using preprocess2 DITA-OT step" as a transformation type if you want to try how WebHelp Responsive with "preprocess2" would work. But we do not officially support it or run all our automatic tests with it.
