### ISSUE TITLE
Include third-party sources in source package

### ISSUE THREAD

**Issue by glatuske** [dita-ot/dita-ot#4500]
## Description
DITA-OT provides a source package which includes the sources of DITA-OT it self but not of third-party libraries shipped with DITA-OT.
For our commercial product using DITA-OT we have to ship all sources. This currently means to manually go through the DITA-OT dependencies and add the sources.

## Possible Solution
An additional package could be created including the source JARs of all dependencies. This could be completely handled using Gradle.

## Potential Alternatives
none

## Additional Context
none

**Comment by jelovirt** [comment]
IMO we should not do this, because the Java source code is not used by our binary distribution package, neither our own or third-party party Java code. If some user needs to bundle the source code for all third-party libraries, it should be up to them to make the distribution. Note that the source code for all third-party libraries may not be easily available and this effort would only affect very few individual users.

**Comment by jelovirt** [comment]
@glatuske My suggestion is that you fork the DITA-OT repo, make the necessary changes to the Gradle build to bundle the third-party sources, and create your own distribution packages.
