### ISSUE TITLE
keyref element's with whitespace replaces the text content

### ISSUE THREAD

**Issue by ChrisTrenkamp** [dita-ot/dita-ot#4543]
## Expected Behavior
According to the specification: http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/archSpec/base/processing-keyref-for-text.html#processing_key_references

Empty elements that include a key reference with a defined key might get their effective content from the key definition. Empty elements are defined as elements that meet the following criteria:

* Have no text content, including white space 

So I would expect XML such as `<ph keyref='key'> </ph>` to display empty text.

## Actual Behavior
The XML `<ph keyref="key"> </ph>` results in the following HTML: `<span class="ph"> some key</span>`, which is in contradiction with the specification.  There are no errors reported.

## Steps to Reproduce

[dita-keyref-whitespace-issue.zip](https://github.com/user-attachments/files/17757904/dita-keyref-whitespace-issue.zip)

## Copy of the error message, log file or stack trace
There are no errors in the console.

## Environment
Windows 11

* DITA-OT version: 4.2.3
* Operating system and version: Windows
* How did you run DITA-OT? `dita`
* Transformation type: `html5`

**Comment by jelovirt** [comment]
Need to verify this is a valid but. If so, this is a problematic because fixing it may break _a lot_ of content that assumes whitespace only is treated as an empty element.

**Comment by jelovirt** [comment]
@robander unfortunately it seems the implementation has this bug. Will need to discuss how to fix this.

**Comment by jelovirt** [comment]
Closing this as fixed and not fixed at the same time. Out of the box DITA-OT 4.2.4 will behave the same way as before, i.e. it will tread whitespace only keyref element as empty. This is due to backwards compatibility issues, as fixing the bug could potentially break existing content that used to work. Relying on a bug is not a good approach, but if the user doesn't know the behaviour is due to a bug, that's different.

We will toggle the fix on in either 4.3 or 5.0.
